### ISSUE TITLE
There is some thing wrong with function addShape in "pascal_voc_io.py" and I've modefied it.

### ISSUE THREAD

**Issue by RosinLee** [tzutalin/labelImg#10]
When you load annotations from local xml file and change the position of the points ,the shape will change irregularly. 

In "pascal_voc_io.py", function "addShape()",line 121

it should be: 

`points = [(xmin,ymin), (xmax,ymin), (xmax, ymax), (xmin, ymax)] `

rather than:

`points = [(xmin,ymin), (xmin,ymax), (xmax, ymax), (xmax, ymin)] `

**Comment by tzutalin** [comment]
Could you provide your xml and image to me?

Let me try it.

**Comment by RosinLee** [comment]
@tzutalin I'm sorry that the date provider does not alow to leak the pic. The xml was created by this toolkit. May be something wrong with my data and I'll check it. Thanks.

**Comment by tzutalin** [comment]
@RosinLee ,
  Thanks. I am looking forward to your feedback
