### ISSUE TITLE
Python 2.6 throws an error "File "./labelImg.py", line 786     extensions = {'.jpeg','.jpg', '.png', '.bmp'}"

### ISSUE THREAD

**Issue by nobuyukioishi** [tzutalin/labelImg#101]
Thank you for this great GUI application.
I checked that it is working properly but I noticed one thing.

When I execute 'labelImg.py' with Python 2.6, the program throws error
"File "./labelImg.py", line 786     extensions = {'.jpeg','.jpg', '.png', '.bmp'}"

I think it should be "extensions = set('.jpeg','.jpg', '.png', '.bmp')" with Python 2.6
or
You should clarify to use Python 2.7.

I think that clarifying to use Python 2.7 is better because opencv-python no longer supports Python 2.6.
Python 2.7 is the only supported version in 2.x series. [opencv-python](https://pypi.python.org/pypi/opencv-python)

Again, thank you for making this useful application.

- **OS:** mac OS Sierra Version 10.12.5
- **PyQt version:** 4.11.3

**Comment by tzutalin** [comment]
Hi @nobuyukioishi ,
  Thanks for your suggestion. I will update our code or README according to your suggestions.
