### ISSUE TITLE
Is there anyway to add truncated option?

### ISSUE THREAD

**Issue by TrinhTUHH** [tzutalin/labelImg#102]
Hi,
Thank you very much for this tool. I have seen "difficult" box on the GUI and it would be helpful if you could add a "truncated" box also.

**Comment by TrinhTUHH** [comment]
I have solved it after looking through the code. Simply changing .txt file below to .py file and make folder again. Then you would get truncated option. Please let me know if there's anything wrong.
[
[labelImg.txt](https://github.com/tzutalin/labelImg/files/1079216/labelImg.txt)

](url)

**Comment by ChrisDal** [comment]
Hi, 

From memory you have to change the contents of `Shape` associated to `PascalVocReader` class, and all the dependency with the shapes ( `LabelFile` class to save the annotation), maybe look for the keyword difficult through the repository you will eventually find all the dependencies :) 

In `./libs/pascal_voc_io.py` , there is a the "implementation" of truncated objects (on the edge of the image basically), you will have to adapt it : 

```
truncated = SubElement(object_item, 'truncated')
# max == height or min 
if int(each_object['ymax']) == int(self.imgSize[0]) or (int(each_object['ymin'])== 1):
    truncated.text = "1"
    # max == width or min 
elif (int(each_object['xmax'])==int(self.imgSize[1])) or (int(each_object['xmin'])== 1):
    truncated.text = "1"
else:
    truncated.text = "0"
    difficult = SubElement(object_item, 'difficult')
    difficult.text = str( bool(each_object['difficult']) & 1 )
```

**Comment by TrinhTUHH** [comment]
Hi Chris,
You're right! I have known about this after reading the code. My modification is unnecessary.

**Comment by nanhui69** [comment]
@TrinhTUHH does the context  ：
from lib import struct, newAction, newIcon, addActions, fmtShortcut
from shape import Shape, DEFAULT_LINE_COLOR, DEFAULT_FILL_COLOR
from canvas import Canvas
from zoomWidget import ZoomWidget
from labelDialog import LabelDialog
from colorDialog import ColorDialog
from labelFile import LabelFile, LabelFileError
from toolBar import ToolBar
from pascal_voc_io import PascalVocReader
from pascal_voc_io import XML_EXT
from ustr import ustr
 is right ？ the lib is'not in the project，also for for the struct,newAction,new Icon...,so ?
