### ISSUE TITLE
multiple points are overlaped, program crashes

### ISSUE THREAD

**Issue by zsz02** [tzutalin/labelImg#108]
bug :
When i draw a box , if there are multiple points are overlaped , then the program crashes when i drag point

**Comment by tzutalin** [comment]
Hi @zsz02 ,
 Can you describe more regarding your steps, environement, and version?

**Comment by zsz02** [comment]
win10,  python3.5 
V1.3.4
![bug](https://user-images.githubusercontent.com/23742288/27964159-e4db546c-6369-11e7-993f-382efed82540.jpg)

**Comment by tzutalin** [comment]
Hi @zsz02 ,
  I will try to get a laptop with win10

**Comment by zsz02** [comment]
i think  the bug on all platform ,, you can try and  fixed it ..

**Comment by zsz02** [comment]
ok, i fixed it
