### ISSUE TITLE
The effect of Difficult button 

### ISSUE THREAD

**Issue by 315386775** [tzutalin/labelImg#113]
This pull contains :

- Difficult checkbox to label difficult or with occlusion object (saved in shape)

```
	<object>
		<name>cat</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		**<difficult>1</difficult>**
		<bndbox>
			<xmin>141</xmin>
			<ymin>459</ymin>
			<xmax>343</xmax>
			<ymax>719</ymax>
		</bndbox>
	</object>
```

i don't know the meaning and the effect. Can anyone help me?

**Comment by tzutalin** [comment]
From my point of views, 'difficult tag' is designed for object detection to exclude the samples labeled as difficult

**Comment by srafay** [comment]
so if you select difficult attribute for an object, it will not be considered in training of the model?
@tzutalin

**Comment by vdalv** [comment]
@srafay No, I don't believe that's correct.
@315386775 Here's an explanation of the difficult attribute:

"The difficult field being set to 1 indicates that the object has been annotated as "difficult", for example an object which is clearly visible but difficult to recognize without substantial use of context." - [Source](https://github.com/tensorflow/models/issues/2386#issuecomment-330948518)

**Comment by srafay** [comment]
@vdalv alright thanks!

**Comment by karenkao** [comment]
@vdalv  nice explanation, thanks.
