### ISSUE TITLE
add openPrevImg and openNextImg action to advanced mode

### ISSUE THREAD

**Issue by GarrickLin** [tzutalin/labelImg#115]
Advanced mode speeds up annotation efficiently, but I got confused there is not a good way to switch to next/prev image. Is is function under development or just I didn't find it?
- **OS:** Windows10
- **PyQt version:** py2-qt4

**Comment by GreenKing** [comment]
I add the functionality by modifying [here](https://github.com/tzutalin/labelImg/blob/py2-qt4/labelImg.py#L306)
```
self.actions.advanced = (
            changeSavedir, opendir, openNextImg, openPrevImg, save, None,
            createMode, editMode, None,
            hideAll, showAll)
```
