### ISSUE TITLE
Why <annotation verified="no">

### ISSUE THREAD

**Issue by squirrel233** [tzutalin/labelImg#117]
`<annotation verified="no">`
Why this line has `verified="no"` in my generated xml file? In original PASCAL VOC xml and the demo, I didn't see this.
Thanks

- **OS:Ubuntu16.04**
- **PyQt version:Python 2 + Qt4**

**Comment by tzutalin** [comment]
HI @squirrel233 ,
  This feature is implemented by https://github.com/tzutalin/labelImg/pull/64.

I tried to remove it by default in the latest code. https://github.com/tzutalin/labelImg/commit/398da39dce942e8d9f4f504323a2c0a5f205227e

**Comment by squirrel233** [comment]
@tzutalin Thanks for helping
