### ISSUE TITLE
How to keep annotations of prev-image still exist when I open the next image?

### ISSUE THREAD

**Issue by zhonghuabao1** [tzutalin/labelImg#118]
Hi, thanks for your good job firstly!
      My images are captured from video, so the prev-image are similar with next-image. but when I open next image, previous annotations disappear. I don't want to create then again, since they are useful for the next image.
      I tried to modify you codes, but failed. can you tell me how to do it ?

**Comment by zhonghuabao1** [comment]
and there is a bug when 'open annotation file', nothing load !

**Comment by zhonghuabao1** [comment]
I have deal with it.
modify the code in labelImg.py(line in 928) as:
---------------------------------------------------------------------------
       # Label xml file and show bound box according to its filename
            if self.usingPascalVocFormat is True:
                if self.defaultSaveDir is not None:
                    basename = os.path.basename(
                        os.path.splitext(self.filePath)[0]) + XML_EXT
                    xmlPath = os.path.join(self.defaultSaveDir, basename)
                else:
                    xmlPath = filePath.split(".")[0] + XML_EXT

                if self.loadPascalXMLByFilename(xmlPath) is None:
                    self.loadPascalXMLByFilename(self.prev_xmlpath)
                else:
                    self.prev_xmlpath = xmlPath
----------------------------------------------------------------------------
and at the end of function ' loadPascalXMLByFilename() ' add:  return Ture

**Comment by tzutalin** [comment]
Hi @zhonghuabao1 ,
  Thanks for your information. I fixed it.

**Comment by kmsravindra** [comment]
I modified labelImg to accomodate this change. You can find it here - https://github.com/kmsravindra/labelImg

I can do a pull request to add this change here as well...But from what I seen, the pull requests are not being merged into the repo here...
