### ISSUE TITLE
make: *** No rule to make target `qt4py2'.

### ISSUE THREAD

**Issue by rilias92** [tzutalin/labelImg#119]
When i run << make qt4py2 >> i get this --> make: *** No rule to make target `qt4py2'. Stop.
Can anyone help me with this?

- El Capitan 10.11.6
- Qt4

**Comment by lgallen** [comment]
Was this issue resolved? Can you offer an explanation of how?

**Comment by nivetaiyer** [comment]
I need an explanation too! Get the same error.

**Comment by rilias92** [comment]
Hello guys, sorry for the late answer, I was on vacation.
I forgot to write how the problem was solved for me.
The problem was resolved when installing Qt. I had downloaded it but I did not install it.
Http://doc.qt.io/qt-4.8/install-mac.html
Thank you!!

**Comment by mateusmecunhe** [comment]
One issue that may also be causing this type of erorr is that you didn't git clone the project.
1st thing to do on terminal is:
$ git clone https://github.com/tzutalin/labelImg.git
$ cd labelImg

then, follow the steps here:
https://github.com/tzutalin/labelImg#ubuntu-linux
