### ISSUE TITLE
Toolbar doesn't open again once it was closed

### ISSUE THREAD

**Issue by Falcatrua** [tzutalin/labelImg#12]
Once I closed to toolbar I could never show it again. Not even deleting and reinstalling it.

**Comment by jlevis73** [comment]
Same here

**Comment by faschinj** [comment]
I also had an issue with this. However when I did what @jlevis73 suggested I did not get the exact same toolbar back. Specifically the forward and backward buttons were gone. To remedy the situation on Ubuntu linux I removed the settings file. This was stored at ~/.config/Unknown Organization/labelImg.conf. After I did this the default settings returned.

**Comment by tzutalin** [comment]
If you right click on the label panel (right bar) and check tools, the left bar will return.

**Comment by bertalanimre** [comment]
2019 and the "check tools" doesn't exist any more. Any other way to get the left hand toolbar back?
