### ISSUE TITLE
Install in windows 7

### ISSUE THREAD

**Issue by ManojPabani** [tzutalin/labelImg#120]
I have downloaded the zip file and the setup.py to install labelimg in windows 7.Here is my command and result:

> C:\Users\Manoj\Downloads\labelImg-master\labelImg-master>python setup.py
> usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
>    or: setup.py --help [cmd1 cmd2 ...]
>    or: setup.py --help-commands
>    or: setup.py cmd --help
> 

error: no commands supplied

which argument should i give?
I have installed PyQt4 and lxml successfully,I am using Python 3.5
By installing through pip is giving me this error:

> C:\Users\Manoj\Downloads\labelImg-master\labelImg-master>pip install labelImg
> Collecting labelImg
>   Using cached labelImg-1.3.4.0.tar.gz
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "C:\Users\Manoj\AppData\Local\Temp\pip-build-3ew1c3zy\labelImg\setup.
> py", line 7, in <module>
>         readme = readme_file.read()
>       File "c:\python35\lib\encodings\cp1252.py", line 23, in decode
>         return codecs.charmap_decode(input,self.errors,decoding_table)[0]
>     UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 4800:
>  character maps to <undefined>
> 
>     ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in C:\Users\Manoj\Ap
> pData\Local\Temp\pip-build-3ew1c3zy\labelImg\

**Comment by vdalv** [comment]
Please download the latest code or release and follow the current setup instructions for your environment. And let us know if you face any other issues.

Thanks,

-Vlad
