### ISSUE TITLE
'pyrcc4' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by ManojPabani** [tzutalin/labelImg#121]
Hi,I am trying install LabelImg from source,I have installed PyQt4 and lxml now when runing this command:
`pyrcc4 -o resources.py resources.qrc`
getting this error:

> 'pyrcc4' is not recognized as an internal or external command,
> operable program or batch file.
I tried to install  'pyrcc4' using:
pip install  pyrcc4
but it did'nt work.

**Comment by tzutalin** [comment]
Have you installed pyqt4-dev-tools?

**Comment by MaxeeoveCR** [comment]
Add your pyqt4 path to your system PATH.

**Comment by Abby263** [comment]
How to add to system PATH ?

**Comment by romulo37** [comment]
I tested with PyQt5. 
Just download it and add to system path "[path to anaconda]\Anaconda3\Library\bin". 
Then execute:
Open cmd and go to labelImg directory
pyrcc5 -o resources.py resources.qrc   
python labelImg.py

Done!

Tested on Anaconda3, PyQt5, Win10 x64

**Comment by valleyzine** [comment]
Riverbank does not support qt4..
where can i get the pyqt4-dev-tools(for pyrcc4) ?

**Comment by vicflamenco** [comment]
Win8.1, 64bit, Python 3.7.4, PyQt5
My solution was:
`pyrcc5 -o resources.py resources.qrc`

And, in the `labelimg.py` file, change line: 
`from libs.resources import *`
to:
`from resources import *`

**Comment by h2ochipdotcom** [comment]
Im using PySide2 and Python3 on Win 10. After searching my files in my python installation I found that the pyrcc4/5 file was not present but has been replaced. Here's the command I used to get the same result.
`pyside2-rcc -py3 -o ip2img.py ip2img.qrc`

**Comment by chentongwilliam** [comment]
> Im using PySide2 and Python 3.6.5 on Win 10. After searching my files in my python installation I found that the pyrcc4/5 file was not present but has been replaced. Here's the command I used to get the same result.
> `pyside2-rcc -py3 -o ip2img.py ip2img.qrc`

Hi h2ochipdotcom,
im trying to replace pyqt5 with pyside2 on win 10 but failed with no error reported in shell.
python version: 3.8.2
what i have done:
1. pyside2-rcc resources.qrc -o resources.py 
2. replace from PyQt5.QtGui import *
                from PyQt5.QtCore import *
                from PyQt5.QtWidgets import *
with     from PySide2.QtGui import *
            from PySide2.QtCore import *
            from PySide2.QtWidgets import *
in all files.
3. In canvas.py: CURSOR_DEFAULT = QCursor(Qt.ArrowCursor) ...

Then i run labelImg.py in IDLE and no error are shown but after few seconds shell restarts.
Can you help me about this? Thanks a lot!!!
