### ISSUE TITLE
Is there any tool for image semantic segmentation labeling?

### ISSUE THREAD

**Issue by xjock** [tzutalin/labelImg#122]
Maybe add a polygon tool for this lableImg software?

**Comment by fastlater** [comment]
@xjock  did you find one? If yes, can you let me know.

**Comment by vdalv** [comment]
I think this tool has what you're looking for: https://github.com/wkentaro/labelme

**Comment by ryouchinsa** [comment]
If you are using Labelme, use this script to convert the COCO segmentation format to the YOLO segmentation format.
https://github.com/ultralytics/JSON2YOLO

RectLabel is an offline image annotation tool for object detection and segmentation.
Although this is not an open source program, with RectLabel you can read/write/export the YOLO segmentation format.
https://rectlabel.com/help#xml_to_yolo
```
class_index x1 y1 x2 y2 x3 y3 ...
0 0.180027 0.287930 0.181324 0.280698 0.183726 0.270573 ...
```
![yolo_polygon](https://user-images.githubusercontent.com/1954306/214472214-a9c2775d-247a-4bd1-87f6-9d90818ef8ff.jpg)
