### ISSUE TITLE
'Open Dir' mssing

### ISSUE THREAD

**Issue by stvogel** [tzutalin/labelImg#123]
- OS: ubuntu 16.04

The newest master seems to somehow lack the feature to open a directory.

![image](https://user-images.githubusercontent.com/4895281/28456588-2619e2b0-6e03-11e7-884e-51e69979ed62.png)

Did I miss something?

**Comment by tzutalin** [comment]
@stvogel ,
  You might enter to 'advance mode'. Go to 'View' on menu, and uncheck  'advance mode'

**Comment by stvogel** [comment]
Uuuuh. Shame on me.
Sorry for that. 
And thanks for helping out.
