### ISSUE TITLE
Problems with running labelImg.py on macos

### ISSUE THREAD

**Issue by zhoukaihui** [tzutalin/labelImg#124]
- **OS:**macOS 10.12.5
- **PyQt version:**PyQt4_gpl_mac-4.12.1
when I ran labelImg.py on macOS, I got this error:
~/Applications/labelImg-master » python labelImg.py                                                                 
Traceback (most recent call last):
  File "labelImg.py", line 1359, in <module>
    sys.exit(main(sys.argv))
  File "labelImg.py", line 1355, in main
    app, _win = get_main_app(argv)
  File "labelImg.py", line 1348, in get_main_app
    argv[2] if len(argv) >= 3 else os.path.join('data', 'predefined_classes.txt'))
  File "labelImg.py", line 426, in __init__
    self.recentFiles = list(settings.get('recentFiles', []))
TypeError: 'QVariant' object is not iterable

Any ideas? Thanks.

**Comment by stvogel** [comment]
I have the same problem running in ubuntu.
But only if I start labelImg the second time. On first time it works.

**Comment by tzutalin** [comment]
It had been fixed

**Comment by Turkmen1Mehmet** [comment]
> ###

How fixed?
