### ISSUE TITLE
'NoneType' object is not iterable

### ISSUE THREAD

**Issue by JerryLauzzz** [tzutalin/labelImg#125]
when I run labelImg.py, I met this trouble.
OS: Ubuntu17.04
Python: Anaconda Python3.6

Traceback (most recent call last):
  File "/home/jerry/deep_learning/labelImg-1.4.0/labelImg.py", line 1377, in <module>
    sys.exit(main(sys.argv))
  File "/home/jerry/deep_learning/labelImg-1.4.0/labelImg.py", line 1373, in main
    app, _win = get_main_app(argv)
  File "/home/jerry/deep_learning/labelImg-1.4.0/labelImg.py", line 1366, in get_main_app
    argv[2] if len(argv) >= 3 else os.path.join('data', 'predefined_classes.txt'))
  File "/home/jerry/deep_learning/labelImg-1.4.0/labelImg.py", line 433, in __init__
    self.recentFiles = list(settings.get('recentFiles', []))
TypeError: 'NoneType' object is not iterable

**Comment by tzutalin** [comment]
@JerryLauzzz ,
   I didn't test it on Ubuntu17.04 and Anaconda Python3.6 before. What's your version of QT? Can you find the root cause?

**Comment by JerryLauzzz** [comment]
I make some changes in labelImg.py, and it works.
"
try:
    self.recentFiles = list(settings.get('recentFiles', []))
except:
    pass
"
I think it's because when first start the labelImg.py, the settings['recentFiles'] is None. I always met 'NoneType' object is not iterable when I use Python3.6...

**Comment by JerryLauzzz** [comment]
I make some changes in labelImg.py, and it works.
"
try:
    self.recentFiles = list(settings.get('recentFiles', []))
except:
    pass
"
I think it's because when first start the labelImg.py, the settings['recentFiles'] is None. I always met 'NoneType' object is not iterable when I use Python3.6...

**Comment by JerryLauzzz** [comment]
I think it's more convenient if the all the images in the dir are listed in just one xml file.

**Comment by tzutalin** [comment]
@JerryLauzzz ,
  Thanks for investigating the problem. About your second question, do you mean use only one xml file for all of images in the same dir?

**Comment by JerryLauzzz** [comment]
@tzutalin 
Yes.

**Comment by tzutalin** [comment]
That is because ImageNet and Pascal competition use the format. 1 xml to 1 image
