### ISSUE TITLE
rm cv2 module

### ISSUE THREAD

**Issue by lzx1413** [tzutalin/labelImg#13]
I think that there is no need to import cv2 module in labelfile.py to get the image shape.

**Comment by tzutalin** [comment]
Hi @lzx1413 ,
  Currenetly, I used opencv to get the shape of image when creating pascal file. Do you have an alternative way to get shape of image?
libs/labelFile.py:
```
        img = cv2.imread(imagePath)
        imageShape = img.shape
```

**Comment by lzx1413** [comment]
``

**Comment by lzx1413** [comment]
in labelImg.py
```
image = QImage.fromData(self.imageData)
self.image_shape.append(image.width())
self.image_shape.append(image.height())
self.image_shape.append(3)//this is not good enough but I don not find a good function to meet it
```

**Comment by ck196** [comment]
If you only need shape of image, you could you PIL.
`
from PIL import Image

with Image.open(filename) as im:
    width, height = im.size
`
It is easy to install, openCV is very heavy and hard to install. It comes up for non-IT person use your tools.

**Comment by tzutalin** [comment]
Hi , 
 Sorry.  I am busy with other stuffs this month. I will remove Opencv next month. If possible, you can send a PR and test it, I will review and merge it.

**Comment by lzx1413** [comment]
Hi,
@ck196  yep,I just want to make the size of the software after packaged less :) 
@tzutalin  I have make a lot of change on this project,so it may be not easy to create a pr to merge it to this branch.It's just a suggestion to rm the opencv

**Comment by tzutalin** [comment]
Fix it 
4a3a47a
