### ISSUE TITLE
Bounding Boxes Stop Being Boxes when Corners Overlap at Time of Placement

### ISSUE THREAD

**Issue by ConlonNovak** [tzutalin/labelImg#130]
When creating a bounding box, move your pointer vertically or horizontally exactly in line with the original point. When you let go, the box is created and loos like a line segment, as expected. However, if you go to edit the box using its circular handles, the bounding box has lost a point, becoming a bounding triangle! It retains some of the movement behaviors of rectangles, but mostly just glitches around the screen as you drag its handles. [Edit: Additionally, if you place all four points at the same location, you get a bounding point that cannot be expanded further!] Not a critical bug, just a funny issue that I found and have been able to easily reproduce. I'd be curious to see what the .xml files look like with these triangles in them...

- Linux 16.04

**Comment by jaewchoi** [comment]
fixed by #151.

**Comment by tzutalin** [comment]
Nice
