### ISSUE TITLE
Files missing from build-tools folder

### ISSUE THREAD

**Issue by dcsds1** [tzutalin/labelImg#133]
**build-ubuntu-binary.sh** and **build-windows-binary.sh** are missing from the build-tools folder.

**Comment by tzutalin** [comment]
Hey, sorry.I made a mistake to remove it.

**Comment by tzutalin** [comment]
Fix it https://github.com/tzutalin/labelImg/commit/e86472a592f3740cb6d91f671ec69cecb93a4da1
