### ISSUE TITLE
ImportError: No module named 'resources'

### ISSUE THREAD

**Issue by swetshaw** [tzutalin/labelImg#135]
- **OS:** Windows 8.1
- **PyQt version:** PyQt5

How to get the resources file?

**Comment by swetshaw** [comment]
I just commented the **import resources**  line from labelImg.py and things are working.

I commented because **resources** is not being used anywhere in the code.

**Comment by dcsds1** [comment]
Hi @swetshaw , I guess you forget typing `pyrcc4 -o resources.py resources.qrc` first. This will generate the **resources.py** file you need. The **resources**  is for loading icons into the labeling tool. A detailed explanation can be found [here](http://pyqt.sourceforge.net/Docs/PyQt4/resources.html).
