### ISSUE TITLE
AttributeError: 'QStringList' object has no attribute 'remove'

### ISSUE THREAD

**Issue by Hitiron** [tzutalin/labelImg#136]
Traceback (most recent call last):
File "./labelImg.py", line 1096, in openDir
   self.openNextImg()
File "./labelImg.py", line 1158, in openNextImg
   self.loadFile(filename)
File "./labelImg.py", line 937, in loadFile
  self.addRecentFile(self.filePath)
File "./labelImg.py", line 554, in addRecentFile
   self.recentFiles.remove(filePath)
AttributeError: 'QStringList' object has no attribute 'remove'

 When i click 'Open Dir' ,this problem happen ,and 'File list' is empty ,when i click 'Next Image' or 'Prev Image' ,the image show correctly in the main window, but the same error log appear again,just like above.
This tool is really helpful and i appreciate the contributors from heart. 
Thank you!

- **OS:** ubuntu14.04
- **PyQt version:** Qt4

**Comment by tzutalin** [comment]
Thanks for giving a heads up

**Comment by tzutalin** [comment]
Fix it https://github.com/tzutalin/labelImg/commit/6958e69851567abb18bfece52888d4709bbacc5b#diff-335ce07d50088fb26e24f96701ddfed4R436.
