### ISSUE TITLE
Fast move feature.

### ISSUE THREAD

**Issue by ck196** [tzutalin/labelImg#14]
Hi,
Your tool is awesome now. It is more useful than LabelMe (MIT-CSAIL format).
It will be better if there is a feature to move to an image fast. Such as I am in 1000.jpg, but I want to come back 500.jpg to edit. Or already created 500 images, computer is shutdown or close application, next time?
Now, it seems you must to click back or next 500 times.

**Comment by tzutalin** [comment]
Do you have idea or suggestions or example about how to move fast? Like add a search bar to jump quickly?

**Comment by lzx1413** [comment]
how about add a QComboBox to list the image names?

**Comment by ck196** [comment]
I think a progress bar or a list of images name is OK.

**Comment by tzutalin** [comment]
Fix it  f2712d4

**Comment by tzutalin** [comment]
Hi @ck196 @lzx1413 ,
  What do you think about this change?

**Comment by ck196** [comment]
@tzutalin it is awesome.

**Comment by lzx1413** [comment]
@tzutalin  good job
