### ISSUE TITLE
Background-Only images' annotation

### ISSUE THREAD

**Issue by VanitarNordic** [tzutalin/labelImg#146]
Hello,

in some datasets, we have background-only images. it means they have no object of interest. in this case we should pass these tags with black coordinates I believe:
```
<bndbox>
  <xmin></xmin>
  <ymin></ymin>
  <xmax></xmax>
  <ymax></ymax>
</bndbox>
```
Can you implement a checkbox in the form to tick if the image is only-background, then save an `xml` with this difference? 

or maybe the `<object>` tag should be removed totally. I think this is more correct.

**Comment by ChrisDal** [comment]
By  memory,  clicking on the `verify` button allows you to save the xml associated to the image without adding `<object>` tag :)

**Comment by vdalv** [comment]
I think this has been resolved, but please feel free to reopen if that's not the case.
