### ISSUE TITLE
  File "labelImg.py", line 27, in <module>     from resources import resources ImportError: cannot import name 'resources'

### ISSUE THREAD

**Issue by PriyankaOjha** [tzutalin/labelImg#150]
make qt5py3 
output : pyrcc5 -o resources.py resources.qrc
and with command: python3 labelImg.py 
output results in error: File "labelImg.py", line 27, in <module> from resources import resources ImportError: cannot import name 'resources'
on Anaconda, python3.6

- **OS:**mac
- **PyQt version:**5

**Comment by fengjunCN** [comment]
seems the some kind of problem with me.
