### ISSUE TITLE
Labeling round objects

### ISSUE THREAD

**Issue by szymonk92** [tzutalin/labelImg#153]
Hi,
Marking round objects is quite hard. After creating an label I always have to correct it.

Idea for enhancement is simple. Before creating the bounding box, vertical and horizontal line across the image will be displayed. After creating the starting point the lines will disappear. It will speed up labeling! See example below:
![untitled](https://user-images.githubusercontent.com/4785319/29803898-d9356282-8cb9-11e7-8999-d7709bd220d2.png)

**Comment by tzutalin** [comment]
@szymonk92 
 Thanks to @jaewchoi , he has implemented it.

**Comment by szymonk92** [comment]
Great! Thanks for implementing the feature.
