### ISSUE TITLE
mac osx , overwrites .xml files.

### ISSUE THREAD

**Issue by neurotensin** [tzutalin/labelImg#154]
I cannot seem to reopen an annotated image. The image reopens, and if I verify it simply overwrites the XML file.    I would like to request that images and have user specified annotation files, and that renaming not overwriting is the default. 

- **OS:** Mac OsX , 10.12.6
- **PyQt version:** 4.12._1

**Comment by tzutalin** [comment]
Have you tried to save the annotation to a specific folder?

**Comment by neurotensin** [comment]
Hi,

Yes, but it did, but the filename is not shown until afterwards. I quick check would be nice to make sure we only update and not overwrite files.

Nice app ;-)

**Comment by vdalv** [comment]
Please let us know if you continue to experience this issue w/ the latest code.
