### ISSUE TITLE
There is no resources.py program

### ISSUE THREAD

**Issue by ASH1998** [tzutalin/labelImg#155]
How do you expect to run this in windows!! Pls Fix this
- **OS:** Windows
- **PyQt version:** 4

**Comment by VShawn** [comment]
try run
`pyrcc4 -o resources.py resources.qrc`

It worked will on my computer,Win10&Py3.6.2&Qt5,  i modify code and build it my owm tool

**Comment by ASH1998** [comment]
The last commit has no resources.py how can you run it!!! check the repo
and also i used the binary...it was easier than to compile the code

**Comment by tzutalin** [comment]
Hi @ASH1998 ,
  resources.py is generated by executing makefile. 

Python 2 + Qt4
`make qt4py2`

Python 3 + Qt5
`make qt5py3`
