### ISSUE TITLE
Portrait Image Issues being treated as Landscape ones

### ISSUE THREAD

**Issue by Kiathui** [tzutalin/labelImg#159]
All my portrait images loaded into labelimg is flipped horizontal and i have no ways of rotating it in the program. Coordinates appear weird because of this.

![image](https://user-images.githubusercontent.com/19143921/30250399-2a1d7192-9680-11e7-8d02-d660039d7729.png)

**Comment by iraadit** [comment]
I have exactly the same problem

**Comment by ryouchinsa** [comment]
RectLabel is an offline image annotation tool for object detection and segmentation.
Although this is not an open source program, with RectLabel you can remove the EXIF orientation flags from images and convert images to the front orientation. If necessary, you can rotate the image right/left by 90 degrees.
https://rectlabel.com/help#remove_exif_orientation_flags
