### ISSUE TITLE
Toolbar containing "Next Image", "Open Dir" etc. has disappeared.

### ISSUE THREAD

**Issue by kylehounslow** [tzutalin/labelImg#16]
Hello,  
The toolbar has disappeared, see below image:
![image](https://cloud.githubusercontent.com/assets/7102778/18451770/2954979c-78ed-11e6-9eee-4db85cdae955.png)

Thanks in advance for your help.
K

**Comment by tzutalin** [comment]
Hi @kylehounslow,
  Move your cursor to Box Labels and click the right button using your mouse, then enable 'Tools' option.
