### ISSUE TITLE
size is 0 in xml annotations.

### ISSUE THREAD

**Issue by makefile** [tzutalin/labelImg#160]
- **OS:** Windows 7
- **PyQt version:**5

for some images ,the xml annotations file created by using labelImg has problems that: the width and height in size node is 0.
My guess is that the image is maybe not a jpg format file.

**Comment by IcyFrequency** [comment]
@makefile 
I get the same problem and haven't solved it. 
- MacOS Sierra
- python 3.5
- PyQt 5
