### ISSUE TITLE
Help needed ! Pyrcc4 command not found.

### ISSUE THREAD

**Issue by neospeed83** [tzutalin/labelImg#163]
Hi,
I am trying to set up LabelImg for my Windows 10 x64 PC with (CPU only no GPU)
But I am quite confused.
I downloaded LabelImg, PyQt 4 and Lxml for windows and after that, I was going with the flow mentioned on respective pages. Afterwards when I tried to run the
LabelImg using pyrcc4 command it says command not found.
Now I have zero Idea what went wrong :(
Total newbie here.
Attached SS for reference.
![pycc4 error](https://user-images.githubusercontent.com/17794737/30796880-8591a760-a1f1-11e7-980c-179c0aac478b.png)

- **OS:** Windows 10 x64
- **PyQt version:** 4

**Comment by tzutalin** [comment]
Hi @neospeed83 ,
  Your terminal is unable to recognize pyrcc4. You didn't setup pyrcc4 correctly.

**Comment by neospeed83** [comment]
what is pyrcc4 ? can you please elaborate ?

**Comment by tzutalin** [comment]
Simply speaking, pyrcc4 is a command line tool to convert the resource file to python files
You need to install python & pyQt4, then let your environment can execute `pyrcc4` by setting the environment path on your windows.

**Comment by tikhonovpavel** [comment]
If you use python3.6 it's:
c:\Python\Python36\Lib\site-packages\PyQt4

**Comment by tikhonovpavel** [comment]
If you use python3.6 it's:
c:\Python\Python36\Lib\site-packages\PyQt4
