### ISSUE TITLE
LabelImg Installation issue

### ISSUE THREAD

**Issue by EldorIbragimov** [tzutalin/labelImg#165]
In the labelImg installation. I get this error. What should I do?
cd
![screenshot from 2017-09-27 10-25-31](https://user-images.githubusercontent.com/26270045/30891432-4b5998e0-a36e-11e7-951f-951c77a9cc2a.png)

**Comment by tzutalin** [comment]
sudo apt-get install pyqt4-dev-tools
sudo pip install lxml

**Comment by mldm4** [comment]
Hello. Thanks for the tool.
It does not work for me either and I have done what @tzutalin suggested.
