### ISSUE TITLE
I implemented Rotation functions, how to create binary files?

### ISSUE THREAD

**Issue by wangzhe0623** [tzutalin/labelImg#168]
Hi, @tzutalin 
      I added rotating rectangle in labelImg, and I run the python code with PyCharm, everything is OK. So, what I should do to build source to binary file? I need executable file in Windows. Just follow the README in "build-tools" folder? Should I do all the operations in Ubuntu?

Thx~~~

**Comment by tzutalin** [comment]
Hi @wangzhe0623 ,
    How about sending a pull request ? The feature might be useful to other people.
All of my operations to build windows's exe is running in Ubuntu.

**Comment by wangzhe0623** [comment]
@tzutalin Thx, But I am not familiar with 'docker', when I run 'build-for-pypi.sh' in ubuntu, I got ‘no rule to make 'py2qt4', no rule to make 'test'’. What should I do to solve this problem before build python source? I never build python source code to '.exe', I feel so confused.

**Comment by wangzhe0623** [comment]
I installed 'docker' before running the script, and I also got 'FATA[0000]' error. Thx so much~

**Comment by wangzhe0623** [comment]
And, I used PyQt5 and Python3, I can't use script in 'build-tools' to create '.exe' directly, OMG, version problem is so terrible````````````

**Comment by wangzhe0623** [comment]
I changed 'tzutalin/py2qt5' to 'tzutalin/py3qt5' in 'build-for-pypi.sh', is that ok? Is 'tzutalin/py3qt5' offerd?

**Comment by wangzhe0623** [comment]
I changed 'tzutalin/py2qt4' to 'tzutalin/py3qt5' in 'build-for-pypi.sh', is that ok? Is 'tzutalin/py3qt5' offerd?

**Comment by wangzhe0623** [comment]
I make it with pyinstaller, Thx again~

**Comment by smajida** [comment]
@wangzhe0623 that would be great if you could pull or share the rotated bounding box feature which others could also use?

**Comment by vdalv** [comment]
Closed due to inactivity. @wangzhe0623 Please feel free to reopen.

Thanks,

-Vlad
