### ISSUE TITLE
RFE: move bounding box "corners" with arrow keys for pixel perfect alignment

### ISSUE THREAD

**Issue by lorenzob** [tzutalin/labelImg#171]
Hi, this is what I'd like to be able to do:

1. place the mouse pointer over a corner until the corner is highlighted (square marker) and leave it there
2. now use the WSAD keys (or the arrow keys) to move the corner by a single pixel

Right now it is quite hard to do pixel perfect alignments, especially on small images: you fix one side and you move another one, quite frustrating. Darktable image editor works like this and it is great for fine tuning tone curves and the like.

**Comment by vdalv** [comment]
Closing this, because there's already an open issue for this enhancement (https://github.com/tzutalin/labelImg/issues/186).

Thanks,

-Vlad
