### ISSUE TITLE
Not recognizing valid image files

### ISSUE THREAD

**Issue by Elizabethcase** [tzutalin/labelImg#176]
Hi,

I was using label img successfully until I recently pulled down updates (it had been a while). Now it can't open an image directories, and I get the error:

"Make sure /Users/elizabeth/Pictures/GoPro/2017-07-31/HERO5 Black 1/Time Lapse 1/G0016365.JPG is a valid image file."

Tried removing and reinstalling everything.

Help?

- **OS: macOS SIerra 
- **PyQt version: 4.8.7

**Comment by tzutalin** [comment]
Hi @Elizabethcase ,
  I am not sure about the root cause. Could you help me to do a test?  
Move that image to another folder without space or special characters, then try to open the image again.
If solved, the problem might be about decoding the image path in the wrong format.

**Comment by Elizabethcase** [comment]
Hi @tzutalin, 

Ah sorry, yes. I've tried with different images/file formats/locations. Unfortunately I'm getting the same error for all of them. I can't open any image directly and it throws the same error for every directory.

Anything else I might be able to try?

**Comment by tzutalin** [comment]
Hi @Elizabethcase ,
  That's wired. So far, I cannot know the cause. Add a log to the below line is the alternative way to get more insights:
https://github.com/tzutalin/labelImg/blob/f4d87a9951b067d5719f5ffaeed211b5329d502b/labelImg.py#L901
https://github.com/tzutalin/labelImg/blob/f4d87a9951b067d5719f5ffaeed211b5329d502b/labelImg.py#L907

**Comment by Elizabethcase** [comment]
How do you add a log?

**Comment by tzutalin** [comment]
@Elizabethcase ,
   You can add a log by using print() or log library. Using print() is easier.

In the meantime, you can try to download and reinstall again to see if the issue will happen or not.

**Comment by tzutalin** [comment]
@Elizabethcase ,
  Do you resolve it?

**Comment by bobhaffner** [comment]
Hi @tzutalin thanks for building this awesome tool.  I'm getting the same error as @Elizabethcase 

OSX Sierra 
Python 2.7 and pyqt 4.11.4

![image](https://user-images.githubusercontent.com/8531623/31722631-3718a248-b3e2-11e7-9d4d-dae0db7e7970.png)

I looked at the lines you provided above.  Not sure why the error description doesn't show in the error dialog box like it's implied in the code block below.  

```
except LabelFileError as e:
                    self.errorMessage(u'Error opening file',
                                      (u"<p><b>%s</b></p>"
                                       u"<p>Make sure <i>%s</i> is a valid label file.")
                                      % (e, unicodeFilePath))

```

**Comment by Elizabethcase** [comment]
@bobhaffner just below that is the corresponding error

Not sure if you're doing this in a conda environment but for whatever reason (that I can't figure out), I got labelimg working with pyqt5 and python 3 only *outside* the environment. Previously, I always ran it within an environment. Thinking it must be a path thing because some searching shows that  qt4 was bugging out with jpgs for a while, but I'm not fluent enough to suss out the exact solution.

**Comment by Elizabethcase** [comment]
@tzutalin I did, but I honestly don't know why doing it inside vs. outside a conda environment with all the required packages installed made a difference.

Thanks for your help & responsiveness!

**Comment by bobhaffner** [comment]
Hi @Elizabethcase I don't think I follow you on the error thing.  I'm thinking it should appear on the line that's currently blank between `Error opening file` and `Make sure...`

I am using a conda env.  That's interesting.  Come to think of it, I did read a [blog post](https://medium.com/towards-data-science/how-to-train-your-own-object-detector-with-tensorflows-object-detector-api-bec72ecfe1d9) that mentioned the same thing about jpegs

**Comment by xinario** [comment]
I came across the same problem within conda environment.
I'm using OSX Sierra Python 2.7 and pyqt4. After some search, I found this [thread](https://github.com/ContinuumIO/anaconda-issues/issues/131). Basically, the problem lies in pyqt4 and they are not going to add support to jpeg. 

So my solution is just switching to python 3 with pyqt5. Hope it helps.

**Comment by bobhaffner** [comment]
> So my solution is just switching to python 3 with pyqt5. Hope it helps.

Same here @xinario.  I was able to install everything thru conda

**Comment by vdalv** [comment]
Looks like this issue has been resolved. If not, please feel free to reopen.

Thanks,

-Vlad

**Comment by Stern-Hayat** [comment]
Hello,  I'm getting the same error as @bobhaffner and @Elizabethcase now.
In case of me, labelImg doesn't work well even if I switch versions to python3 and pyqt5.

・Mac OS
・Python 3.7.3
・pyqt5

How can I solve the error ?

**Comment by bobhaffner** [comment]
@Stern-Hayat Here are my versions if that helps

python                   3.4.5  
pyqt5                     5.4.1

**Comment by Abubakar26** [comment]
I am also facing the same issue my 
python version: 3.9.4
PyQt: 5.9.2
I tried to run it in both conda ENV and without condaenv but nothing happens 
Also, I faced a strange issue it is giving the img not valid error on the jpg format images but loading the PNG and JPEG format images can anyone help me in this matter

**Comment by PDahal2871** [comment]
Installing PyQT5 solved the problem for me

**Comment by pandyah5** [comment]
pip install --upgrade pyqt5 lxml --user

This solved the issue for me!

If that does not solve it too, then run the above command and then run this:

cd /d {LABELIMG_PATH} && pyrcc5 -o libs/resources.py resources.qrc

Use the path as per your pc.

**Comment by phutaekwondo** [comment]
change file's type to *png. I tried tried and solved in my case, because I had changed origin PNG file to JPG.

**Comment by kuangxiaoye** [comment]
conda install lxml 

that ok
