### ISSUE TITLE
Different colors for labels

### ISSUE THREAD

**Issue by vcasadei** [tzutalin/labelImg#177]
Hi, I would like to know if it's something simple to add a new line color for each new label created.

This would be a great feature for many people I believe (including me).

I tried to read the code and add such feature, but I had no success.

Does anyone know how could I do such thing?

**Comment by tzutalin** [comment]
Hi @vcasadei ,
  I have implemented today. I am not sure if it satisfies your request.
6cf04ad

**Comment by vcasadei** [comment]
Thank you!
