### ISSUE TITLE
Some images are reversed after loading

### ISSUE THREAD

**Issue by nerv3890** [tzutalin/labelImg#179]
Sometimes images are reversed after loading
Both Win10 and Ubuntu16.04+python2+QT4 happened 
Like this

**1. Image is normal** 
https://imgur.com/dzLaKk0

**2. Image is normal in the loading window too**
https://imgur.com/5dGeX8E

**3. Image is reversed after loading**
https://imgur.com/eJPCQE1

How to fix this problem?

Thanks for ur helping
Best wishes

**Comment by nerv3890** [comment]
I found the solution. thx~
#159

**Comment by thangvip4321** [comment]
hey @nerv3890 how did you fix it , im having the same problem here.

**Comment by nerv3890** [comment]
Hi:

U can see this website for the solution.
https://www.howtogeek.com/254830/why-your-photos-dont-always-appear-correctly-rotated/

U have to fix the EXIF data using the EXIF program which u can find on the
internet.

Just google "EXIF fix"

I hope the information can help u.



Kevin Lin

thangvip4321 <notifications@github.com> 於 2018年11月8日 週四 下午5:43寫道：

**Comment by thangvip4321** [comment]
Thank you very much sir.

Vào 17:17 T.5, 08 Th11 2018 nerv3890 <notifications@github.com đã viết:

**Comment by ryouchinsa** [comment]
RectLabel is an offline image annotation tool for object detection and segmentation.
Although this is not an open source program, with RectLabel you can remove the EXIF orientation flags from images and convert images to the front orientation. If necessary, you can rotate the image right/left by 90 degrees.
https://rectlabel.com/help#remove_exif_orientation_flags
