### ISSUE TITLE
Display label in bounding box

### ISSUE THREAD

**Issue by Jenzzz** [tzutalin/labelImg#182]
**Feature idea:**

Display label in the bounding box. Show the label in the bounding box so it is more clear which label corresponds to which bounding box.

**Comment by tzutalin** [comment]
@Jenzzz ,
  I use another way to connect label and bounding box. The color of the label in the list widget is the same as the bounding box. 
![pic](https://user-images.githubusercontent.com/3283822/32434468-261eacbc-c319-11e7-9877-531f1fd7f9a3.png)

**Comment by ngoanpv** [comment]
> @Jenzzz ,
> I use another way to connect label and bounding box. The color of the label in the list widget is the same as the bounding box.
> ![pic](https://user-images.githubusercontent.com/3283822/32434468-261eacbc-c319-11e7-9877-531f1fd7f9a3.png)

Hi @tzutalin,  How to do that, I don't see that feature in the latest version.

**Comment by santo4ul** [comment]
One problem that our annotators are facing is with typos. Labels are misspelled sometimes. So an option to display the laben on the left top corner of the rectbox would really help. 

Request you to please take this feature request. Thank you. 

Thanks,
San

**Comment by bernhardschaefer** [comment]
You can toggle display labels using View -> Display Labels
