### ISSUE TITLE
Installation in macOS Sierra:*** No rule to make target `qt4py2'.  Stop.

### ISSUE THREAD

**Issue by zhihongzeng2002** [tzutalin/labelImg#185]
laptop: MacBook Pro 2015, MacOS Sierra.

Installation: 
brew install qt: success
brew install qt4: Error No formulae found in taps
brew install cartr/qt4: success
brew install libxml2: success
brew install pyqt: success
$ make qt4py2
make: *** No rule to make target `qt4py2'.  Stop.
$ python labelImg.py
python: can't open file 'labelImg.py': [Errno 2] No such file or directory

The current version:
qt 5.9.2 is already installed
libxml2 2.9.6 is already installed
pyqt 5.9_1 is already installed

Is there something missing?

**Comment by zhihongzeng2002** [comment]
I fixed this issue with the following solution:

1) git clone https://github.com/tzutalin/labelImg.git, and cd labelImg
2) brew install qt
3) brew install cartr/qt4
4) export PYTHONPATH=/usr/local/Cellar/libxml2/2.9.6/lib/python2.7/site-packages:/usr/local/Cellar/sip/4.19.3_4/lib/python2.7/site-packages/:/usr/local/Cellar/pyqt@4/4.12_1/lib/python2.7/site-packages:$PYTHONPATH
5) brew install libxml2
6) sudo easy_install pip
7) sudo pip install lxml (I install it because step 9 show "no module lxml")
8) make qt4py2
9) python labelImg.py

It works very well now.

**Comment by MatinC** [comment]
doesn't work for me, in high sierra

**Comment by zhihongzeng2002** [comment]
@MatinC 
Could you post the error messages so that we can figure out what is missing?
For qt4 installation, there are several components. You may try:
brew install cartr/qt4/qt@4
brew install cartr/qt4/qt-legacy-formula
brew install cartr/qt4/pyqt@4

**Comment by megha-17** [comment]
hi, I am facing following issue
$ python labelImg.py
Traceback (most recent call last):
  File "labelImg.py", line 27, in <module>
    import resources
  File "/Users/i303433/labelImg/resources.py", line 9, in <module>
    from PyQt4 import QtCore
ImportError: dlopen(/usr/local/Cellar/pyqt@4/4.12_1/lib/python2.7/site-packages/PyQt4/QtCore.so, 2): Symbol not found: _PyInt_Type
  Referenced from: /usr/local/Cellar/pyqt@4/4.12_1/lib/python2.7/site-packages/PyQt4/QtCore.so
  Expected in: flat namespace
 in /usr/local/Cellar/pyqt@4/4.12_1/lib/python2.7/site-packages/PyQt4/QtCore.so


Could you please help me with it

**Comment by zhihongzeng2002** [comment]
@megha-17 I think that you may create a new issue. Your problem is different from the current issue.

**Comment by megha-17** [comment]
@zhihongzeng2002 , Actually I am also trying to install labelImg on my mac osx and have followed solution provided by you to install but it is not working and facing following issue:-

$ python labelImg.py
Traceback (most recent call last):
File "labelImg.py", line 27, in 
import resources
File "/Users/i303433/labelImg/resources.py", line 9, in 
from PyQt4 import QtCore
ImportError: dlopen(/usr/local/Cellar/pyqt@4/4.12_1/lib/python2.7/site-packages/PyQt4/QtCore.so, 2): Symbol not found: _PyInt_Type
Referenced from: /usr/local/Cellar/pyqt@4/4.12_1/lib/python2.7/site-packages/PyQt4/QtCore.so
Expected in: flat namespace
in /usr/local/Cellar/pyqt@4/4.12_1/lib/python2.7/site-packages/PyQt4/QtCore.so

**Comment by SepidehAlassi** [comment]
@zhihongzeng2002 Hi, I followed the steps you mentioned, and have all 

brew install cartr/qt4/qt@4
brew install cartr/qt4/qt-legacy-formula
brew install cartr/qt4/pyqt@4

installed, nevertheless when I try make qt4py2, I get following error
make: *** No rule to make target `qt4py2'.  Stop.

any suggestion?

**Comment by RodolfoFerro** [comment]
Hey, this worked for me:

### Python 3 + Qt5 (Works on macOS High Sierra)

```bash
brew install qt  # will install qt-5.x.x
brew install libxml2
make qt5py3
python labelImg.py
python  labelImg.py [IMAGE_PATH] [PRE-DEFINED CLASS FILE]
```

**Comment by aysark** [comment]
Doesn't work for me on latest macOS.

#make qt4py2
pyrcc4 -py2 -o resources.py resources.qrc
#python labelImg.py
Segmentation fault: 11

**Comment by RodolfoFerro** [comment]
A possible thing happening is that you're not using Qt-5 with Python 3 or Qt-4 with Python 2.
What Python version are you using? Can you share your output from `qmake --version`? @aysark

**Comment by RodolfoFerro** [comment]
A better solution! 😃 👍

**Comment by ttungl** [comment]
Hope this help. https://github.com/tzutalin/labelImg/issues/202

**Comment by saikanam** [comment]
@aysark 
You, sir, just made my day. Thanks

**Comment by pallavtrivedi03** [comment]
@aysark You saved my day. Thanks a ton.

**Comment by vijaysan** [comment]
@aysark Most elegant solution, ever ;-)

**Comment by wxianfeng** [comment]
when compile, i meet this:
```
➜  labelImg git:(master) make qt5py3
pyrcc5 -o resources.py resources.qrc
make: pyrcc5: No such file or directory
```

@aysark thx, Man ~ 

this app is very Cool ~  it dont need compile .

**Comment by vdalv** [comment]
This issue appears to be resolved. @wxianfeng Please open a separate issue if necessary.

Thanks,

-Vlad

**Comment by abautistah** [comment]
I used a combo
already had python 3.x and python 2.x

1.- git clone https://github.com/tzutalin/labelImg.git
2.- cd labelImg
3.- brew install qt
4.- brew install cartr/qt4/qt@4
5.- brew install libxml2
6.- make qt5py3
7.- python3 labelImg.py (used python3 !!)
8.- python3  labelImg.py (i copied my image files to the same directory, so you would have to add the path here like in the previous responses)

**Comment by bubjanes** [comment]
@aysark has got the goods!

**Comment by svengateswaran** [comment]
`pip3 install pyqt5 lxml`

The above command seems to fix the following error:
`make: pyrcc5: No such file or directory`

Reference : [](https://pypi.org/project/labelImg/)

**Comment by enyangxxx** [comment]
same issue with pyrcc5: No such file or directory

**Comment by tzutalin** [comment]
missing pyrcc is because pyqt5 is not installed properly.

If you are using mac, try `$ pip install pyqt5 lxml`. Or else you can check out how I set up for build machine

https://github.com/tzutalin/labelImg/blob/master/.travis.yml#L78

**Comment by javadba** [comment]
pyqt5 is in place but pyrcc5 is missing anyways. Any thoughts?

**Comment by heguihua** [comment]
Summary

MacOS: QT5 + Python3
    pip3 install pyqt5 lxml
    make qt5py3
    python3 labelImg.py

Build an App: 
    python3 setup.py py2app -A
    sudo mv dist/labelImg.app /Applications/

**Comment by javadba** [comment]
As I mentioned "pyqt5 is in place".  

> $ python3 -c "from PyQt5.QtCore import *; import lxml"
> $
> 

```
$make qt5py3
pyrcc5 -o libs/resources.py resources.qrc
make: pyrcc5: No such file or directory
make: *** [qt5py3] Error 1

```

**Comment by cgironda** [comment]
It seems that this problem still persist. I solved my problem following the steps of @abautistah and the comment of @svengateswaran. I installed `lxml` with the command below in a macOS Catalina Version 10.15.7, but I was wondering how long this issue will remain in the future.

`conda install -c anaconda lxml`

**Comment by peoplecure** [comment]
Bootstrap was giving me problems. But, I made it through eventually. I closed and reopened the terminal window, and the problem magically disappeared so that I can deal with new problems. Made it through anyway.
