### ISSUE TITLE
Verify Image button has no icon 

### ISSUE THREAD

**Issue by Jenzzz** [tzutalin/labelImg#187]
"Verify Image" button has no icon in the windows binaries v1.5.2

**Comment by tzutalin** [comment]
It seems "Verify Image" never has an icon before. It should have.

**Comment by tzutalin** [comment]
Hi @Jenzzz,
  I added a new one. What do you think?
https://github.com/tzutalin/labelImg/commit/7c145ef6e9602b8ae756410ead2576ac4a8ed3b9

**Comment by Jenzzz** [comment]
Looks nice
