### ISSUE TITLE
QString' object has no attribute 'rfind'

### ISSUE THREAD

**Issue by zhoupan9109** [tzutalin/labelImg#189]
Ubuntu 16.04
python 2.7
qt4

when I load the image, the terminal show that "QString' object has no attribute 'rfind'.So ,I can't create the rectbox.

**Comment by tzutalin** [comment]
Hi @zhoupan9109 ,
  Try to delete ~/.labelImgSettings.pkl . It will hit the problem if you change your python or qt version.
