### ISSUE TITLE
Polygon tool for licence plate recognition?

### ISSUE THREAD

**Issue by mrgloom** [tzutalin/labelImg#190]
Is there any polygon like tool (labelImg is good,  but it only support axis aligned rectangles) for licence plate recognition - 4 points that represent perspective projection of rectangle.

Something like this:
https://gurus.pyimagesearch.com/wp-content/uploads/2015/03/anpr_localize_successful.jpg

**Comment by raviv** [comment]
+1 for polygon editing. 
I think it's an important feature for those of us training mask rcnns.
Thanks.

**Comment by vdalv** [comment]
This tool has what you're looking for: https://github.com/wkentaro/labelme

Cheers,

-Vlad
