### ISSUE TITLE
UnicodeDecodeError while installing on windows7

### ISSUE THREAD

**Issue by shravankumar147** [tzutalin/labelImg#193]
- **OS: windows 7
- **
 Qt version: 5.6.2
SIP version: 4.18
PyQt version: 5.6
`
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 5059: character maps to <undefined>`

**Comment by Fuchsiaff** [comment]
Hi, 
I have the same issue, how did you fix it?

**Comment by shravankumar147** [comment]
try commenting `long_description=readme + '\n\n' + history,` line in setup.py
