### ISSUE TITLE
Loading an annotation file does not work

### ISSUE THREAD

**Issue by laurikari** [tzutalin/labelImg#195]
Using latest version from git.  When I try to load an existing .xml file (previously saved using labelImg), the program crashes:

```
Traceback (most recent call last):
  File "labelImg.py", line 1179, in openFile
    self.loadFile(filename)
  File "labelImg.py", line 908, in loadFile
    self.lineColor = QColor(*self.labelFile.lineColor)
AttributeError: 'LabelFile' object has no attribute 'lineColor'
```

**Comment by tzutalin** [comment]
Hi @laurikari ,
  Try to delete ~/.labelImageSetting.pkl. Because the format of the setting file is changed, you need to delete the old one. Sorry for that.

**Comment by AllenShielder1994** [comment]
I have the same problem as above but i use win10 OS and i could not find any file call labelImageSetting.pkl

**Comment by youngsoul** [comment]
Same problem.  I am on MacOS just install a few days ago and tried to open a previously saved PascalVOC xml file.

I think this issue still exists.
