### ISSUE TITLE
Can you just use the prebuilt binary file for windows?

### ISSUE THREAD

**Issue by kannan60** [tzutalin/labelImg#197]
Hey!

For windows users: Can we just use the prebuilt binary version? It has an executable file for the program directly. Can we just use this to create the .xml files? Or, do we need to build it from source as explained further down below in your installation guide? I could not manage to get  PyQt4  working. I used this link to proceed(Francesco's reply):

https://stackoverflow.com/questions/32054021/how-to-install-sip-pyqt-on-windows-7/47144239#47144239

I am having trouble after executing this instruction: "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\vcvars32.bat"
nmake

The error is: cl : Command line error D8021 : invalid numeric argument '/FS'
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN\cl.EXE"' : return code '0x2'

- **Winodws 10:**
- **PyQt4_gpl_win-4.12.1:**

**Comment by tzutalin** [comment]
Hi @kannan60 ,
I have built the prebuilt version for windows as the below link. Do you meet any problem when using that?

```
https://tzutalin.github.io/labelImg/
```
