### ISSUE TITLE
how to run in windows

### ISSUE THREAD

**Issue by lightning0016** [tzutalin/labelImg#2]
can you give a example,thank you

**Comment by lightning0016** [comment]
i success run in windows,another problem,select dir is not work,is my question?

**Comment by tzutalin** [comment]
I didn't try yet. As far as I know, you can use cygwin.

**Comment by tzutalin** [comment]
@lightning0016 ,
 Could you share me with the steps how to run on Windows?

I would like to get a Windows laptop, and try 'select dir' issue

**Comment by tzutalin** [comment]
Hi @lightning0016 ,
  Could you share the steps with me?

**Comment by tzutalin** [comment]
Steps to run on windows
1. Download PyQt4 and Python 2.7
2. Open cmd and go to labelImg folder
3. pyrcc4 -o resources.py resources.qrc
4. python labelImg.py
5. Install the required modules like PIL, xlml, numpy, etc.

**Comment by tzutalin** [comment]
Hi @lightning0016,
 I setup the cross compile for windows. You can download exe file from  http://tzutalin.github.io/labelImg/
