### ISSUE TITLE
How to Load Image & XML folders AND have them load in parallel?

### ISSUE THREAD

**Issue by taewookim** [tzutalin/labelImg#200]
I have  a folder of images

images/1.jpg
images/2.jpg
images/3.jpg

And a folder of annotations

annotatations/1.xml
annotatations/2.xml
annotatations/3.xml

Is there a way to load labelImg with both folders so that I can just click next image and have labelImg automatically load the correct / proper XML files? I am trying to quickly verify the annotations.

**Comment by tzutalin** [comment]
Clicking 'Open Dir' will load all of the images.
Clicking 'Change Save Dir' will load all of the annotations.
