### ISSUE TITLE
Image dimensions are not captured in xml file after labeling 

### ISSUE THREAD

**Issue by aditya-karampudi** [tzutalin/labelImg#201]
Hi,
The tool is really good and easy to use. But after labeling, in XML file the dimensions of image is missing. The dimensions of the labeled image are being saved but the dimension of image is not being saved.
Please refer the screenshot.
I am labeling . 
![capture](https://user-images.githubusercontent.com/32515662/32836450-d22c5fb4-ca2f-11e7-90f0-49db79a43558.JPG)
jpg image

- **OS:** Windows 8
- **PyQt version:** 4.12

**Comment by tzutalin** [comment]
Does it happen for every image? Do you see any warning or errors in the terminal?

**Comment by aditya-karampudi** [comment]
Yes this issue happens for every image and I did not see any warnings in the terminal

**Comment by aditya-karampudi** [comment]
Hi,
I have reinstalled the whole software and now it is working fine. May be there was an issue while installing

Thanks for the awesome and easy to use app

![capture](https://user-images.githubusercontent.com/32515662/33002701-d367b3ec-cddb-11e7-825f-7f5fa5e1310c.JPG)
