### ISSUE TITLE
Segmentation fault:11

### ISSUE THREAD

**Issue by SwaggyK93** [tzutalin/labelImg#202]
- **OS:macOS10.13
- **PyQt version:4.12.1
I came across an issue when running "labelImg" on my terminal, said "Segmentation fault:11".Have someone come across the same problem?

**Comment by aysark** [comment]
Yes having same issue on latest macos.

**Comment by ttungl** [comment]
+ I disabled/removed line 123 ( `painter.drawText(min_x, min_y, self.label)` ) in `shape.py` file of the `lib` folder and it works for me. Here is the `xml` output file.

+ Another thing, before processing your image with `labeImg`, making sure it in the `png` format.

```
<annotation>
	<folder>jpg2png_resized</folder>
	<filename>4.jpg</filename>
	<path>/Users/your_path_to_file/4.jpg</path>
	<source>
		<database>Unknown</database>
	</source>
	<size>
		<width>500</width>
		<height>366</height>
		<depth>3</depth>
	</size>
	<segmented>0</segmented>
	<object>
		<name>iphone</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>0</difficult>
		<bndbox>
			<xmin>111</xmin>
			<ymin>167</ymin>
			<xmax>221</xmax>
			<ymax>302</ymax>
		</bndbox>
	</object>
</annotation>
```

**Comment by vdalv** [comment]
The Python3 + Qt5 approach works well w/ macOS High Sierra, so I recommend using that.
