### ISSUE TITLE
labelImg not working properly

### ISSUE THREAD

**Issue by harisudhan312** [tzutalin/labelImg#203]
Hi,

I'm using labelImg for the first time. I trying to use it with pyqt 4.11 and  sip 4.16 on anaconda. I have several issues:

1. If I'm using conda install pyqt=4.11 and installing pyqt, my sip gets upgraded to 4.18, then i use

pyrcc4 -o resources.py resources.qrc which works perfectly, but when i use python labelImg.py to start the application, I'm getting, 

 File "labelImg.py", line 24, in <module>
    from PyQt4.QtGui import *
RuntimeError: the sip module implements API v11.0 to v11.2 but the PyQt4.QtGui module requires API v11.3

2. On the other hand, if I'm using conda install sip=4.16 to downgrade the sip which is compatible with pyqt 4.11 and run pyrcc4 -o resources.py resources.qrc, i get

'"C:\Miniconda2\Scripts\\..\Lib\site-packages\PyQt4\pyrcc4"' is not recognized as an internal or external command,
operable program or batch file.

What is the real issue here? Seems like a lot of people had similar issue. But there isn't really any concrete solution

3. If I use labelImg directly without using pyrcc4 -o resources.py resources.qrc, it opens the labelImg, i can label my image, but i can't save it as jpeg/jpg image rather i only have xml file format.

**Comment by tzutalin** [comment]
Hi @harisudhan312 ,
  If you are using window, why do not you use the [prebuilt binary](https://tzutalin.github.io/labelImg/)?

**Comment by harisudhan312** [comment]
Hi,

Thanks for your prompt reply. I used it. Still I can't saved the cropped image as a jpg file but only as xml file. Could you please explain why and how to solve this issue
