### ISSUE TITLE
How to define <pose> & <truncated>?

### ISSUE THREAD

**Issue by ssls18years** [tzutalin/labelImg#206]
pose &  truncated are needed for yolo, but i can't find how to define them in labelimg.

anyidea or any other tools? thx.

**Comment by ChrisDal** [comment]
`truncated` is true if object is at the limits of the image [Code in [libs/pascal_voc_io.py](https://github.com/tzutalin/labelImg/blob/master/libs/pascal_voc_io.py)]

```
truncated = SubElement(object_item, 'truncated')
if int(each_object['ymax']) == int(self.imgSize[0]) or (int(each_object['ymin'])== 1):
    truncated.text = "1" # max == height or min
elif (int(each_object['xmax'])==int(self.imgSize[1])) or (int(each_object['xmin'])== 1):
    truncated.text = "1" # max == width or min
else:
    truncated.text = "0" 
```

A `truncated` button might be defined the same way as the `difficult` button.
