### ISSUE TITLE
No module named lxml

### ISSUE THREAD

**Issue by jry2016** [tzutalin/labelImg#21]
Running OSX 10.11, python 2.7, for some reason my environment is missing lxml.

$  python labelImg.py
Traceback (most recent call last):
  File "labelImg.py", line 23, in <module>
    from labelFile import LabelFile, LabelFileError
  File "libs/labelFile.py", line 6, in <module>
    from pascal_voc_io import PascalVocWriter
  File "libs/pascal_voc_io.py", line 5, in <module>
    from lxml import etree
ImportError: No module named lxml

Any ideas on how to fix this?

**Comment by alfiya400** [comment]
You need to install `lxml`. This one worked for me: 
```bash
# http://geekforbrains.com/post/how-to-install-lxml-for-python-using-homebrew-and-pip-in-3-steps
brew install libxml2
pip install lxml
```
