### ISSUE TITLE
Cant load saved xml annotations.

### ISSUE THREAD

**Issue by julled** [tzutalin/labelImg#210]
Running on ubuntu 16.04.
Tried to delete ~/.labelImageSetting.pkl like in  #195  suggestted, but didnt help.
I am running into:
> Traceback (most recent call last):
  File "labelImg.py", line 1181, in openFile
    self.loadFile(filename)
  File "labelImg.py", line 910, in loadFile
    self.lineColor = QColor(*self.labelFile.lineColor)
AttributeError: 'LabelFile' object has no attribute 'lineColor'

**Comment by tzutalin** [comment]
Hi,
 Try to remove ~/.labelImgSettings.pkl. It is caused by using different python versions
