### ISSUE TITLE
Cannot install on macOS High Sierra if I use qt4 and make qt4py2

### ISSUE THREAD

**Issue by IAvor** [tzutalin/labelImg#211]
Hello guys.Just to let you know that the installation for macOS is not working as described.
1.The qt4 is missing...I get this error in brew: Error: No available formula with the name "qt4" 
2.Since qt4 is missing and cannot be installe via homebrew - this is not working also "make qt4py2".

To get it working on macOS I had to install qt5 and instead of using "make qt4py2" I have used "make qt5py3" and this solved the issue.Please change the this in the description for the installation,because I am pretty sure that there will be people banging their heads right now...
Thanks.
Kind Regards,
IAvor Kolev

**Comment by campdav** [comment]
Thanks ! **Qt5** installation is working instead of **QT4**, on **macOS High Sierra**.
In the main time, modification on the script **/libs/ustr.py** seams to be mandatory in this case, as **QT5** does not have **QTString** (it returns directly a python string).
kind regards

**Comment by titanbender** [comment]
I still get the error on High Sierra: 
make: *** No rule to make target `qt5py3'.  Stop.

After cloning the repo from git and cd into it, it's possible to run the 'make qt5py3'. However, then I get the error: No module named 'lxml' when I run python labelImg.py or python3 labelImg.py... 

Did anyone experience the same? I do have lxml installed :-(...

**Comment by RodolfoFerro** [comment]
Hey @IAvor, @titanbender, this worked for me:

### Python 3 + Qt5 (Works on macOS High Sierra)

```bash
brew install qt  # will install qt-5.x.x
brew install libxml2
make qt5py3
python labelImg.py
python  labelImg.py [IMAGE_PATH] [PRE-DEFINED CLASS FILE]
```

**Comment by titanbender** [comment]
Thanks for the note @RodolfoFerro! 
I'm not sure why, but I still get the same error message: 
"make: *** No rule to make target `qt5py3'.  Stop." 
This happens for the command: "make qt5py3"...

**Comment by RodolfoFerro** [comment]
Looks like it is a dependencies problem.
Are you using brew to manage the dependencies @titanbender?

To install qt5 with brew:
`brew install qt5`

You can also try to reinstall libxml2. The following link might be useful for that:
https://stackoverflow.com/questions/11054972/homebrew-install-libxml2-with-python-modules

**Comment by titanbender** [comment]
Thanks @RodolfoFerro - it worked out perfectly after lxml was installed directly.

**Comment by RodolfoFerro** [comment]
Nice!
How did you install lxml?

**Comment by tleyden** [comment]
This worked for me:

```
$ virtualenv -p python3 labelimg
$ source labelimg/bin/activate
(labelimg) $ pip install PyQt5
(labelimg) $ pip install lxml
(labelimg) $ python labelImg.py
```

**Comment by vdalv** [comment]
This issue appears to have been resolved.

**Comment by zjmvwb** [comment]
Thanks @tleyden , I have tried many ways, only your method works.

**Comment by SidMalladi** [comment]
@tleyden You're a life saver, thank you!
