### ISSUE TITLE
the 'file list' window disappears

### ISSUE THREAD

**Issue by IvyGongoogle** [tzutalin/labelImg#213]
hello, I modify your code to add a small function. But now I find the `file list` window disappears that let me crazy. my code is [here](https://github.com/IvyGongoogle/labelImg). can you give some advises?
thank you very much~
looking forward to your reply.

**Comment by IvyGongoogle** [comment]
@tzutalin can you give some advises?

**Comment by tzutalin** [comment]
Hi @IvyGongoogle ,

Sorry about that. There is a workaround for that, you can try to click File/ResetAll. 

I also submitted a change that 'file list' won't be hidden anymore. https://github.com/tzutalin/labelImg/commit/3391ab632ec20c9038b10dfb03c536ac58128465

**Comment by IvyGongoogle** [comment]
@tzutalin it works, thanks a million
