### ISSUE TITLE
pyrcc4 is not recoznised 

### ISSUE THREAD

**Issue by MotiBaadror** [tzutalin/labelImg#219]
pyt4 
win 10  64bit 
I have cloned this repo and when I go to directory and type 
pyrcc4 -o resources.py resources.qrc
then it gives error pyrcc4 is not recognized

**Comment by lYlantis** [comment]
You have to add the location of pyrcc4 to your system path. Ex path for me is C:\Python36\Lib\site-packages\PyQt4

https://github.com/tzutalin/labelImg/issues/121

**Comment by vdalv** [comment]
I believe this issue has been resolved. If not, please feel free to reopen it.

Thanks,

-Vlad
