### ISSUE TITLE
can't save  xml  in ubuntu16.04 

### ISSUE THREAD

**Issue by jiangjie666** [tzutalin/labelImg#22]
when I have finished  annotation the image that I can't save  xml  files in ubuntu16.04 .when I tick the button to save the xml file to my folder .I can find nothing in my computer .

**Comment by tzutalin** [comment]
Hi @jiangjie666 , 
  I will spare some time to try this issue. Have you specified the save dir?

**Comment by jiangjie666** [comment]
Thanks .Your help will be greatly appreciated

**Comment by tzutalin** [comment]
Hi @jiangjie666 ,
 I always ubuntu to develop and use the tool. I have tried my ubuntu16.04 and ubuntu14.04, and it can work on both of operating systems.

Could you add some logs in pascal_voc_io.py ? Maybe it will be helpful to understand the problems.

**Comment by jiangjie666** [comment]
HI @tzutalin 
I have find the problem .thank you .

**Comment by tzutalin** [comment]
Nice. Can you share me with the cause?

**Comment by tzutalin** [comment]
Nice. Can you share me with the cause?

**Comment by LeeRock** [comment]
hi，@tzutalin ，i guess his   path contains unicode ,for example chinese character like /home/xx/图片/，maybe the same problem like Can't save unicode labels  #24

**Comment by LeeRock** [comment]
the same problem came for me ,i solved it by moving your code project and my pictures to a English only path~ @tzutalin

**Comment by tzutalin** [comment]
@LeeRock ,
  Thanks a lot. I will spare some time to reproduce and fix this issue this week. It's a minor issue about ascii and unicode.

**Comment by tzutalin** [comment]
@LeeRock ,
  I try to save and load XML with unicode. If you have free time, please help to check it again?
https://github.com/tzutalin/labelImg/commit/50a079edc40555f6dfecad64103a99ba615975be

I also created a folder called tests which we can upload more images with different kinds of images or name to do unit tests or reproduce the issues in the future.

**Comment by JasonLiu-TJU** [comment]
Hi, I am using Ubuntu 16.04, python 2.7. The YOLO format annotation is successfully saved on the hard disc, but the size of xml is 0 when saving a Pascal annotation. I think it's a similar problem with this issue. 
P.S. The path doesn't include any other characters besides English.
Can you help me solve this problem? Thanks a lot.
