### ISSUE TITLE
Bounding box positions change after saving (on Windows ,v1.5.3)

### ISSUE THREAD

**Issue by true-source** [tzutalin/labelImg#220]
On reopening the labelled images, the coordinates of bounding box changed. The bounded parts of the image are not bound, but the bound label changes on its own.

- **Windows 10**
- **PyQt 4:**

**Comment by tzutalin** [comment]
Can you try the latest version?

**Comment by vdalv** [comment]
I experienced this with one of the previous versions. It's fixed now, so I recommend running the latest code/build.

**Comment by true-source** [comment]
Seems to be working well, thanks!

**Comment by Anothorld** [comment]
I'm using v1.8.3 and got the same problem as you, what version are you using right now?

**Comment by cjpurackal** [comment]
@Anothorld  Sorry , I'm no longer using this software.
