### ISSUE TITLE
labelImg 1.5.2 on windows crashed 

### ISSUE THREAD

**Issue by pongrut** [tzutalin/labelImg#221]
- **OS:** windows 10
- **PyQt version:**

I have used labelImg 1.5.2 on windows for many days.
Today I was opening an image then I try to change its .xml with notepad to see the result.
After I closed program then I cannot open program again it keep throw this error even I have tried to reboot my computer many times.

Traceback (most recent call last):
  File "<string>", line 1344, in <module>
  File "<string>", line 1340, in main
  File "<string>", line 1333, in get_main_app
  File "<string>", line 93, in __init__
  File "Z:\home\darrenl\tmp\labelImg\build-tools\build\labelImg\out00-PYZ.pyz\libs.settings", line 33, in load
  File "Z:\home\darrenl\tmp\labelImg\build-tools\build\labelImg\out00-PYZ.pyz\pickle", line 1378, in load
  File "Z:\home\darrenl\tmp\labelImg\build-tools\build\labelImg\out00-PYZ.pyz\pickle", line 858, in load
  File "Z:\home\darrenl\tmp\labelImg\build-tools\build\labelImg\out00-PYZ.pyz\pickle", line 880, in load_eof
EOFError

Any suggestion please?

**Comment by nikitaverbis** [comment]
Add any example of your xml-file and image if possible.

**Comment by pongrut** [comment]
Here it is. However, I can open the program on another computer but the main one I cannot open it anymore.
<?xml version="1.0"?>

-<annotation>

<folder>object-detection-macaroni_images</folder>

<filename>0ShAyPFRqBeO60QkYN7w_Mac Cheese 2.jpg</filename>

<path>F:/OneDrive/Machine_Lerning/Nano Degree/capstone/object-detection-macaroni_images/0ShAyPFRqBeO60QkYN7w_Mac Cheese 2.jpg</path>


-<source>

<database>Unknown</database>

</source>


-<size>

<width>620</width>

<height>414</height>

<depth>3</depth>

</size>

<segmented>0</segmented>


-<object>

<name>macncheese</name>

<pose>Unspecified</pose>

<truncated>0</truncated>

<difficult>0</difficult>


-<bndbox>

<xmin>0</xmin>

<ymin>9</ymin>

<xmax>565</xmax>

<ymax>313</ymax>

</bndbox>

</object>

</annotation>

**Comment by a9595776** [comment]
I have this error. I don't know to solve it....

**Comment by IvyGongoogle** [comment]
I have the same error

**Comment by hiroalchem** [comment]
I have the same error too.....

**Comment by IvyGongoogle** [comment]
＠tzutalin　can you give some advises?  looking forward to your reply

**Comment by Mingta** [comment]
I have the same error.

**Comment by seovchinnikov** [comment]
+1

**Comment by zuifengwuchou** [comment]
Just delete the file ```.labelImgSettings.pkl``` which is locate at ```C:\\Users\your_account\```. Then reopen LabelImg.exe will be fine.

**Comment by pongrut** [comment]
thank  @zuifengwuchou the solution works for me.
"Just delete the file .labelImgSettings.pkl which is locate at C:\\Users\your_account\. Then reopen LabelImg.exe will be fine."

**Comment by IvyGongoogle** [comment]
@zuifengwuchou thanks a million

**Comment by FMsunyh** [comment]
thank @zuifengwuchou the solution works for me.
thanks,
thanks,
thanks,
thanks,
thanks,

**Comment by Akashpanchal95** [comment]
thanks, @zuifengwuchou its work for me.

**Comment by senisna** [comment]
this my sounds stupid but it worked for me
open the kabelImg.exe directly from winrar 
just don't extract it and it will open smothly

**Comment by ankni1** [comment]
my version of labelImg does not run. it crashes as soon as i try to import an image from a directory.
there is no file called .labelImgSettings.pkl. can someone help? the installations are as per @tzutalin 's instructions.

**Comment by zhaoxuyan** [comment]
### For Windows
Go to `Users\xxx\` delete `.labelImgSettings.pkl`,then `pyrcc5 -o libs/resources.py resources.qrc`, `python labelImg.py`
### For Mac or Linux
Go to home(~) folder, `rm .labelImgSettings.pkl`, then `pyrcc5 -o libs/resources.py resources.qrc`, `python labelImg.py`

**Comment by cheng-zi-ya** [comment]
But for windows, what can I do to solve the problem if I cannot find the .labelImgSettings.pkl?

**Comment by Akashpanchal95** [comment]
> But for windows, what can I do to solve the problem if I cannot find the .labelImgSettings.pkl?

You can find under the C:\Users\your_account\.labelImgSettings.pkl, Delete this file and open again the tool.

**Comment by cheng-zi-ya** [comment]
Thanks! I search all my files still cannot find it, but I find this is helpful: https://medium.com/@sanghuynh_73086/how-to-install-labelimg-in-windows-with-anaconda-c659b27f0f. Someone who has the problem like me maybe can try this.

**Comment by mrwicky381** [comment]
thankyou @zuifengwuchou , its work

**Comment by SB2020-eye** [comment]
> Just delete the file `.labelImgSettings.pkl` which is locate at `C:\\Users\your_account\`. Then reopen LabelImg.exe will be fine.

Such a simple solution. Thanks! I wish I were smart enough to correct it here with a pull request on github.

**Comment by Anuradha-Uggi** [comment]
I have done labelling for 280 images around,all corresponding .txt files were generated,but after sometime I have opened classes.txt where mostly of the classes were missing and when I opened the directory back in labelImg tool,when I press next image few images it shows and immediately gets crashed saying python has stopped working.plz kindly help me out of it.lots of efforts I kept in preparing it.i use it in windows 10.

**Comment by 3b0000d** [comment]
@zuifengwuchou Thank you very much.

**Comment by DilinaHirantha** [comment]
> thank @zuifengwuchou the solution works for me.
> "Just delete the file .labelImgSettings.pkl which is locate at C:\Users\your_account. Then reopen LabelImg.exe will be fine."

thanks bro it worked

**Comment by mohsin-riad** [comment]
> Just delete the file `.labelImgSettings.pkl` which is locate at `C:\\Users\your_account\`. Then reopen LabelImg.exe will be fine.

Thanks A Lot 💯

**Comment by prankshtain** [comment]
Worked for me tooooo!
@zuifengwuchou

**Comment by Jojodike** [comment]
> I have done labelling for 280 images around,all corresponding .txt files were generated,but after sometime I have opened classes.txt where mostly of the classes were missing and when I opened the directory back in labelImg tool,when I press next image few images it shows and immediately gets crashed saying python has stopped working.plz kindly help me out of it.lots of efforts I kept in preparing it.i use it in windows 10.

I'm having this same problem too. Please were you able to find a solution for it?

**Comment by Jojodike** [comment]
> my version of labelImg does not run. it crashes as soon as i try to import an image from a directory.
> there is no file called .labelImgSettings.pkl. can someone help? the installations are as per @tzutalin 's instructions.

I'm also having this issue too. Please were you able to find a solution for it?

**Comment by ITSAIDI** [comment]
C:\Users\hp>cd C:\Users\hp\AI\DL formation\Projects\Object recognition.CV\Sign launguage detection\RealTimeObjectDetection\Tensorflow\labelImg

C:\Users\hp\AI\DL formation\Projects\Object recognition.CV\Sign launguage detection\RealTimeObjectDetection\Tensorflow\labelImg>python labelImg.py
Traceback (most recent call last):
  File "C:\Users\hp\AI\DL formation\Projects\Object recognition.CV\Sign launguage detection\RealTimeObjectDetection\Tensorflow\labelImg\labelImg.py", line 1359, in open_dir_dialog
    self.import_dir_images(target_dir_path)
  File "C:\Users\hp\AI\DL formation\Projects\Object recognition.CV\Sign launguage detection\RealTimeObjectDetection\Tensorflow\labelImg\labelImg.py", line 1374, in import_dir_images
    self.open_next_image()
  File "C:\Users\hp\AI\DL formation\Projects\Object recognition.CV\Sign launguage detection\RealTimeObjectDetection\Tensorflow\labelImg\labelImg.py", line 1429, in open_next_image
    self.change_save_dir_dialog()
  File "C:\Users\hp\AI\DL formation\Projects\Object recognition.CV\Sign launguage detection\RealTimeObjectDetection\Tensorflow\labelImg\labelImg.py", line 1309, in change_save_dir_dialog
    self.show_bounding_box_from_annotation_file(self.file_path)
  File "C:\Users\hp\AI\DL formation\Projects\Object recognition.CV\Sign launguage detection\RealTimeObjectDetection\Tensorflow\labelImg\labelImg.py", line 1182, in show_bounding_box_from_annotation_file
    basename = os.path.basename(str(os.path.splitext(file_path))[0])
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen ntpath>", line 232, in splitext
TypeError: expected str, bytes or os.PathLike object, not NoneType

I got this error ,any solution please ???
