### ISSUE TITLE
labelImg.ui file

### ISSUE THREAD

**Issue by CF2220160244** [tzutalin/labelImg#222]
how can i get the labelImg.ui file

- **OS:**
- **PyQt version:**

**Comment by tzutalin** [comment]
what is labelImg.ui file?

**Comment by vdalv** [comment]
Closed due to inactivity. Please feel free to reopen and clarify your question.

Thanks,

-Vlad

**Comment by peach1995** [comment]
I want to develop software based on the project,so I also need the file named "labelImg.ui",I want to add many new widgets on the software,so it is difficult to add widgets by the code.I want to add new widgets by QT Designer.I want to get the labelImg.ui file.I'm looking forward your replies.

**Comment by ymqian1785** [comment]
I also want to develop software based on the project,so I also need the file named "labelImg.ui",I want to add many new widgets on the software,so it is difficult to add widgets by the code.I want to add new widgets by QT Designer.I want to get the labelImg.ui file.I'm looking forward your replies.

**Comment by Cerno-b** [comment]
I think there is none. labelImg seems to be developed with all GUI elements placed "by hand"
