### ISSUE TITLE
How can I crop the ROI image? Not only label it.

### ISSUE THREAD

**Issue by Isabelliu** [tzutalin/labelImg#223]
Hi,thank you for your work.
How can I crop the rectangle ROI image and save it?
I am a beginner of python.
which part of the code should I modify or add?
Can you give me a hint? Or do you consider to add this function to your LabelImg?

**Comment by tzutalin** [comment]
Hi @Isabelliu ,
There are several ways to achieve.  If you are familiar with OpenCv, you can simply crop the ROI and save it
