### ISSUE TITLE
Unable to run under PyQt4 environment

### ISSUE THREAD

**Issue by TommeyChang** [tzutalin/labelImg#229]
This edition has some new features which is much more friendly for users.
But it is unable to run under PyQt4 environment, what is more, the windows app is unable to run as it is built with PyQt4.
This problem is caused by importing QtCore from PyQt5 directly in the file resources.py without checking the PyQt version.

It is easily to solve by just checking the PyQt version in the resources.py.

- **OS:Ubuntu 16.04
- **PyQt version: PyQt4

**Comment by tzutalin** [comment]
Do you have logs? Since I didn't encounter this problem.

**Comment by TommeyChang** [comment]
I am sorry, this is my fault. When I made the codes I have installed the pyqt5. Then I changed pyqt5 to pyqt4 without remaking the codes which leading the error.

**Comment by vdalv** [comment]
Sounds like this issue has been resolved, but please feel free to re-open if that's not the case.
