### ISSUE TITLE
Error when using the "rectbox" tool. Python crashes. 

### ISSUE THREAD

**Issue by Yosukywen** [tzutalin/labelImg#233]
Hi, I'm trying to run the labelImg.py and it keeps crashing when I try to use the "rectbox" tool.
I used the pre-built package for Windows (Windows_v1.6.0) and it works very well. I can add rectboxes to the image and save the annotations. However, when I build the source files according to the instructions and I type "python labelImg.py" I get this error. When I select the "rectbox" tool, as soon as I click on the image, Python crashes and the labelImg window gets closed.

The error I get can be observed in the next picture:

![error_label](https://user-images.githubusercontent.com/28245919/35850516-bae4e956-0aea-11e8-871d-98f334ae1c6b.jpg)

I have tested the tool on a virtual machine with Ubuntu and the same error happens. Any idea? Thanks!

- **OS:** Windows 10, Anaconda 2
- **Python version:**  Python 2.7.13
- **PyQt version:**  PyQt 4.11.4

**Comment by gzero20** [comment]
Same problem here. Using Ubuntu. Are there required formats or configs of the images?

**Comment by vdalv** [comment]
@Yosukywen @gzero20 

Have you guys tried this recently, with the latest code/builds?

**Comment by vdalv** [comment]
Closed due to inactivity. Please feel free to reopen if you're continuing to face this issue.

Thanks,

-Vlad
