### ISSUE TITLE
Can't save unicode labels

### ISSUE THREAD

**Issue by k8tems** [tzutalin/labelImg#24]
I'm getting a `UnicodeEncodeError` every time I try to save unicode labels.
![](https://i.gyazo.com/47fa09a207aa8d8d72ea9417a656eea3.png)
Exception traceback:

```
Traceback (most recent call last):
  File "labelImg/labelImg.py", line 946, in saveFile
    else self.saveFileDialog())
  File "labelImg/labelImg.py", line 969, in _saveFile
    if filename and self.saveLabels(filename):
  File "labelImg/labelImg.py", line 588, in saveLabels
    print 'savePascalVocFormat save to:' + filename
UnicodeEncodeError: 'ascii' codec can't encode characters in position 49-54: ordinal not in range(128)
```

I'm currently working around this by replacing  the call to `str()` in `PascalVocWriter.appendObjects` with `repr`(Don't know if this complies with the pascal voc format).

**Comment by tzutalin** [comment]
Hi @k8tems ,
  I tried to change save and load XML with unicode. Could you hlep me to try again?

https://github.com/tzutalin/labelImg/commit/50a079edc40555f6dfecad64103a99ba615975be

**Comment by mineshmathew** [comment]
@k8tems was the issue resolved with the above fix

**Comment by ujsyehao** [comment]
hi, I use the latest version 1.4 on ubuntu 16.04, but I still has the error
`Traceback (most recent call last):
  File "labelImg/labelImg.py", line 1178, in saveFile
  File "labelImg/labelImg.py", line 1206, in _saveFile
  File "labelImg/labelImg.py", line 733, in saveLabels
UnicodeEncodeError: 'ascii' codec can't encode characters in position 25-26: ordinal not in range(128)
`**how to solve it???**

**Comment by tzutalin** [comment]
@ujsyehao ,
  What is your language? Does it happen for all of your images? Can you upload the original image?

**Comment by ujsyehao** [comment]
thank you in advance! @tzutalin , my language is english, it happens for all my images
original image:
![dji_0288](https://user-images.githubusercontent.com/17454232/28716007-77d1776a-73cd-11e7-97d2-42d3ab7cb386.JPG)

**Comment by tzutalin** [comment]
@ujsyehao ,
  I will spare some time to reproduce it. :)

**Comment by ujsyehao** [comment]
@tzutalin I am very sorry to disturb you, I install labelImg from .zip file, should I install it from source code?

**Comment by tzutalin** [comment]
Hi @ujsyehao ,
  Sure, you can refer to READMME.md to try to install from scratch. It is very easy to install and run it.
After you run it, you can try to fix the issue. (convert the ASCII o Unicode in labelImg.py:733)
