### ISSUE TITLE
Running on Windows causes python to crash immediately

### ISSUE THREAD

**Issue by lYlantis** [tzutalin/labelImg#246]
- **OS:** Windows 10
- **PyQt version:** Have PyQt4 and 5 installed

Using python 3.5.2  from the command line I run:
```
pyrcc4 -py3 -o resources.py resources.qrc
python labelimg.py
```
It immediately crashes with no error message. Same thing if I try running it from IDLE. 

![issue](https://user-images.githubusercontent.com/11239651/36765670-5d4ceaf6-1c00-11e8-9bfe-9374bf3b0266.png)

When I click debug and open up in visual studio it says:
Unhandled exception at 0x000000006AD26A90 (python35.dll) in python.exe: 0xC0000005: Access violation reading location 0xFFFFFFFFFFFFFFFF.

![issue2](https://user-images.githubusercontent.com/11239651/36768177-cbad0d36-1c0b-11e8-867a-0605f21d40e9.png)

It works fine with the pre-built binary, but I was hoping to modify the code for some custom functionality. Any ideas?

**Comment by quendee** [comment]
Same thing is happening to me, any ideas what can I do to run the file?

**Comment by lYlantis** [comment]
I haven't figured this issue out yet, but the binaries still work: https://tzutalin.github.io/labelImg/

**Comment by lYlantis** [comment]
The issue is running the pyrcc4 command. If you just clone the repo and run 
```
python labelimg.py
```
It opens fine (but without icons). However, if you run 

```
pyrcc4 -o resources.py resources.qrc
python labelImg.py
```
It will crash immediately.

**Comment by vdalv** [comment]
@lYlantis Can you try running `pyrcc5 -o resources.py resources.qrc` instead of the pyrcc4 command?

**Comment by lYlantis** [comment]
@vdalv Same result.

**Comment by vdalv** [comment]
What is the output on the command prompt when the program crashes?

**Comment by vdalv** [comment]
> It works fine with the pre-built binary, but I was hoping to modify the code for some custom functionality.

I just noticed this^ comment. Can you delete this file and try again? File path: `C:/Users/<your_username>/.labelImgSettings.pkl`

I think that might sort you out.

**Comment by lYlantis** [comment]
I tried that and it didn't change anything. However, after I deleted it as well as my labelImg folder and then re-cloned the repo and its working now. Thanks!
