### ISSUE TITLE
Can I call labeling functions in my code without the GUI?

### ISSUE THREAD

**Issue by JoeHsiao** [tzutalin/labelImg#251]
I will be creating some synthetic training data, and that means I will know the locations and sizes of those objects in the image. Is there some guideline of how to use those labeling functions without the GUI?

**Comment by vdalv** [comment]
No, you cannot do this with labelImg in it's current state. You could probably achieve this functionality with a simple Python script that reads the location and sizes and then outputs a PascalVOC formatted xml filled with the appropriate data...
