### ISSUE TITLE
how to modify labelImg code to draw polygon bounding box instead of only rectangular bounding boxes? 

### ISSUE THREAD

**Issue by abunesh** [tzutalin/labelImg#254]
i am trying to label cars and people and i would like to be able to "shade" the outline of the car/person instead of just drawing a box over them. is it possible to modify the code to to turn the "create rectbox" option to a "create polygon" option?
or even i freestyle option where i can click on a few points along the perimeter and it will select the outline? 
and if it is possible, how do i go about doing so? thank you for the help!

**Comment by vdalv** [comment]
I think [this project](https://github.com/wkentaro/labelme) has what you're looking for. I believe it's what labelImg was based on.
