### ISSUE TITLE
[BUG] When click Save .xml extension is not added to markup file

### ISSUE THREAD

**Issue by mrgloom** [tzutalin/labelImg#256]
Using prebuild LabelImg v.1.6.0 on Windows I have a problem that I need to manually specify extension each time after click Save, if I just Save than markup data file is saved without extension and when directory is open second time LabelImg can't see markup files (because they doesn't have  .xml extension). I think it's a bug and this process can be automated.

**Comment by benguyer** [comment]
What version of Windows and PyQT are you using?

**Comment by mrgloom** [comment]
OS: Win 7
I'm using prebuild `labelImg.exe`, so QT is linked statically inside?

**Comment by karry520** [comment]
me too

**Comment by vdalv** [comment]
@mrgloom @karry520 Please pull the latest code or release and reopen this issue if the bug still hasn't been resolved.

Thanks,

-Vlad
