### ISSUE TITLE
can not save xml file on win10

### ISSUE THREAD

**Issue by LukeHe** [tzutalin/labelImg#26]
when I have finished annotation the image that I can't save xml files in window 10.when I tick the button to save the xml file to my folder .I can find nothing in my computer. I have installed python2.7, pyQt4, numpy, and lxml, PIL on my computer.

**Comment by tzutalin** [comment]
@Luke, 
  Currently, I didn't have PC with win 10. I can't help u recently

**Comment by zhubuntu** [comment]
@LukeHe I tried on win10，and there is a way to solve this problem.
First ,change the
``` 
import sys
```
to
```
import sys
reload(sys)
sys.setdefaultencoding('utf-8')
```
Secound,the path where you save the xml can't have chinese.

**Comment by tzutalin** [comment]
@LukeHe ,
I try to fix this problem. If you have free time, could you help to try again on your side?
https://github.com/tzutalin/labelImg/commit/50a079edc40555f6dfecad64103a99ba615975be
