### ISSUE TITLE
No available formula with the name "pyqt4-dev-tools" 

### ISSUE THREAD

**Issue by Yaffa1607** [tzutalin/labelImg#27]
Hi , How do I instal the "pyqt4-dev-tools for mac? 
Brew install pyqt4-dev-tools raises the error : Error: No available formula with the name "pyqt4-dev-tools"

I am using conda to install everything. Any idea how to get it running for mac?

**Comment by tzutalin** [comment]
@Yaffa1607 ,
 I am not a mac user.  Can you describe your steps?
Have you tried the below commands?
`brew install PyQt4`
`brew install python qt pyqt pyside pyside-tools`

**Comment by mrkent** [comment]
I have the same issue. 
```
$ brew search qt
homebrew/boneyard/libdbusmenu-qt               pyqt5                  qtfaststart
homebrew/boneyard/pyqt ✔                       qt ✔                   qtplay
homebrew/boneyard/qt-mobility                  qt5 ✔                  sqtop
homebrew/games/qtads              homebrew/science/uniqtag    Caskroom/cask/mqttfx       Caskroom/cask/qtpass
homebrew/science/iqtree           homebrew/versions/qt52      Caskroom/cask/qt-creator   Caskroom/cask/qtspim
homebrew/science/seqtk            homebrew/versions/qt55      Caskroom/cask/qtox         Caskroom/versions/qt-creator-dev
```

**Comment by rflynn** [comment]
> Brew install pyqt4-dev-tools raises the error : Error: No available formula with the name "pyqt4-dev-tools"

@Yaffa1607 `pyqt4-dev-tools` is an Ubuntu-specific package name. Take another look at the OS X-specific build instructions in the updated README
