### ISSUE TITLE
Image wide label

### ISSUE THREAD

**Issue by CMCDragonkai** [tzutalin/labelImg#276]
Other than bounding box rectangle labels, is there a way to just label the entire image with a particular label?

This way we can have image-wide metadata and bounding box labels.

**Comment by vdalv** [comment]
@CMCDragonkai No, this isn't something that's supported by labelImg. But you can write a script that creates an xml file with one large rectangle around the entire image, with a particular label... I wrote this script myself, but I'm afraid I no longer have it.
