### ISSUE TITLE
Segmentation fault (core dumped) - Ubuntu 16.04

### ISSUE THREAD

**Issue by skanwwal** [tzutalin/labelImg#279]
Hi,

 I am trying to process some images using GAMMA software in terminal to view a raster using disSLC/rasSLC commands. It gives me this segmentation problem. I am a beginner.  Initially I thought it is some problem related to JDK on ubuntu 16 system as Matlab 2015b software keep giving me an error of graphics issue after installation. I'd really appreciate if some can provide any assistance. 

I am using Ubuntu 16.05 64but on ASUS platform. 

Thank you,

![whatsapp image 2018-04-17 at 9 53 17 pm](https://user-images.githubusercontent.com/33715874/38874138-ffd10028-4289-11e8-8ef1-7f4ff08c4a18.jpeg)
![whatsapp image 2018-04-17 at 9 53 53 pm](https://user-images.githubusercontent.com/33715874/38874139-fffcc992-4289-11e8-94e3-8a62440b8481.jpeg)

**Comment by srslynow** [comment]
Why are you posting this here? As you can see this is the issue list of labelImg, and this error clearly has nothing to do with labelImg.

That being said, your errors are clearly display related. Have you messed with your ```DISPLAY``` environment variable, or are you working remotely on a computer via VNC?

**Comment by skanwwal** [comment]
Maybe, I am not sure. How can I check? I am not working remotely but sometimes I do use teamviewer.

**Comment by skanwwal** [comment]
Here is the output of echo DISPLAY command: 
:1

**Comment by vdalv** [comment]
As @srslynow stated (neat username btw), this issue doesn't seem to be related to labelImg in any way, shape, or form. Please post this in the appropriate channel.

Thanks,

-Vlad
