### ISSUE TITLE
Previous labels do not appear when I reopen an image file

### ISSUE THREAD

**Issue by Bigoudom** [tzutalin/labelImg#293]
- **OS:** Windows 7
- **PyQt version:** I have downloaded LabelImg from prebuilt binaries

**Comment by vdalv** [comment]
I'm having this issue as well w/ the latest version (v1.6.1), on Windows 10. I noticed that it labels some images fine, but not others...

I've gone back to [windows_v1.5.2](https://www.dropbox.com/s/954fn0qakr6zsvk/windows_v1.5.2.zip?dl=1) for now.

**Comment by Bigoudom** [comment]
Hi,

I continue to use the latest version and just do as follows to display previous label:
I open my image and the File/Open Annotation and I chose the corresponding xml file. 
It is not the most convenient way but it is sufficient for me.

**Comment by vdalv** [comment]
It looks like the issue is that the xml files are being saved as image_name.xml.xml, and labelImg is looking for image_name.xml, so this issue is related to https://github.com/tzutalin/labelImg/issues/252

I'll be submitting a PR momentarily that should take care of this.

**Comment by rmprater-papajohns** [comment]
sometimes it labels the xml files as <name>.xml.xml and this will not show up until you rename the annotation as <name>.xml

**Comment by vdalv** [comment]
This issue should be resolved now. Please pull the latest code or binary and let us know if you continue to experience it, thanks.

**Comment by Bigoudom** [comment]
Hi, as previously written I use the 1.6.1 version and I use File/Open Annotation when the annotation does not open automatically. I have not had issue with the naming of xml files. For me the issue #293 is solved.

Thanks!
