### ISSUE TITLE
Update the Windows + anaconda section of README.rst

### ISSUE THREAD

**Issue by XupingZHENG** [tzutalin/labelImg#294]
Hi,

I install the anaconda3 5.1.0 on my windows7 laptop today, and I find that using pyqt5 can compile.
The following commands are ok, I can run labelImg.
```
pyrcc5 -o resources.py resources.qrc
python labelImg.py
```

The README.rst can be updated

**Comment by vdalv** [comment]
Thanks for looking into this, but I'm having some issues. I've run the following:
```
conda install pyqt=5
pyrcc5 -o resources.py resources.qrc
python labelImg.py
```

And I get this error trace on the last command:
```
Traceback (most recent call last):
  File "labelImg.py", line 1434, in <module>
    sys.exit(main())
  File "labelImg.py", line 1430, in main
    app, _win = get_main_app(sys.argv)
  File "labelImg.py", line 1423, in get_main_app
    argv[3] if len(argv) >= 4 else None)
  File "labelImg.py", line 98, in __init__
    self.settings.load()
  File "C:\labelImg\libs\settings.py", line 33, in load
    self.data = pickle.load(f)
ModuleNotFoundError: No module named 'PyQt4'
```

Any suggestions? Thanks

**Comment by vdalv** [comment]
Thanks for looking into this, but I'm having some issues. I've run the following:
```
conda install pyqt=5
pyrcc5 -o resources.py resources.qrc
python labelImg.py
```

And I get this error trace on the last command:
```
Traceback (most recent call last):
  File "labelImg.py", line 1434, in <module>
    sys.exit(main())
  File "labelImg.py", line 1430, in main
    app, _win = get_main_app(sys.argv)
  File "labelImg.py", line 1423, in get_main_app
    argv[3] if len(argv) >= 4 else None)
  File "labelImg.py", line 98, in __init__
    self.settings.load()
  File "C:\labelImg\libs\settings.py", line 33, in load
    self.data = pickle.load(f)
ModuleNotFoundError: No module named 'PyQt4'
```

Note: I'm on Win10

Any suggestions? Thanks

**Comment by XupingZHENG** [comment]
@vdalv did you use Anaconda2 or Anaconda3? I use Anaconda3

**Comment by vdalv** [comment]
Thanks for the info, I took another look and was able to resolve the issue by deleting this file: `C:\Users\USERNAME\.labelImgSettings.pkl` and re-running the pyrcc5 command.

I'll be submitting a PR with this updated info momentarily. Thanks again.

**Comment by vdalv** [comment]
Thanks again @XupingZHENG, the README.rst file has been updated.

**Comment by zhaoxuyan** [comment]
### For Windows
Go to `Users\xxx\` delete `.labelImgSettings.pkl`,then `pyrcc5 -o libs/resources.py resources.qrc`, `python labelImg.py`
### For Mac or Linux
Go to home(~) folder, `rm .labelImgSettings.pkl`, then `pyrcc5 -o libs/resources.py resources.qrc`, `python labelImg.py`
