### ISSUE TITLE
Needs updates

### ISSUE THREAD

**Issue by drcrook1** [tzutalin/labelImg#30]
Python 3.5 and PyQT5 and latest Anaconda.  Testing on windows 10 with latest stack.

**Comment by tzutalin** [comment]
Worth of trying. But I do not have free time to do that in two months

**Comment by drcrook1** [comment]
Hrm, any thoughts on where I might start modifying hte code to update it?

**Comment by drcrook1** [comment]
Mostly I'm running into issues with python 2.6 I beleive

**Comment by tzutalin** [comment]
I think you can try to install PyQT5 and  3.5 to compile first.
Besides, what kind of issues you meet with python 2.6?

**Comment by tzutalin** [comment]
Hi @drcrook1 ,
Thanks to @rflynn . He is done with a draft version about this. 
FYI https://github.com/tzutalin/labelImg/pull/45
