### ISSUE TITLE
I want to add function to draw polygon bounding box with keeping the function to draw rectangular bounding boxes

### ISSUE THREAD

**Issue by leejinho0408** [tzutalin/labelImg#305]
I want to add function to draw polygon bounding box with keeping the function to draw rectangular bounding boxes.
"Labelme" is famous tool for drawing polygon bounding box. However, i would like to mix that function with original labelimg...
Please give me any hints or comments. Thank you so much

- **OS:** Ubuntu 16.04
- **PyQt version:** 5

**Comment by dlueder** [comment]
I did this myself, by defining a second drawing mode and then adding actions for adding some standard polygon shapes into my bounding box (mostly circles). Then you can modify the mouse events and paintEvent for showing both.

**Comment by vdalv** [comment]
@leejinho0408 Looks like his code is: https://github.com/dlueder/adpkd-support-tool/blob/master, particularly: https://github.com/dlueder/adpkd-support-tool/blob/master/main.py

**Comment by dlueder** [comment]
The modified canvas for drawing polygons from a predefined generated shape is actually here: https://github.com/dlueder/adpkd-support-tool/blob/master/libs/canvas.py

**Comment by vdalv** [comment]
@dlueder Thanks for the clarification.
@leejinho0408 This should be enough info to get you well on your way.

Best of luck,

-Vlad
