### ISSUE TITLE
pyqt4 problem

### ISSUE THREAD

**Issue by selster** [tzutalin/labelImg#306]
Hello, I appreciate your delightful program.  I have a win 7, 64-bit machine, with python 3.6.5.  I did a pip3 install pyqt5 and now a pip3 show pyqt5 shows it is installed in site-packages.  When I run your program, I changed your directions from pyrcc4 -o resources.py resources.qrc to the same but starting with pyrcc5.  After all, "5" is now installed.  Correct?  (Using pyrcc4 resulted in more pyQT4 errors but from the very start of the program, beginning with resources.py.)  Butpyrcc5 results in a resource.py that has an import pyQT5.  However, when I python labelIMG.py, I get an error in settings.py, at line 33, apparently because pickle requires pyQT4(?).  Since I am not a boni fide pythonista, I hope very much that you will resolve this problem, and hopefully very soon.  thank you, Steve

- **OS:**
- **PyQt version:**

**Comment by vdalv** [comment]
Ah, this is a known issue that I've experienced as well.

Here's the solution: https://github.com/tzutalin/labelImg/issues/221#issuecomment-368215559

**Comment by selster** [comment]
The solution looks like it works when running the exe file; but I am running labelIMG from a python prompt.  Is there a solution for this?  Thanks, Steve

**Comment by vdalv** [comment]
Have you tried it? It worked for both cases for me.

**Comment by selster** [comment]
I switched to pyQT5.  Then it worked.

**Comment by vdalv** [comment]
Nice! Thanks for the update.

**Comment by zhaoxuyan** [comment]
### For Windows
Go to `Users\xxx\` delete `.labelImgSettings.pkl`,then `pyrcc5 -o libs/resources.py resources.qrc`, `python labelImg.py`
### For Mac or Linux
Go to home(~) folder, `rm .labelImgSettings.pkl`, then `pyrcc5 -o libs/resources.py resources.qrc`, `python labelImg.py`
