### ISSUE TITLE
the minX mustn't equal maxX and the same as minY&maxY value

### ISSUE THREAD

**Issue by loulansuiye** [tzutalin/labelImg#310]
initPos = self.current[0]
                    minX = initPos.x()
                    minY = initPos.y()
                    targetPos = self.line[1]
                    maxX = targetPos.x()
                    maxY = targetPos.y()
                    self.current.addPoint(QPointF(maxX, minY))
                    self.current.addPoint(targetPos)
                    self.current.addPoint(QPointF(minX, maxY))
                    self.current.addPoint(initPos)
self.line[0] = self.current[-1]

**Comment by vdalv** [comment]
Please elaborate on what you're trying to do.
