### ISSUE TITLE
Shortcuts of next image?

### ISSUE THREAD

**Issue by jinfagang** [tzutalin/labelImg#313]
Shortcuts of next image? Is there already a shortcuts exist or not?

**Comment by vdalv** [comment]
Yes, the 'a' and 'd' keys.

**Comment by srdg** [comment]
Does there exist a shortcut for drawing the rectangle (activating that option)?

**Comment by srdg** [comment]
Found it. 'w' key is the shortcut for activating the create  a rectangle option.

**Comment by splevine** [comment]
ctrl+n works on windows to create a new rectangle

**Comment by faizygithub** [comment]
my next images  and previous  images button is not working  also the shortcut keys which mention above .What can i do please help it taking too much time without it.I have to go to folder and then scroll down for selecting pictures for annotation.Thanks in advance

**Comment by faizygithub** [comment]
> Yes, the 'a' and 'd' keys.

my next images and previous images button is not working also the shortcut keys which mention above .What can i do please help it taking too much time without it.I have to go to folder and then scroll down for selecting pictures for annotation.Thanks in advance

**Comment by tothedistance** [comment]
you can always click that next image button. of course not so fast as shortcut.
