### ISSUE TITLE
X-axis bounding box shift on mouse button release

### ISSUE THREAD

**Issue by miguelgamendes** [tzutalin/labelImg#316]
OS: Linux

I noticed that, on maximum zoom, when I try to set a bounding box, upon releasing the left mouse button, the entire box shifts one pixel to the right.

Not sure if intended, but it sure doesn't seem to be appropriate, as I assume the box I'm creating would be the final one to be labeled.

**Comment by vdalv** [comment]
Are you running labelImg from the latest source? Because I believe this issue was resolved a couple versions ago...

**Comment by miguelgamendes** [comment]
This was with 1.6.1

What's weird is that this particular problem happens randomly(?). I've seen it once or twice, but then it stops for a while.

I'll update and report back if I ever see it again 👍

**Comment by vdalv** [comment]
Yeah, that's pretty bizarre...

I think this issue was resolved a couple versions back, so upgrading to v1.7.0 may or may not fix it. I'll close this issue for now, but by all means feel free to reopen it if the issue persists.
