### ISSUE TITLE
Add cut button for bounding boxes

### ISSUE THREAD

**Issue by vBoykoGit** [tzutalin/labelImg#318]
I offer add cut button to cut all bounding boxes into little images.
It can be useful when you need big annotated images and simple little images both.
So you dont need to do double work.

**Comment by vdalv** [comment]
I don't understand what you're asking for...can't you just duplicate the bounding box and then resize it was needed? Can you provide an example of what you're trying to annotate?

**Comment by vBoykoGit** [comment]
Ok. I use Nvidia DIGITS object detection which requires annotated images. But also i want use TensorFlow which require simple images.
For example i have an image with selected faces:![1](https://user-images.githubusercontent.com/13284583/41810922-b0fe1a72-7730-11e8-9a1a-d543d5b4baf9.png)
I can load it to the nvidia digits.
But also i need images like this:
![2](https://user-images.githubusercontent.com/13284583/41810981-36c0ca56-7731-11e8-9247-b8e99ff6b658.png)
I can load it to the TensorFlow.
So my idea is very simple: add button 'Cut' which creates folders by class names and put selected areas inside.
For example: we have 3 faces and 5 legs on the image, so if we press 'Cut' it creates two folders - "legs" and "faces" with 5 and 3 images inside correspondenly.

**Comment by vdalv** [comment]
Thanks for the clarification, but I don't think would be a practical feature. It seems like it would be a hassle to constantly click the 'Cut' button for every image you annotate. I wrote a script a while ago that does what you're looking for, but for all annotations in the train and val folders, at one time. I've uploaded it here: https://gist.github.com/vdalv/7aaf8a090a6111184d6b6438a6847669

**Comment by vdalv** [comment]
Thanks for the clarification, but wouldn't it make more sense to 'cut' all the images you want, at one time? I think that it would be a hassle to constantly click the 'Cut' button for every image you annotate...

I wrote a script a while ago that does what you're looking for, but for all annotations in the train and val folders, at one time. I've uploaded it here: https://gist.github.com/vdalv/7aaf8a090a6111184d6b6438a6847669

**Comment by vBoykoGit** [comment]
Thanks! If you dont plan add 'Cut' or 'Cut all' button then close this issue.
