### ISSUE TITLE
Tensorflow Object Detection creat XML files without Labelimg

### ISSUE THREAD

**Issue by Setareh123** [tzutalin/labelImg#325]
Hi everybody,

I want to run my own dataset and want to creat the xml files by myself since they are too many and it is not possible with labelimg software. 
I already have the coordinates of bonding boxes and have written a script by which i creat the XML files. 
Here is an example of created xml files:  I have around 400 training images , each with 20-30 objects in it. 
 But after runnig the code of "xml_to_csv.py" i get the following error (in the attachment  also). While it is not there when I run it with a labelimg-created xml.  - Thank you in advance.
error: 
![untitled](https://user-images.githubusercontent.com/39617031/42538388-13034f48-8498-11e8-9fa7-53c9e7292c8c.jpg)

**Traceback (most recent call last):
  File "xml_to_csv.py", line 36, in <module>
    main()
  File "xml_to_csv.py", line 31, in main
    xml_df = xml_to_csv(image_path)
  File "xml_to_csv.py", line 17, in xml_to_csv
    int(member[4][0].text),
ValueError: invalid literal for int() with base 10: '\ufeff16'**

my generated xml file : 
[Image129.txt](https://github.com/tzutalin/labelImg/files/2182158/Image129.txt)
![untitled1](https://user-images.githubusercontent.com/39617031/42540037-3df4c434-849d-11e8-9abb-58c3019773fb.jpg)

**Comment by vdalv** [comment]
I'm closing this because it's not related to labelImg. However, I've figured out your issue. It looks like there's a hidden character being written in front of the first <xmin> value (see pic below for location). Please check your script again.

![](https://i.imgur.com/SBYHEC1.png)

Cheers,

-Vlad

**Comment by vdalv** [comment]
I'm sorry that you found my answer unsatisfactory, but this is not the place to receive support for this issue.
