### ISSUE TITLE
Installing the program using setup.py does not work

### ISSUE THREAD

**Issue by eypros** [tzutalin/labelImg#327]
I am using a prebuild binary of labelImg which works fine via python3. Previously I used it in windows and it was useful that the program was installed. 
So, I was wondering if it is possible to install it in Ubuntu also. I know I can use the PyPI way of installing it. I tried installing it using setup.py:
`sudo python3 setup.py install`

which seemed to be successful. Nevertheless when run the program complains about import issues:

> ImportError: No module named 'resources'

is there a way to install it using setup.py or not?

- OS: Ubuntu 16.04
- PyQt version: PyQt5

**Comment by vdalv** [comment]
setup.py is for installing on macOS. Please install using the "Python 3 + Qt5" instructions [here](https://github.com/tzutalin/labelImg#ubuntu-linux)

The Linux binaries are outdated, so atm I recommend running from source, following the instructions mentioned above.

**Comment by eypros** [comment]
OK, thanks for the quick answer
