### ISSUE TITLE
How to create multiple labels for same boundingbox

### ISSUE THREAD

**Issue by bharath063** [tzutalin/labelImg#332]
For eg: An object might be a Dog, it might be Brown, etc. How to add multiple labels to the same object. The workaround that I'm using now is to create multiple bounding boxes for different labels.

- **OS:**: macOS 10.13.4

**Comment by vdalv** [comment]
It sounds more like you're interested in adding attributes to your objects. This PR: https://github.com/tzutalin/labelImg/pull/286 may be useful.

**Comment by xiaoboxie** [comment]
have a look on my fork, repeat LabelDialog. There are lots of hardcode in my code for my project, you can do a few modifications

**Comment by rahuladream** [comment]
I do not found till now but what I did hardcoded the rest tag into label.csv and work fine for me.
