### ISSUE TITLE
Can this tool be converted into an audio label tool？

### ISSUE THREAD

**Issue by hyzhan** [tzutalin/labelImg#334]
Thanks for this useful image label tool.
And I need to label some audio files recently. How can  I convert this tool  into an audio label tool？What are the files or code  about input, output and display in the “libs ”folder? I'm not familiar with qt. I hope I can get some hints from this repository. Thank you.

**Comment by vdalv** [comment]
This tool was built for images, so I think you'd have to do a substantial re-write to get it to work for audio files. I would recommend looking for another tool...here's two that I found via Google:

https://github.com/dsgou/annotator
https://github.com/CrowdCurio/audio-annotator
