### ISSUE TITLE
pip version python3

### ISSUE THREAD

**Issue by cosmoscalibur** [tzutalin/labelImg#338]
Use pip version for Python3 is not working but with Python2 yes. In Python3 pip installation when labelImg is executed, the error is about impossible to import resource module.

- **OS:** Linux Mint 19
- **PyQt version:** 5.9

**Comment by shaform** [comment]
Also see #106.

**Comment by vdalv** [comment]
Closing because there's an open issue for this already (https://github.com/tzutalin/labelImg/issues/106). Thanks @shaform
