### ISSUE TITLE
Rotate 90° when opening？

### ISSUE THREAD

**Issue by pprp** [tzutalin/labelImg#342]
### When I open it with labelimg, the image will rotate by 90°. Why is this happening? How should I solve this problem?

**Comment by humandotlearning** [comment]
When a picture is taken with some camera, it is recorded as a landscape direction picture and it is specified in the EXIF file of the picture that it was a portrait direction picture.
labelImg isn't handling the rotation needed through that EXIF file.

You have to rotate and save the pictures before using them in labelImg.

You can use

On Linux :
exiftran -ai *.jpeg
exiftran
On Windows:
JPEG Autorotate

**Comment by pprp** [comment]
Thank you very much!^_^

**Comment by ryouchinsa** [comment]
RectLabel is an offline image annotation tool for object detection and segmentation.
Although this is not an open source program, with RectLabel you can remove the EXIF orientation flags from images and convert images to the front orientation. If necessary, you can rotate the image right/left by 90 degrees.
https://rectlabel.com/help#remove_exif_orientation_flags
