### ISSUE TITLE
'pyrcc4' is not recognized 

### ISSUE THREAD

**Issue by knightcube** [tzutalin/labelImg#350]
I tried running the setup instructions in the README. When i tried running this line in cmd `pyrcc4 -o resources.py resources.qrc` , i get this error - `'pyrcc4' is not recognized as an internal or external command,operable program or batch file`

- **OS:Windows**
- **PyQt version:PyQt5**

**Extra Note**
I went inside C:\Program Files\Python36\Lib\site-packages\PyQt5 and there are files named pyrcc_main.py, pyrcc.pyd but could not find pyrcc5. Probably this is causing the error.  So i tried removing the `import resource` line from `labelImg.py` and everything works as expected but I dont know if it would cause some other error or not because I dont see resource being used anywhere in `labelImg.py`. Would it be a problem if I dont have that resource file?

How do i resolve this issue?

**Comment by KNaudin** [comment]
It is asked to use PyQt4 in the installation section. The pyrcc4.exe file will be there and you'll have to add it to the path.

**Comment by AwesomePeople** [comment]
Try with Cygwin64 terminal, success for me, it contain pyrcc4

**Comment by iseegr8tfuldeadppl** [comment]
for me adding the pyrcc4 path to system environment variables made it work
`C:\Users\BenBouali\AppData\Local\Programs\Python\Python35\Lib\site-packages\PyQt4`
