### ISSUE TITLE
virus warning

### ISSUE THREAD

**Issue by theprodev** [tzutalin/labelImg#358]
Unfortunately this is showing a virus inside your windows binary;
https://www.virustotal.com/#/file/cf9f6f0aed6bf783d2769a765cfaf7460f82ea6ed7ee2d296d58f1cd71a7a749/detection

Can you please help? I really like this tool.

Thanks.

**Comment by vdalv** [comment]
Closing this because there's already an open issue for this problem. https://github.com/tzutalin/labelImg/issues/166
