### ISSUE TITLE
ImportErrors for Python 3 Qt 5

### ISSUE THREAD

**Issue by rjbruin** [tzutalin/labelImg#360]
When using the standard installation instructions for Python 3 and Qt 5 I get the following error:

```python
Traceback (most recent call last):
  File "labelImg.py", line 15, in <module>
    from PyQt5.QtGui import *
ImportError: No module named 'PyQt5'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "labelImg.py", line 24, in <module>
    import sip
ImportError: No module named 'sip'
```

It looks like this is caused by not installing the pip package `pyqt5`. However, this is not noted in the installation instructions.

- **OS:** Ubuntu 16.04
- **PyQt version:**

**Comment by elieser1101** [comment]
same problem

**Comment by xiaoboxie** [comment]
try update PyQt to the latest version ( PyQt 5.11 )

**Comment by rjbruin** [comment]
> try update PyQt to the latest version ( PyQt 5.11 )

I don't think that solves the problem, since the problem seems to be that PyQt isn't installed at all.

**Comment by danluev08** [comment]
Hi everyone! I haven't been able to solve the problem.
I have  updated PyQt to its last version and the same error persists.
Any additional help?

**Comment by satianferdy** [comment]
bro already have a solution?
i have same problem

**Comment by tzutalin** [comment]
Could you check this which is how we built this repo
https://github.com/tzutalin/labelImg/blob/master/.github/workflows/package.yml

**Comment by Ali-Abozaid** [comment]
in this case you might  write one of the commend wrong (this error showed to me before I find out the mistake )
first :
conda install pyqt=5
second : 
conda install -c anaconda lxml
third : 
pyrcc5 -o libs/resources.py resources.qrc
finally you can run : 
python labelImg.py

**Comment by Ali-Abozaid** [comment]
don't forget to cut ( resources.py  and resources.qrc )then paste thim in libs folder
