### ISSUE TITLE
Could you please add the support for CJK

### ISSUE THREAD

**Issue by yangulei** [tzutalin/labelImg#362]
Thanks for sharing this useful tool.
I'm using labelImg to label vehicles in traffic images, and the label are Chinese names, which is difficult to translate to English. Even if we translate the names to English, the people who do the labeling job may not understand the exact meaning of the label, there are information loss in the translate and re-translate processes.
So, could you please add the support for CJK labels.
BTW, I'm using labelImg V1.7.0 for Windows.

**Comment by liuyiyiyiyi** [comment]
How do you solve the problem?
