### ISSUE TITLE
in generateColorByText: UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)

### ISSUE THREAD

**Issue by yangulei** [tzutalin/labelImg#364]
Thanks for sharing this useful tool 👍 
I have some Chinese names in the file "predefined_classes.txt".
At first, I just open "predefined_classes.txt" with Windows' notepad and type in the names, but I got the errors as below:
![1](https://user-images.githubusercontent.com/24203353/45289448-bcbe4580-b51f-11e8-9e34-3c5a7fb9aa02.png)
then I save the "predefined_classes.txt" with UTF-8 encoding. The app opened successfully, then I began to label the objects, I draw a box and the Chinese name list popup as it should be, but when I select a name by double click, I got the errors below:
![2](https://user-images.githubusercontent.com/24203353/45289461-c3e55380-b51f-11e8-8330-64cee8e50263.png)
I can still continue to label more objects, but none of them will be saved, the "Save" button is in gray and the Box Labels list is empty:
![3](https://user-images.githubusercontent.com/24203353/45290112-53d7cd00-b521-11e8-8a24-00c67336c49f.png)

- **OS: Windows 10 1803**
- **labelImg version: prebuilt binary Windows_v1.7.0**

**Comment by liuyiyiyiyi** [comment]
Have you saved the problem?

**Comment by tzutalin** [comment]
Did u still meet the issue? It should be fixed already if u uses the latest version

**Comment by yangulei** [comment]
@tzutalin 
I tried the new Windows v1.8.1 release, it works fine now, big thanks!
You can close this issue now.

@liuyiyiyiyi @zhuolyang 
The latest release works fine with Chinese labels now, just don't forget to save the "predefined_classes.txt" with UTF-8 encoding.

**Comment by tzutalin** [comment]
Thanks for verifying

**Comment by liuyiyiyiyi** [comment]
Thank you.The latest relase is ok.

**Comment by OnFleeks** [comment]
pardon but i have the same problem with vietnamese character, could you please have a look

**Comment by sw0965** [comment]
> 

I changed 'open dir' path (only ENGLISH) and it works now.
