### ISSUE TITLE
Fast labeling for Video Frames

### ISSUE THREAD

**Issue by giacomobartoli** [tzutalin/labelImg#366]
I need to label a lot of frames extracted from a video.
I was wondering if is there any trick to do this with labelImg.

Ex: I would like to automatically save images and, when the next images is loaded, then the same bounding box is in the picture. In this way I can quickly label many bounding boxes.

**Comment by kmsravindra** [comment]
I made changes at my repo - @ https://github.com/kmsravindra/labelImg

**Comment by kmsravindra** [comment]
I modified labelImg to accomodate this change. You can find it here - https://github.com/kmsravindra/labelImg

**Comment by giacomobartoli** [comment]
@kmsravindra thank you a lot!
