### ISSUE TITLE
a valid image file

### ISSUE THREAD

**Issue by Heipiao** [tzutalin/labelImg#37]
Error opening file
Make sure .jpg is a valid image file

**Comment by tzutalin** [comment]
More information? 
Could you share me with jpg file?

**Comment by Heipiao** [comment]
![img_00033](https://cloud.githubusercontent.com/assets/9475632/21525394/f0198f7e-cd14-11e6-9358-fa23d15b2e81.jpg)

**Comment by Heipiao** [comment]
this is the picture.

**Comment by Heipiao** [comment]
do you have any idea ,what happens? I try many ways ,but does not works

**Comment by tzutalin** [comment]
Hi @Heipiao ,
 I can use the tool to open the image. Do you use the latest version of [labelImg](https://github.com/tzutalin/labelImg)?

**Comment by tzutalin** [comment]
![screenshot from 2016-12-30 11 32 39](https://cloud.githubusercontent.com/assets/3283822/21559257/f83bf474-ce83-11e6-9465-4c401a2ddab2.png)

**Comment by Heipiao** [comment]
it not work for me, 
`2016-12-30 08:30:21.498 python2.6[3442:563661] modalSession has been exited prematurely - check for a reentrant call to endModalSession:`
maybe I should move my work from mac OS to Linux :(

**Comment by tzutalin** [comment]
Hi @Heipiao ,
 I cannot help you too much now. I do not have mac os to reproduce that..

**Comment by Heipiao** [comment]
Thank you, I will try myself

发自我的 iPhone

**Comment by rflynn** [comment]
@Heipiao the message `modalSession has been exited prematurely - check for a reentrant call to endModalSession` is a warning from the underlying QT library and not a bug in labeling -- see https://bugreports.qt.io/browse/QTBUG-37699

**Comment by Feynman27** [comment]
I'm currently running labellmg on a Max OSX 10.11.3. It appears that you can only load .png and not .jpg.

**Comment by tzutalin** [comment]
Hi @Feynman27 ,
  I am afraid that I cannot help you too much because I don't have Mac OSX to test.

**Comment by china56321** [comment]
> Error opening file
> Make sure .jpg is a valid image file

have you solve the problem? i also encountered this problem?

**Comment by arslan-cyberTITU** [comment]
Error opening file
Make sure .jpg is a valid image file

**Comment by arslan-cyberTITU** [comment]
labelimg don't find .jpg files
