### ISSUE TITLE
On the handling of exif orientation of labelImg and darknet

### ISSUE THREAD

**Issue by keides2** [tzutalin/labelImg#376]
Hi,

If the orientation of Exif is 6, the image rotates 90 degrees clockwise, but labelImg seems to rotate counterclockwise 90 degrees.
Have the recent version of labelImg repaired issue # 198 .[https://github.com/tzutalin/labelImg/issues/198]?

Also, since darknet does not consider the orientation of Exif  (since darknet recognizes that the image is rotating 90 degrees clockwise), the coordinates of the bounding box we made when labelImg rotates the image 90 degrees counterclockwise does not become wrong coordinates for darknet Is it?

Thank you,
Kei

 **OS:**
Windows7

**Comment by vdalv** [comment]
Thanks for the info. To answer your initial question: Issue 198 is still unresolved.

**Comment by panban-ux** [comment]
> I registered materials to explain this phenomenon in Github.
> Please point out if there are any mistakes.
> 
> [Exif-Eng](https://github.com/keides2/android-yolo-v2/blob/tts-JP/scripts/labelImg/exif-Eng.md)
> 
> I think that older versions of labelImg could be learned correctly by darknet in order to be able to learn, even though the appearance is rotating differently from the smart screen.
> Is this wrong?
> 
> I wrote a Python script that can rotate and convert from a set of images and annotation files and verify that annotations are correctly annotated to automatically generate 24 pairs of images and annotation files. (yolo-img-x28_windows.py)
> 
> Another script reads and saves an image with Exif information using OpenCV and PIL, so you can see what kind of image you can obtain. (exif-test.py)
> 
> **Additional notes:**
> By using[ yolo-img-rotate-del_exif.py](https://github.com/keides2/android-yolo-v2/blob/master/scripts/labelImg/yolo-img-rotate-del_exif_windows.py), you do not have to redo annotations.
> 
> [img](https://github.com/keides2/android-yolo-v2/blob/master/scripts/labelImg/yolo-img-rotate-del_exif/result-2.jpg)

How am i going to use your code in order to convert my yolo exif orientation infected .txt file that created in labelImg but shown wrong in CVAT and who knows inside Darknet training? As i understand under this method annotation orientation can be tweaked back?
