### ISSUE TITLE
Russian Label

### ISSUE THREAD

**Issue by SlimRG** [tzutalin/labelImg#378]
Windows 10 x64 
1.7.0 and down

When I want to label russian char I can't add it

For example:
 й ц у к е н г ш щ з х 

Please add this support

**Comment by DontsingListen** [comment]
Before adding this support, I think you can label them in English or number or something else first, then modify the xml file changing the 'object'-'name' to your according Russian label.
Hope it helps.

**Comment by SlimRG** [comment]
I can't do it
Because of many things
So, as I think, it is a bug
And smb should destoy it.

**Comment by tzutalin** [comment]
Check out the latest change. It was fixed already.
