### ISSUE TITLE
What‘s the effect of the button 'diffcult' ?

### ISSUE THREAD

**Issue by lx-onism** [tzutalin/labelImg#380]
- **OS:**
- **PyQt version:**
I see there is a optional button named 'difficult' in the right-upper corner of the labeling window.But the README seem not to mention how it work when labeling VOC2007 format.So I want to know if it has any help when labeling VOC?

**Comment by dbgns** [comment]
I guess you may set the difficult button checked if you are not sure about which class the current image rectangle belongs to.

**Comment by ChrisDal** [comment]
Here's a quote of previous answer (#113 )
> @315386775 Here's an explanation of the difficult attribute:
> 
> "The difficult field being set to 1 indicates that the object has been annotated as "difficult", for example an object which is clearly visible but difficult to recognize without substantial use of context." - [Source](https://github.com/tensorflow/models/issues/2386#issuecomment-330948518)

According to your deep neural network implementation, you can include or exclude difficult objects during training.

**Comment by vdalv** [comment]
Thanks @dbgns and @ChrisDal
