### ISSUE TITLE
Installing on Ubuntu 18.04 not working properly

### ISSUE THREAD

**Issue by ngesa254** [tzutalin/labelImg#381]
Could not open requirements file: [Errno 2] No such file or directory: 'requirements/requirements-linux-python3.txt'

- **OS:**
- **PyQt version:**

**Comment by tzutalin** [comment]
Do you run `sudo pip3 install -r requirements/requirements-linux-python3.txt` in the root of the repo?
How about installing the below dependnecies on your own?
```
pyqt5==5.10.1
lxml==4.2.4
```

**Comment by tzutalin** [comment]
it should be nothing to do with os

**Comment by ashnaeldho** [comment]
I am also facing the same issue. All the below dependencies also doesn't work for me.

**Comment by i-chaochen** [comment]
$ sudo pip install -r requirements/requirements-linux-python3.txt 
The directory '/home/chao/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/chao/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting pyqt5==5.10.1 (from -r requirements/requirements-linux-python3.txt (line 1))
  Could not find a version that satisfies the requirement pyqt5==5.10.1 (from -r requirements/requirements-linux-python3.txt (line 1)) (from versions: )
No matching distribution found for pyqt5==5.10.1 (from -r requirements/requirements-linux-python3.txt (line 1))

**Comment by maulik2222** [comment]
@ashnaeldho I am facing the same issue then I installed $ pip install labelImg it worked form me.

**Comment by rukon-uddin** [comment]
"pip install labelImg" worked for me. Note: the 'I' in labelImg is in uppercase
