### ISSUE TITLE
how to label in Chinese in windows

### ISSUE THREAD

**Issue by liuyiyiyiyi** [tzutalin/labelImg#383]
At the windows,I add some Chinese label in pre_class.txt to label in Chinese,the labelImg is flash back,
how to solve the problem.

**Comment by liuyiyiyiyi** [comment]
predefined_classes.txt,not  pre_class.txt

**Comment by marchawake** [comment]
@liuyiyiyiyi are you solve this problem?

**Comment by marchawake** [comment]
When I use chinese label, it throw the error like this
```
![image](https://github.com/HumanSignal/labelImg/assets/67617433/6d363088-d7a8-4f5d-b7dc-9eda00c0a1bf)

```
