### ISSUE TITLE
Zero value in annotation data

### ISSUE THREAD

**Issue by disheet** [tzutalin/labelImg#385]
Hello guys,

I found one issue with labelImg, that Sometime it saved annotation data to zero instead of one.
So later while training FASTER-RCNN model I was getting bbox Error because annotation file shouldn't contain zero value in rectangle data.

I don't whether it is problem with labelImg or somewhere else I did mistake. But In case if you are getting zero value please rise a bug report so that developer can work on it.

Thanks

**Comment by vdalv** [comment]
Please see: https://github.com/tzutalin/labelImg/issues/309#issuecomment-394246497
