### ISSUE TITLE
windows binary, YOLO format: multiple bounding boxes but only one object-class label in .txt file

### ISSUE THREAD

**Issue by julia-kraus** [tzutalin/labelImg#388]
- **OS:** Windows
- **PyQt version:**

Hi, I am using the binary version 1.8.0 for Windows. I want to tag multiple classes in one image, in YOLO format. This should for each bounding box include 'object-class', 'x', 'y', 'height' and 'width'. 

However, when I take a look at the label .txt file, the object class is only labeled for the first bounding box. For all following bounding boxes, only the parameters 'x', 'y', 'height', and 'width' are saved.

As you can see in the picture, there is a class index 0 (dog) for the first picture but no class label for the subsequent pictures.
![image](https://user-images.githubusercontent.com/22000879/48148793-e9da6a80-e2ba-11e8-89c2-e05dd86a1021.png)

Thanks!

**Comment by julia-kraus** [comment]
sorry, it was a text editor issue. thanks for your good work

**Comment by vysakhr** [comment]
Yes, I've encountered the same issue. And it seems to me that the issue occurs when opening the .txt label file in Notepad . Not while opening in a good text editor like Sublime.
