### ISSUE TITLE
Create RectBox - any way to default to always on ?

### ISSUE THREAD

**Issue by ronkent** [tzutalin/labelImg#390]
Is there any way to default the Create RectBox to always be selected ? For example, if I'm going through an entire directory of images, annotating them, then clicking Next Image (with the auto save on), I would like it to automatically enable the Create RectBox function on the next image so I don't have to click the button. I know this sounds really ridiculous, but if you have thousands of images to annotate even saving one extra mouse click really adds up. 

I love this program BTW - the auto save and single class mode has saved me tons of time over other alternative programs.

**Comment by jordi102** [comment]
Use "w" hotkey

**Comment by sourabhyadav** [comment]
@ronkent How to enable autosave. For me it always ask to save "cntrl+s" the overwrite permission "Yes". This waste a lot of time.

**Comment by edurenye** [comment]
Even having the hotkey, I think would be nice to have this feature anyway, so  we don't have to be clicking 'w' all the time, for me does not make much difference from clicking with the mouse that I'm already moving to using the keyboard. Is a repetitive action that could be avoided in my opinion.

@sourabhyadav To enable autosave just go to 'View' in the menu and click 'Auto save mode'.
