### ISSUE TITLE
Orientation issue exif related

### ISSUE THREAD

**Issue by kechan** [tzutalin/labelImg#395]
Photos taken by iPhones in Portrait mode show up as landscape. This could be an Exif related issue. Photos taken in landscape mode seem fine. I will provide more details as I work with this tool more to characterize what's really wrong.

**Comment by kechan** [comment]
Remark: This ignoring of Exif may be ok depending on context. I just tried the tool out, label a few boxes. In my jupyter notebook, I used this to open them as an numpy array

x = np.array(PIL.Image.open('my image.jpg'))

Since we are using x as raw data, and doesn't care about the intended display orientation, all are consistent and fine. I think the trouble come if you use some other tools, maybe imageio, that respects EXIF, then you may get an apparent mismatch in coordinates those captured by this tool in some circumstance. 

I don't think this is a bug with this tool, it is appropriately a data processing tool (part of a pipeline) and not concern with display and presentation.

**Comment by ryouchinsa** [comment]
RectLabel is an offline image annotation tool for object detection and segmentation.
Although this is not an open source program, with RectLabel you can remove the EXIF orientation flags from images and convert images to the front orientation. If necessary, you can rotate the image right/left by 90 degrees.
https://rectlabel.com/help#remove_exif_orientation_flags
