### ISSUE TITLE
边框错位

### ISSUE THREAD

**Issue by lijingrenya** [tzutalin/labelImg#401]
你好。
我在标注一张后，点击下一张，然后再返回到标注那张，会发现边框会偏移一个单位。
这种情况会在分辨率较低的图片上发生。
这个可以解决吗？

**Comment by tzutalin** [comment]
感謝你發現這個不容易發現的問題＠＠
但我最近沒時間看這個問題

**Comment by lijingrenya** [comment]
> 感谢你发现这个不容易发现的问题@@ 
> 但我最近没时间看这个问题

不好意思,还有一个问题~
在填写日语或者韩语，会提示编码错误。我在labelme中可以解决这个问题，但是在labelimg中我不太清楚应该在哪里修改或代码。
以上~

**Comment by tzutalin** [comment]
有ＥＲＲＯＲ嗎

**Comment by lijingrenya** [comment]
> 有ＥＲＲＯＲ嗎

Traceback (most recent call last):
  File "labelImg.py", line 850, in newShape
    generate_color = generateColorByText(text)
  File "C:\Users\Naver\Desktop\L\labelImg-master\l
ibs\lib.py", line 78, in generateColorByText
    s = str(ustr(text))
UnicodeEncodeError: 'gbk' codec can't encode chara
cter u'\uc544' in position 0: illegal multibyte se
quence
这是在输入韩文和保存xml的时候会发生。

**Comment by tzutalin** [comment]
Fix `输入韩文和保存xml的时候会发生`
https://github.com/tzutalin/labelImg/commit/eaac0314044b7aed9aa256349b23f908d398bb2e

**Comment by Anothorld** [comment]
你好， 我也遇到了一样的问题，边界框会发生偏移。请问你最后怎么解决的？

**Comment by hujunyao** [comment]
> 你好， 我也遇到了一样的问题，边界框会发生偏移。请问你最后怎么解决的
use float to calculate the coordinate and +0.5 .

**Comment by Anothorld** [comment]
> use float to calculate the coordinate and +0.5 .

thank you, can you tell me more details? where should I change in the code? I'm using Windows and anaconda.

**Comment by selrahc** [comment]
In my case, I changed the code in function of yoloLine2Shape() in yolo_io.py.
```
xmin = round(self.imgSize[1] * xmin)
xmax = math.ceil(self.imgSize[1] * xmax)
ymin = round(self.imgSize[0] * ymin)
ymax = round(self.imgSize[0] * ymax)
```
