### ISSUE TITLE
It is currently not possible to download the prebuild binaries

### ISSUE THREAD

**Issue by MichaelGuardian** [tzutalin/labelImg#402]
It's currently not possible to download the prebuild binaries for Linux and Windows.

Would be nice if you could reupload them. Maybe directly on GitHub in the Release tab?

**Comment by tzutalin** [comment]
Sure. Thanks for your information.I will try to use the release tab next time

**Comment by tzutalin** [comment]
Fix https://github.com/tzutalin/labelImg/releases
