### ISSUE TITLE
XML extension not written correctly if filename contains a dot (.)

### ISSUE THREAD

**Issue by krummrey** [tzutalin/labelImg#403]
I have a lot of training images that contain a dot (.) in the filename (firstname.name-number.jpg). 

Labelimg will not set the .xml extension correctly when reading or writing for those images.

**Comment by tzutalin** [comment]
https://github.com/tzutalin/labelImg/commit/6db1dd500d83e8367eaec045120dd7cd29bb9c3d
Fixed
