### ISSUE TITLE
Issue with Pascal vs yolo labeling

### ISSUE THREAD

**Issue by jcf0419** [tzutalin/labelImg#415]
Hello,

Just wanted to point out when using this tool for labeling for yolo - you have the following in your documentation.. I think it might need to be reworded. - that or you might look at updating the GUI to be more clear on what annotation file is being output on save.

The issue is on step 3 - is says.. click "PascalVOC" button to switch to yolo format.

""

> Steps (YOLO)
1. In data/predefined_classes.txt define the list of classes that will be used for your training.
2. Build and launch using the instructions above.
3. Right below "Save" button in toolbar, click "PascalVOC" button to switch to YOLO format.

""

If you click pascalVOC then the gui shows "yolo" - when in truth - the gui should really be showing pascalVOC when the files need to be saved in yolo annotiation. 

Maybe you could update it to use a check box instead? or a toggle in the gui?

I wont tell you the pain i just experienced.. however I'm sure you can image :)

**Comment by vdalv** [comment]
This is the first time I'm hearing a complaint about this part of the UI. I personally think the instructions and UI is fine. However, if more users share your sentiment, I'd be happy to look into some changes.

Also note: It's pretty straightforward to write a script that converts annotations from one format to another. For example: https://gist.github.com/vdalv/321876a7076caaa771d47216f382cba5


Best,

-Vlad
