### ISSUE TITLE
Can I batch convert PascalVOC to YOLO?

### ISSUE THREAD

**Issue by justshot** [tzutalin/labelImg#420]
I have label thousands of files in PascalVOC format. Now I want to convert PascalVOC to YOLO format. Is there a way to do it using labelimg?

**Comment by iraadit** [comment]
I'm interested too

**Comment by vdalv** [comment]
This is currently not possible with labelImg. However, I have written a Python script to get this done: https://gist.github.com/vdalv/321876a7076caaa771d47216f382cba5


Best,

-Vlad
