### ISSUE TITLE
"ctrl + n" hotkey  inconvenient  , whether can change the hotkey?

### ISSUE THREAD

**Issue by libeiUCAS** [tzutalin/labelImg#44]
hi, labelImg is an excenlent tool, i am enjoying it.
however ,to most peopel, our hand is not big,hotkey "ctrl+n" is not suitable,whether can  you change it ?

**Comment by tzutalin** [comment]
Hi @libeiUCAS ,
   Do you have other suggestion? I forget why I use 'ctrl + n'.

**Comment by tzutalin** [comment]
What about changing the hotkeys as below. Like playing shooting game
w: Create a bounding box
a : Next image
d: Previous image

**Comment by libeiUCAS** [comment]
hi @tzutalin ,
in fact , hotkey "ctrl+s" is unnecessary.it add extra work.  
as your suggestion:
    'w': Create a bounding box
    'd' : Next image  and not save 
    'a': Previous image 
    'Space':save and forward next image  (it will work faster and more convenient.)

**Comment by libeiUCAS** [comment]
@tzutalin  ，my understanding of hotkey  "next image " was wrong, it had forward and save function.
i change hotkeys as your suggestion:
'w': Create a bounding box
'd' : Next image and  save
'a': Previous image

**Comment by tzutalin** [comment]
Fix this issue on https://github.com/tzutalin/labelImg/commit/d9ba7b18d0e8f4d3f32a8b2972370c5d86187c1f

**Comment by mandarhs** [comment]
@tzutalin ,
is this update available for windows too ?

**Comment by tzutalin** [comment]
@mandarhs ,
  Sorry. I did not update this change for windows.

**Comment by mandarhs** [comment]
@tzutalin ,
Thanks for reply, eagerly await v1.3. My fingers and keyboard "n" buttons are about to crack :)

**Comment by tzutalin** [comment]
Hi @mandarhs ,
   Sorry for any inconvenience. I will build the new version next week. I am on vacation this week.

**Comment by mandarhs** [comment]
Hi @darrenl,

I eagerly await for the windows version. pls. share when you will finish.

With Thanks and Best regards,
Mandar SHENDGE

**Comment by tzutalin** [comment]
Hi @mandarhs ,
 Sorry for that. I will build it next week

**Comment by tzutalin** [comment]
Hi @mandarhs ,
 Try it.
http://tzutalin.github.io/labelImg/

**Comment by ajitpsakri** [comment]
> hi @tzutalin , in fact , hotkey "ctrl+s" is unnecessary.it add extra work. as your suggestion: 'w': Create a bounding box 'd' : Next image and not save 'a': Previous image 'Space':save and forward next image (it will work faster and more convenient.)

Space is not saving and moving next, any solution? My version - Windows_v1.8.0
