### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by jorlogicus** [tzutalin/labelImg#444]
Hello @tzutalin,  today while exploring GitHub looking for interesting projects found yours and I would love to contribute by designing a logo for it. I'm a designer in development and an open source enthusiast. We would be working together to create the design that fits best. Of course it's totally free and you can quit whenever you want. In case you agree, please let me know any preferences you may have about colours, shapes, etc you may have.

Kind regards.

**Comment by tzutalin** [comment]
Sounds good. I don't have any preference on this. Do whatever you think it is suitable for this tool

**Comment by jorlogicus** [comment]
Hello again! here I have a few concepts I just made, just wanted to know your opinion about them

![](https://cdn.discordapp.com/attachments/451449919648169984/548930562321154059/1Recurso_3.png)

**Comment by tzutalin** [comment]
I prefer the top left one. But why does the mountain mean? Also, it will be better if the bounding box is a rectangle instead of a circle.

**Comment by michaelizergit** [comment]
They are meant (the mountains) to represent the concept of "images".

I'm working on a few more sketches, but if you already have your choice. And also if you want to add/modify anything on the one you chose (apart from changing the bounding box), let me know as well. :blush:

**Comment by jorlogicus** [comment]
They are meant (the mountains) to represent the concept of "images".

I'm working on a few more sketches, but if you already have your choice. And also if you want to add/modify anything on the one you chose (apart from changing the bounding box), let me know as well.

**Comment by jorlogicus** [comment]
![](https://cdn.discordapp.com/attachments/451449919648169984/549333058835185665/Recurso_4.png)
 And look at these:

![](https://cdn.discordapp.com/attachments/451449919648169984/549333030137757711/Recurso_5.png)
What do you think?

**Comment by jorlogicus** [comment]
Hello @tzutalin, any updates on this issue?

**Comment by jorlogicus** [comment]
Great, I will then create and upload the files on google drive so you can have total control of your logo and proceed to create a pull request with the main ones if you agree.

**Comment by jorlogicus** [comment]
Hello there, I made the pull request ([#461](https://github.com/tzutalin/labelImg/pull/461)) and also uploaded all the necessary files to [Google Drive](https://drive.google.com/open?id=1T58aQXzEZayvHdjlY4NzmFEjytpE9F62) so you can access them whenever you want and make any modifications in the future. It was a real pleasure to design this logo for your project, have a nice week and keep up the great work!

**Comment by tzutalin** [comment]
Hi,
Thanks. I will check it by the end of this week.

**Comment by tzutalin** [comment]
Can you help update the title to `labelImg` instead of `labelimg` in the image? That will be consistent to the package name?

**Comment by tzutalin** [comment]
I submitted and made requisite amendments for this like creating svg and icns for your logo.

**Comment by jorlogicus** [comment]
The Google Drive folder with all necessary files was updated with a new font which differentiates the "I" in LabelImg and it's now uppercase. https://drive.google.com/drive/u/2/folders/1BEXJBscoQ37kVztOzpcK1-eeMfU0Xg70

**Comment by tzutalin** [comment]
Thanks

**Comment by elPartizan** [comment]
Hi! Wнy LabelImg app.icns (Mac os X) not displayed?
