### ISSUE TITLE
where is the origin of coordinates?

### ISSUE THREAD

**Issue by russell-li** [tzutalin/labelImg#468]
when i mark the annotations in the image, where is the origin coordinate( the point that x=0 and y=0) of the annotations?
i am confused, anyone can help me?

**Comment by Wanderish** [comment]
Hey @russell-li, the origin coordinate is the top-left corner of the bounding box (i.e., when you click on the image to draw the bounding box).
Let me know if that solves your doubt.
Cheers!

**Comment by russell-li** [comment]
Hey @Wanderish , thanks for your answer.
I think the origin coordinate is the top-left corner of the img that we draw the bounding box,  I tested and verified that by drawing the bounding box on the top-left corner of the figure.

**Comment by Wanderish** [comment]
Glad you got it!
