### ISSUE TITLE
Older version prior to commits work. I think for the newest pull I made for a different computer, I am getting an error regarding resources in lib. It fails to import for the the latest pull. 

### ISSUE THREAD

**Issue by ekuang3** [tzutalin/labelImg#473]
- **OS:**
- **PyQt version:**

**Comment by tzutalin** [comment]
According to the latest change, you have to call `make`, `make qt4py2`, or `make qt5py3`

**Comment by ekuang3** [comment]
Okay thank you very much! I am doing this in anaconda and will try this now.
