### ISSUE TITLE
Issue installing in windows10/Python 3.7/ No module named 'libs.resources'

### ISSUE THREAD

**Issue by newmluser** [tzutalin/labelImg#475]
Steps done:
pip install PyQt5
Requirement already satisfied: PyQt5 in xxx\lib\site-packages (5.12.2)
Requirement already satisfied: PyQt5_sip<13,>=4.19.14 in xxx\lib\site-packages (from PyQt5) (4.19.17)

pyrcc5 -o resources.py resources.qrc

python labelImg.py
Traceback (most recent call last):
  File "labelImg.py", line 29, in <module>
    from libs.resources import *
ModuleNotFoundError: No module named 'libs.resources'

I have seen multiple links and followed the steps. still I am getting the same issue.
I am using anaconda/Python

**Comment by Chetchaiyan** [comment]
I found same error, and solved by install qt5 as follow
```
sudo apt-get install pyqt5-dev-tools
sudo pip3 install -r requirements/requirements-linux-python3.txt
make qt5py3
```

**Comment by newmluser** [comment]
Can you please help me with windows command because I did execute
>pip install pyqt5
even than getting the same error

**Comment by ChunlinYu** [comment]
coppy resources.py  to libs

**Comment by Darshan2701** [comment]
Please try this command from labelImg directory pyrcc5 -o libs/resources.py resources.qrc

**Comment by newmluser** [comment]
Thank you Darshan. This Fixed it.

**Comment by tzutalin** [comment]
If you download the latest code on windows, u got to run  pyrcc5 -o libs/resources.py

**Comment by isalirezag** [comment]
im using ubuntu 16.04
I still see the  :
`pyrcc5 -o libs/resources.py resources.qrc`
any suggestion?
![image](https://user-images.githubusercontent.com/12434910/68796283-96fb6780-0620-11ea-9405-67a7f60f74fc.png)

**Comment by Erik-Banik** [comment]
> 
> 
> Please try this command from labelImg directory pyrcc5 -o libs/resources.py resources.qrc

Thank you! :-)

**Comment by ProZoom** [comment]
> coppy resources.py to libs

where is the reources.py？

**Comment by AguRodCan** [comment]
> > coppy resources.py to libs
> 
> where is the reources.py？

Its created when you run the "pyrcc5 -o libs/resources.py resources.qrc"

I had trouble making it work as its in the READ.ME

try doing it with the complear path.

C:\Python35\Scripts\pyrcc5 -o C:\Desktop\labelImg\libs\resources.py

[https://stackoverflow.com/questions/58140305/labelimg-pyrcc5-is-not-recognized-as-an-internal-or-external-command](url)

**Comment by fawadta** [comment]
> pyrcc5

Thanks. This one worked :)
