### ISSUE TITLE
about Next/Prev Image

### ISSUE THREAD

**Issue by kevinisbest** [tzutalin/labelImg#5]
Hi Lin:
I have many picture named frame000.jpg to framexxx.jpg in same directory.
When i running labelImg.py and open Dir.
 After labeling frame000.jpg i want to next pic but next pic showed isn't frame001.jpg .
Does any solution about it?

**Comment by tzutalin** [comment]
Hi @kevinisbest ,
  Really? I didn't meet the problem. I think sorting the list of image list by name can resolve your image

**Comment by kevinisbest** [comment]
![image](https://cloud.githubusercontent.com/assets/10130649/11979905/d42a04ea-a9d1-11e5-973a-64b55c72eb7b.png)

Under my directory I've sort these pictures by name, but the problem still exist

**Comment by tzutalin** [comment]
@kevinisbest , 
I means I need to sort by name when loading the pictures in this application.

**Comment by whcjb** [comment]
林，你好
因为图片名需要与标注的xml文件名保持一致，然而在使用时却不是很方便获取文件名（需要回到图片文件夹重新确认）。能否改进使得在保存的时候自动填充图片所使用的文件名呢？或者在界面的标签处能注明图片文件名？
谢谢！

**Comment by kevinisbest** [comment]
I wrote a python program to rename all .xml
because after you labeling a picture,the picture name has been record in the xml file
so you can save xml in romdon name
so what i do is fetch the file name data in .xml and rename all xml files.
see this:
https://github.com/DannyHuangXD/BlindGuidingAssistant/commit/400fd27b6288c3899a35348a906ba101b9c31f3d

**Comment by whcjb** [comment]
@kevinisbest  that's great！
but the link cannot work, please give us a new one. Thank you!

**Comment by whcjb** [comment]
@kevinisbest  that's great! but the link cannot find ,can you give a new one? thank you!

**Comment by tzutalin** [comment]
Hi @whcjb  and @kevinisbest ,
Please pull again. I submit a patch
https://github.com/tzutalin/labelImg/commit/dd56234989d51228f87f9dbb905d326b2105ec35
