### ISSUE TITLE
pyrcc5: No such file or directory

### ISSUE THREAD

**Issue by enyangxxx** [tzutalin/labelImg#506]
admins-MacBook-Pro:labelImg admin$ make qt5py3
    pyrcc5 -o libs/resources.py resources.qrc
    make: pyrcc5: No such file or directory
    make: *** [qt5py3] Error 1

- **OS:** Mac OS Mojave 10.14.6
- **PyQt version:** 5

**Comment by enyangxxx** [comment]
solved this issue by using brew install pyqt5 instead of pip3

**Comment by tzutalin** [comment]
Good
