### ISSUE TITLE
How to change GUI color

### ISSUE THREAD

**Issue by atticcas** [tzutalin/labelImg#51]
Hi, 
      I am using your amazing tool for some picture all with dark background. I was wondering if I can change the background to black. so when I "scroll" through all the images, it won't blink so much. 
Thank you!

**Comment by tzutalin** [comment]
@atticcas ,
  In master branch, I have added a draft version, but there still exists some issues.

**Comment by atticcas** [comment]
Thanks!

**Comment by TJ-Yusuke** [comment]
@tzutalin 
> In master branch, I have added a draft version, but there still exists some issues.

Could you inform me of the place where you added?

I'm considering adding a dark theme.

**Comment by tzutalin** [comment]
It can be added when launching the app to set a theme.
https://stackoverflow.com/questions/48256772/dark-theme-for-qt-widgets

it will be great if you can give a try and submit a PR

Thanks

**Comment by TJ-Yusuke** [comment]
@tzutalin 
All right, I'm gonna try and submit a PR.
I appreciate your informing a helpful information.
Thank you.
