### ISSUE TITLE
Question: how to fix  "ModuleNotFoundError: No module named 'libs.resources' "

### ISSUE THREAD

**Issue by javadba** [tzutalin/labelImg#510]
I am trying to run 
       `python labelImg.py`

and it gives the error message in the title

`ModuleNotFoundError: No module named 'libs.resources'`

What is supposed to be done?  I am on MacOs Mojave and using PyQt5

**Comment by yuta-imai** [comment]
@javadba I also ran into the same issue, using Mac and MyQt5, and I could fix the issue with referring to https://github.com/tzutalin/labelImg/issues/475

**Comment by javadba** [comment]
Thx v much for that reference.  The following band-aid from that issue fixed for me:

  `pyrcc5 -o libs/resources.py resources.qrc`

**Comment by harbidel** [comment]
Mine still not working,  this is what have been getting;
Traceback (most recent call last):
  File "labelImg.py", line 30, in <module>
    from libs.resources import *
ModuleNotFoundError: No module named 'libs.resources'

am using windows 10

**Comment by harbidel** [comment]
Thanks
have been able to solve the error on windows,
i used pypl
pip install labelImg on cmd
run labelImg
boom... it runs

**Comment by suresh88** [comment]
I have the same issue. I am using Ubuntu and this is my trace back:

Traceback (most recent call last):
  File "labelImg.py", line 30, in <module>
    from libs.resources import *
ModuleNotFoundError: No module named 'libs.resources'.

Any help will be greatly appreciated.

**Comment by trinhthanhhoakg** [comment]
Tks mọi người
em đã thử nhiều cách và đã cài được
python3
download labelImg -> pip3 install lebelImg -> python labelImg.py -> bị lỗi "ModuleNotFoundError: No module named 'libs.resources'"-> pyrcc5 -o libs/resources.py resources.qrc -> python labelImg.py -> ok :D :D

**Comment by 78-t0b1** [comment]
Thanx @trinhthanhhoakg. It works perfectly. For my English speaking friends. It's like follows.

- You should have python3.
- clone **git@github.com:tzutalin/labelImg.git** -> **pip3 install lebelImg** -> **python labelImg.py** 
If it works you are good to go.

- Else you will get error  
 **Traceback (most recent call last):
  File "labelImg.py", line 30, in <module>
    from libs.resources import *
ModuleNotFoundError: No module named 'libs.resources'**

- Then execute **"pyrcc5 -o libs/resources.py resources.qrc OR pyrcc5 -o libs/resources.py resources.qrc OR both."**

- Again try **"python labelImg.py"**

**Comment by jiapei100** [comment]
@78-t0b1 
Thanks .... working now...

**Comment by ashish23jan** [comment]
> Thanx @trinhthanhhoakg. It works perfectly. For my English speaking friends. It's like follows.
> 
> * You should have python3.
> * clone **[git@github.com](mailto:git@github.com):tzutalin/labelImg.git** -> **pip3 install lebelImg** -> Go to cloned project folder -> **python labelImg.py**
>   If it works you are good to go.
> * Else you will get error
>   **Traceback (most recent call last):
>   File "labelImg.py", line 30, in 
>   from libs.resources import *
>   ModuleNotFoundError: No module named 'libs.resources'**
> * Then execute **"pyrcc5 -o libs/resources.py resources.qrc" OR "pyrcc5 -o libs/resources.py resources.qrc OR both."**
> * Again try **"python labelImg.py"**

Working fine ....thank you

**Comment by Aarshiya1** [comment]
i am getting this issue a lot. how can i solve this.
Traceback (most recent call last):
File "labelImg.py", line 30, in
from libs.resources import *
ModuleNotFoundError: No module named 'libs.resources'

i am using windows 10.  help needed

**Comment by tzutalin** [comment]
> i am getting this issue a lot. how can i solve this.
> Traceback (most recent call last):
> File "labelImg.py", line 30, in
> from libs.resources import *
> ModuleNotFoundError: No module named 'libs.resources'
> 
> i am using windows 10. help needed

Do you run ?
'pyrcc5 -o libs/resources.py resources.qrc' or 'make qt5py3'

**Comment by xelandar** [comment]
> 
> 
> Thanks
> have been able to solve the error on windows,
> i used pypl
> pip install labelImg on cmd
> run labelImg
> boom... it runs

This one worked for me.

You just run in command prompt **pip install labelImg** and **labelImg** after that. labelImg opens!

**Comment by Aarshiya1** [comment]
> > i am getting this issue a lot. how can i solve this.
> > Traceback (most recent call last):
> > File "labelImg.py", line 30, in
> > from libs.resources import *
> > ModuleNotFoundError: No module named 'libs.resources'
> > i am using windows 10. help needed
> 
> Do you run ?
> 'pyrcc5 -o libs/resources.py resources.qrc' or 'make qt5py3'

yes i run that but still it says the module not found. i tried installing pypI but it says could not find the version that statisfies the packages. what should i do?

**Comment by alfavat** [comment]
just copy the resources.py file to libs filder

**Comment by Kashif571** [comment]
> @javadba I also ran into the same issue, using Mac and MyQt5, and I could fix the issue by referring to #475

Thank you so much. It works for me. The issue was I was misspelling this "pyrcc5 -o libs/resources.py resources.qrc".

**Comment by StankovskiA** [comment]
> 
> 
> Thx v much for that reference. The following band-aid from that issue fixed for me:
> 
> `pyrcc5 -o libs/resources.py resources.qrc`

No idea what this does, but it works :)

**Comment by hyn34** [comment]
> Tks mọi người
> em đã thử nhiều cách và đã cài được
> python3
> download labelImg -> pip3 install lebelImg -> python labelImg.py -> bị lỗi "ModuleNotFoundError: No module named 'libs.resources'"-> pyrcc5 -o libs/resources.py resources.qrc -> python labelImg.py -> ok :D :D

Thanks! Good! Now it works well!

**Comment by hyn34** [comment]
> Tks mọi người
> em đã thử nhiều cách và đã cài được
> python3
> download labelImg -> pip3 install lebelImg -> python labelImg.py -> bị lỗi "ModuleNotFoundError: No module named 'libs.resources'"-> pyrcc5 -o libs/resources.py resources.qrc -> python labelImg.py -> ok :D :D

Thanks!

**Comment by RAravindDS** [comment]
> pyrcc5 -o libs/resources.py resources.qrc

Thankyou so much worked for me

**Comment by Basuki74** [comment]
I have run 'pyrcc5 -o libs/resources.py resources.qrc' or 'make qt5py3' but still ''pyrcc5' is not recognized as an internal or external command,
operable program or batch file.

**Comment by kwlaial** [comment]
Reminded that you are in labelImg directory before you run pyrcc5 -o libs/resources.py resources.qrc and python labelImg.py
i.e. cd labelImg

**Comment by IndeeraWE** [comment]
>pyrcc5 -o libs/resources.py resources.qrc
'pyrcc5' is not recognized as an internal or external command,
operable program or batch file.
help me windows 10

**Comment by mostafa-orban** [comment]
> > Thanks
> > have been able to solve the error on windows,
> > i used pypl
> > pip install labelImg on cmd
> > run labelImg
> > boom... it runs
> 
> This one worked for me.
> 
> You just run in command prompt **pip install labelImg** and **labelImg** after that. labelImg opens!

it works for me windows 10 besides only one comment dont run labellmg py file after  > > pip install labelImg on cmd
just write labellmg in the cmd it will open sucessfully

**Comment by subhendu-majumder** [comment]
For me following solves the error

pip install pyqt5-tools 
pyrcc5 -o libs/resources.py resources.qrc

**Comment by Selva-TS-cube** [comment]
> * pyrcc5 -o libs/resources.py resources.qrc

Thank you so much it's working 😍

**Comment by ibtehajali67** [comment]
> Thx v much for that reference. The following band-aid from that issue fixed for me:
> 
> `pyrcc5 -o libs/resources.py resources.qrc`

thank you its work for me

**Comment by christina-cyber** [comment]
> 

thank you a lot

**Comment by harbidel** [comment]
* Make sure you have PyQt5 installed:
Open a terminal and run the following command to install PyQt5 if you haven't already:
pip install pyqt5

* Clone the labelImg repository (if you haven't already):
If you don't have the labelImg script, you can clone the repository from GitHub using the following command:
git clone https://github.com/tzutalin/labelImg.git

* Navigate to the labelImg directory:
Use the cd command in the terminal to change to the labelImg directory:
cd labelImg

* Try running the script again:
Now, attempt to run the labelImg.py script:
python labelImg.py
