### ISSUE TITLE
No module named 'PyQt5'

### ISSUE THREAD

**Issue by henbucuoshanghai** [tzutalin/labelImg#517]
- **OS:**
- **PyQt version:**

**Comment by henbucuoshanghai** [comment]
in ubuntu,  make pyqt5 ,with error 
pyrcc5 -o libs/resources.py resources.qrc
/homeanaconda3/bin/python: Error while finding module specification for 'PyQt5.pyrcc_main' (ModuleNotFoundError: No module named 'PyQt5')
Makefile:24: recipe for target 'qt5py3' failed
make: *** [qt5py3] Error 1

**Comment by HumairaFasih** [comment]
what solution did you find to this issue?
