### ISSUE TITLE
make all fails on OSX

### ISSUE THREAD

**Issue by raviv** [tzutalin/labelImg#52]
```
$ make all

pyrcc4 -o resources.py resources.qrc
make: pyrcc4: No such file or directory
make: *** [resources.py] Error 1
```

Thanks :)

**Comment by tzutalin** [comment]
Had you installed qt already?

**Comment by raviv** [comment]
Thanks for the quick response @tzutalin :)
I figured out brew installed by default qt5 and your code is for qt4.

**Comment by tzutalin** [comment]
Hi @raviv ,
  In fact, @rflynn has implemented the version which supported qt5 on mac OS. Maybe you can refer to the travis file and understand how to build it? 
https://github.com/tzutalin/labelImg/blob/master/.travis.yml#L154

**Comment by tornadomeet** [comment]
@tzutalin @raviv so how to fix this? can i change all the code from qt4 to qt5 ?

**Comment by raviv** [comment]
@tornadomeet I think I changed the code to qt5 but not sure. I ended up writing my own tailor made labeling app in angular.

**Comment by tornadomeet** [comment]
@raviv  thanks.  i cannot build it on my mac os 10.12.3, when run `python3 labelImg.py` it will output: ```libc++abi.dylib: terminating with uncaught exception of type NSException```

**Comment by WilliamCarlos** [comment]
Any updates on how to fix this? I'm having the same issue using pyqt v5.8.2

**Comment by Himanshugahlot** [comment]
** pyrcc4** Directory is not on your system thats the reason its throwing this errors 
On Mac you can make it after installing
`brew install cartr/qt4/pyqt@4`

**Comment by Himanshugahlot** [comment]
**pyrcc4** Directory is not present on your system thats the reason its throwing this errors
On Mac you can make it after installing
`brew install cartr/qt4/pyqt@4`

**Comment by vidalbenjoe** [comment]
Thank you @Himanshugahlot  it works!
