### ISSUE TITLE
pyrcc5 -o libs/resources.py resources.qrc

### ISSUE THREAD

**Issue by isalirezag** [tzutalin/labelImg#522]
im using ubuntu 16.04
I still see the  :
`pyrcc5 -o libs/resources.py resources.qrc`
any suggestion?
![image](https://user-images.githubusercontent.com/12434910/68796283-96fb6780-0620-11ea-9405-67a7f60f74fc.png)

**Comment by bsridatta** [comment]
It is no problem. Run "python3 labelImg.py" it should work
