### ISSUE TITLE
Can't open annotations with more than 6 boxes

### ISSUE THREAD

**Issue by zuphilip** [tzutalin/labelImg#54]
We are using the prebuilt files (v1.2.1) for Windows and when entering more than 6 boxes than the annotations cannot be opened again. Everything looks fine for one up to 6 boxes but when a page contains 7 or more boxes then I cannot open the annotation again. Actually the following errors shows up in the command line window:

```
Traceback (most recent call last):
  File "<string>", line 919, in openNextImg
  File "<string>", line 741, in loadFile
  File "<string>", line 1078, in loadPascalXMLByFilename
  File "Z:\home\darrenl\tools\labelImg\build-tools\build\labelImg\out00-PYZ.pyz\
pascal_voc_io", line 115, in __init__
  File "Z:\home\darrenl\tools\labelImg\build-tools\build\labelImg\out00-PYZ.pyz\
pascal_voc_io", line 131, in parseXML
  File "Z:\home\darrenl\tools\labelImg\build-tools\build\labelImg\out00-PYZ.pyz\
xml.etree.ElementTree", line 1182, in parse
  File "Z:\home\darrenl\tools\labelImg\build-tools\build\labelImg\out00-PYZ.pyz\
xml.etree.ElementTree", line 657, in parse
  File "parser.pxi", line 1166, in lxml.etree._FeedParser.close (src/lxml/lxml.e
tree.c:76950)
  File "parser.pxi", line 556, in lxml.etree._ParserContext._handleParseResult (
src/lxml/lxml.etree.c:71680)
  File "parser.pxi", line 645, in lxml.etree._handleParseResult (src/lxml/lxml.e
tree.c:72614)
  File "parser.pxi", line 585, in lxml.etree._raiseParseError (src/lxml/lxml.etr
ee.c:71955)
lxml.etree.XMLSyntaxError: internal error, line 6, column 15
```

I don't have any path beginning with "Z:\home\darrenl\tools\labelImg".

**Comment by zuphilip** [comment]
Here is a minimal example with an image and annotations (created with labelImg). I can open the image, but not the annotations with labelImg on windows. I tried also v1.2.2.

[andp200910361.png](https://cloud.githubusercontent.com/assets/5199995/23092581/40139d26-f5ce-11e6-88cd-31e31fb7a4c5.png)

[andp200910361.xml.txt](https://github.com/tzutalin/labelImg/files/784955/andp200910361.xml.txt) (added `.txt` to upload it here)

(When you delete by hand one of the boxes, then it will work.)

**Comment by tzutalin** [comment]
@zuphilip ,
  That's interesting. It won't happen on ubuntu. I guess that is the issue regard window lxml lib

**Comment by zuphilip** [comment]
If I see this correctly [in these lines](https://github.com/tzutalin/labelImg/blob/master/build-tools/envsetup.sh#L50-L52) than you are using a very old version 2.3 of `lxml` for the windows build. Any reason not to take the latest 3.7.3 build from https://pypi.python.org/pypi/lxml/3.7.3 ? Which version do you have on Ubuntu?

**Comment by tzutalin** [comment]
@zuphilip ,
  I think it is because I only find the lxml binary with 2.3 when I wrote the script. I will try to use 3.7.3 to build again. Thanks for your shared link.

**Comment by tzutalin** [comment]
@zuphilip ,
 lxml3.7.3 works. Fix it on https://github.com/tzutalin/labelImg/commit/43e62708d4e657af2993638c01d147013a6632a6

Also, I compiled it again for Windows with lxml3.7.3.  
https://raw.githubusercontent.com/tzutalin/LabelImg/gh-pages/windows/windows_v1.2.2.zip

**Comment by zuphilip** [comment]
@tzutalin Thank you very much! My first test with the new `zip` looks good. 👍
