### ISSUE TITLE
labelImg crashing on windows

### ISSUE THREAD

**Issue by kushalj001** [tzutalin/labelImg#552]
I am using the pre-built binaries for windows from [here ](https://tzutalin.github.io/labelImg/), version 1.8.0. Everything was working perfectly until yesterday. Today the app is crashing on opening. The terminal pops up and crashes immediately.

**Comment by irem-ozturkcu** [comment]
> [Buradan](https://tzutalin.github.io/labelImg/) pencereler için önceden oluşturulmuş ikili dosyaları, sürüm 1.8.0 kullanıyorum . Düne kadar her şey mükemmel çalışıyordu. Bugün uygulama açılışta çöküyor. Terminal açılır ve hemen çöker.

hello, i am having the same problem. How did you solve it?
