### ISSUE TITLE
Why LebelImg annotated bounding boxes moves to a new position

### ISSUE THREAD

**Issue by mehedi-tut** [tzutalin/labelImg#561]
The annotation was done with LebelImg in images of gear where there is a scratch. Then the bounding boxes move to another position once I finish annotation. Moreover, I see annotated bounding boxes to images that I did not do annotation. Why is this happening, I could not find out the reason. Could anyone please tell why these bounding boxes move to a new position?

**Comment by unnamed7** [comment]
I was struggling with the same problem and I think I've just found the cause.

In the YOLOWriter class in yoloio_py, saved parameters namely centreX,Y, W and H are calculated from the bounding box position and truncated to 6 digits below 0. Then on load, the written parameter will be used to get a new bounding box coordinates. The truncated numbers below the 6 digits often cause the displacement. 
I tried to change it to 16, and seems this problem is fixed.

```
        for box in self.boxlist:
            classIndex, xcen, ycen, w, h = self.BndBox2YoloLine(box, classList)
            # print (classIndex, xcen, ycen, w, h)
            out_file.write("%d %.6f %.6f %.6f %.6f\n" % (classIndex, xcen, ycen, w, h))

```

Changed the last line to;

`
out_file.write("%d %.6f %.6f %.6f %.6f\n" % (classIndex, xcen, ycen, w, h))
`

**Comment by CodeJjang** [comment]
@unnamed7 I can confirm they are changed as well in the Pascal VOC dataset, I was breaking my head why every time I swipe photos I get a window asking me if I want to save new changes...
Though I haven't changed anything.
So I compared the output XMLs and found out boxes are being changed

**Comment by mehedi-tut** [comment]
> I was struggling with the same problem and I think I've just found the cause.
> 
> In the YOLOWriter class in yoloio_py, saved parameters namely centreX,Y, W and H are calculated from the bounding box position and truncated to 6 digits below 0. Then on load, the written parameter will be used to get a new bounding box coordinates. The truncated numbers below the 6 digits often cause the displacement.
> I tried to change it to 16, and seems this problem is fixed.
> 
> ```
>         for box in self.boxlist:
>             classIndex, xcen, ycen, w, h = self.BndBox2YoloLine(box, classList)
>             # print (classIndex, xcen, ycen, w, h)
>             out_file.write("%d %.6f %.6f %.6f %.6f\n" % (classIndex, xcen, ycen, w, h))
> ```
> 
> Changed the last line to;
> 
> `out_file.write("%d %.16f %.16f %.16f %.16f\n" % (classIndex, xcen, ycen, w, h))`

Thank you for sharing the information. So, how about PascalVOC dataset. I did not find something like that in pascal_voc_io.py script.

**Comment by mehedi-tut** [comment]
> @unnamed7 I can confirm they are changed as well in the Pascal VOC dataset, I was breaking my head why every time I swipe photos I get a window asking me if I want to save new changes...
> Though I haven't changed anything.
> So I compared the output XMLs and found out boxes are being changed

I am also struggling with the same problem. But for "save new changes" issue, you can use autosave option from view of labelImg GUI.

**Comment by mehedi-tut** [comment]
I understood the reason. In my case, some of the **filenames in different image folders were the same** and I put the all XML file in a single folder. That's why when I go the files to be annotated has the bounding boxes that I already annotated earlier.   Thanks everyone.

**Comment by CodeJjang** [comment]
> > @CodeJjang  I can confirm they are changed as well in the Pascal VOC dataset, I was breaking my head why every time I swipe photos I get a window asking me if I want to save new changes...
> > Though I haven't changed anything.
> > So I compared the output XMLs and found out boxes are being changed
> 
> I am also struggling with the same problem. But for "save new changes" issue, you can use autosave option from view of labelImg GUI.
Auto save is not an option, because LabelImg DO incur changes in the XML. Small pixel level changes, but it's false changes as I didn't do anything.
It's definitely a bug...

**Comment by unnamed7** [comment]
I don't understand why this has been closed as the original issue reported is not fixed or reviewed.
