### ISSUE TITLE
Unintuitive vertex movement for point outside canvas

### ISSUE THREAD

**Issue by adwaitbhope** [tzutalin/labelImg#587]
While annotating an image, if you go outside the image boundary, the box shape changes rather unintuitively. It uses the projection of the outside point on the edges of the image.

This behaviour is illustrated here:
![original](https://user-images.githubusercontent.com/32306983/81099488-a05af200-8f28-11ea-9d36-413496daa57e.gif)

It seems odd that the value of x axis changes when you're dragging your mouse through y axis (and vice versa).

**Comment by tzutalin** [comment]
Not sure if it is good as I don't try it out. Let's merge first to see the feedback from others. Thanks
