### ISSUE TITLE
In the xml file, the value of width and height are both zero.

### ISSUE THREAD

**Issue by Jmx5200** [tzutalin/labelImg#59]
I cloned the newest version of labelImg in Ubuntu 16.04, I tried to label my pictures, but found the value of width and height are both zero in xml file. need help, thanks!

```
 <annotation>
<folder>mx</folder>
<filename>timg</filename>
<path>/home/mx/timg.xml</path>
<source>
<database>Unknown</database>
</source>
<size>
<width>0</width> #here
<height>0</height> #here
<depth>3</depth>
</size>
<segmented>0</segmented>
<object>
<name>person</name>
<pose>Unspecified</pose>
<truncated>0</truncated>
<difficult>0</difficult>
<bndbox>
<xmin>189</xmin>
<ymin>136</ymin>
<xmax>762</xmax>
<ymax>573</ymax>
</bndbox>
</object>
</annotation>
```

**Comment by tzutalin** [comment]
All of images has the same problem?

**Comment by Jmx5200** [comment]
@tzutalin yes, I tested about 20 pictures, formal is png and jpg, all the picture have the same problem. and other people have too.

**Comment by tzutalin** [comment]
Can you let me know your env?
python2 or python 3?
Qt4 or Qt5?

**Comment by zuphilip** [comment]
The path information contains for my annotation files the path to the picture file (ending with `png` or something similar). But you have

```xml
<path>/home/mx/timg.xml</path>
```

**Comment by Jmx5200** [comment]
@tzutalin I guess is py2 and qt4. I tested different version of your project, I cloned the code again, then `git checkout py2-qt4`, it is ok. and I `git checkout master`, it is wrong, and I think what zuphilip said is important. <path>/home/mx/timg.xml</path> is abnormal.  It should be <path>/home/mx/timg.png</path>.

**Comment by Jmx5200** [comment]
@zuphilip thanks for your observation.I also wonder why the new version has this bug, and the older version(branch py2-qt4) is ok.

**Comment by tzutalin** [comment]
Hi ,
Thanks. I think the recent two change caused the issue. I will fix it. Sorry for any inconvenience.

**Comment by tzutalin** [comment]
Fix on https://github.com/tzutalin/labelImg/commit/34420d40534be732e3ffcd34765f6c9ee0e83f3c
