### ISSUE TITLE
about the annotation of gray image

### ISSUE THREAD

**Issue by graceywh** [tzutalin/labelImg#6]
Can this  tool be used in the annotation of gray image?  When i use it for the gray image annotation i meet some problem and i can't save the label.

**Comment by tzutalin** [comment]
Could you provde me with your test images?

**Comment by graceywh** [comment]
Thanks, i have solved the problem.

**Comment by graceywh** [comment]
By the way it is not very convenient without default file name item when i try to save the annotation.

**Comment by tzutalin** [comment]
Hi @graceywh,
What do you mean inconvenient without default file name item? Have you tried to assign default saved dir? If you assign the default saved directory, the tool will have a default file name for annotion file.

**Comment by graceywh** [comment]
Thank you! I assign the default saved directory and then i have the default file name.
