### ISSUE TITLE
KeyError: <libs.shape.Shape object at 0x7f14c4bd6710>

### ISSUE THREAD

**Issue by Totoro-wen** [tzutalin/labelImg#605]
When I run labelimg.py, I'm going to have a couple of flashbacks. I followed the installation instructions and my device is running Anconda on Ubuntu '16.04. Error is as follows：
```
(labelImg) aibc@aibc:~/labelimg/labelImg-master$ python labelImg.py 
Image:/home/aibc/Desktop/yu/Data/15_10916.jpg -> Annotation:/home/aibc/Desktop/yu/Anno/15_10916.xml
Image:/home/aibc/Desktop/yu/Data/15_10964.jpg -> Annotation:/home/aibc/Desktop/yu/Anno/15_10964.xml
Image:/home/aibc/Desktop/yu/Data/15_10967.jpg -> Annotation:/home/aibc/Desktop/yu/Anno/15_10967.xml
Traceback (most recent call last):
  File "labelImg.py", line 725, in shapeSelectionChanged
    self.shapesToItems[shape].setSelected(True)
KeyError: <libs.shape.Shape object at 0x7f14c4bd6710>
Aborted (core dumped)
```
thanks a lot.

**Comment by hevinyu** [comment]
I have the same problem

**Comment by Guneetkaur03** [comment]
Even I have the same problem. 
Any solutions yet?

**Comment by iFlyyyy** [comment]
This error seems to happen when I click on an area that doesn't have a box. So the solution is don't click on an area without a box if you don't want to create box

**Comment by breunigs** [comment]
Steps to reproduce (using 39ecb789a7476bd25ef9bb7f41cde3c03f7b5244):
1. draw a box
2. select the box
3. hover over one of the corners as if you want to resize the box (no click needed)
4. press DEL to delete the box
5. left click on the canvas

**Comment by tzutalin** [comment]
Thanks @pletnes who fixed it
