### ISSUE TITLE
cant use in ubuntu 16.04

### ISSUE THREAD

**Issue by NYcleaner** [tzutalin/labelImg#61]
cant use in ubuntu 16.04,  i download linux1.2.2 and unzip  , then click the labelImg ,  but without  any  reaction

**Comment by hejiangda** [comment]
You can try sudo ./labelImg
I don't know why it can only run under root.

**Comment by tzutalin** [comment]
I think it is caused by me because I built the binary under root. How about change the owner using chown?

**Comment by guochaoxxl** [comment]
使用超级用户，也就是root执行命令chmod 777 filename

At 2017-03-15 16:33:09, "darrenl" <notifications@github.com> wrote:


I think it is caused by me because I built the binary under root. How about change the owner using chown?

**Comment by gyang1011** [comment]
I also have issue to run it. Here is the error I got:

Segmentation fault (core dumped)

**Comment by NYcleaner** [comment]
thanks for your's  enthusiasm

**Comment by SrikanthVelpuri** [comment]
yes it is not working in linux 16.04
Segmentation fault (core dumped)
