### ISSUE TITLE
Cann't process .jpg image, but work well for .png

### ISSUE THREAD

**Issue by waynesuzq** [tzutalin/labelImg#62]
Every time I choose a .jpg file, it pops up an error message:

> Error opening file
> Make sure /Users/zqsu/Documents/apps/labelImg/demo/demo3.jpg is a valid image file.

I tried my own image and the demo image, all got the same error, but .png and .bmp file work ok.

Here is some information may help:
OS: Mac OS Sierra
python                    2.7.13
opencv                    2.4.8 
libxml2                   2.9.4                         0  
lxml                      3.7.3                    py27_0
pyqt                      4.11.4                   py27_4  
qt                        4.8.7                         4 

Please help~ Thanks a lot.

**Comment by Spark001** [comment]
I don't know how to solve it on Mac, but I encountered the same problem in my Windows 10 OS.

I solve it as follow:
Copy the **imageformats** folder from Qt installation's "plugins" folder to my application folder.
So the folder structure be:
\<app folder\>
.exe
imageformats/*.dll

Besides, you can use `QImageReader::supportedImageFormats();  ` to print which format it supports.

I hope that will be helpful.

**Comment by yjmade** [comment]
use python3 and qt5, much more image format support. do `make qt5py3` to build
