### ISSUE TITLE
Remove unnecessary labels for yolo classes.txt file

### ISSUE THREAD

**Issue by epomatti** [tzutalin/labelImg#624]
When I save my labels file with yolo format (txt) it keeps saving other tags.

How can I stop this behavior? I tried to find it in the app but I can't figure out how.

Also I tried creating the `classes.txt` only with my tags but it was overridden.

Example:

```
dog
person
cat
tv
car
meatballs
marinara sauce
tomato soup
chicken noodle soup
french onion soup
chicken breast
ribs
pulled pork
hamburger
cavity
my_new_tag_1
my_new_tag_2
```

**Comment by AnhPC03** [comment]
@epomatti 
You can find a class file in the folder. The file saves the labels defined in /labelimg/data/predefined_classes.txt.

The solution is to modify your class file and add new tags.

**Comment by chukwujike** [comment]
I tried editing the predefined_classes.txt but the other tags keeping coming up

**Comment by AlizerUncaged** [comment]
Why isn't this empty by default? Now I have to manually adjust classes to all of my 500 images haha

**Comment by Avv22** [comment]
Thank you. The solution to clear the predefined classes worked for me.

**Comment by ShubhamSongire** [comment]
Your Welcome!

**Comment by mahyah-00** [comment]
> Why isn't this empty by default? Now I have to manually adjust classes to all of my 500 images haha

You can use a python script to fix it
