### ISSUE TITLE
How to add shortcut when I create a label？

### ISSUE THREAD

**Issue by Spark001** [tzutalin/labelImg#63]
When I labeled an image, I find there are so many **car** than other categories. 
I want to create a shortcut when I add the **car** label instead of making double click.

Please help~ Thanks a lot.

**Comment by tzutalin** [comment]
Try "Ctrl + d":	Copy the current label and rect box?

**Comment by Spark001** [comment]
I mean that when I choose the type of labels, I want use a shortcut other than double click. Because I can add the label by my left hand, while create rect box by my right hand. I think it is more efficient.

For example:

1. Left hand: "**w**" -> create a rect box

1. Right hand: click -> choose two point

1. Left hand: "**Space**" -> add the label **Car**

In step 3, I use key "Space" to choose the label "**Car**" by left hand instead of making two click by right hand.

**Comment by tzutalin** [comment]
Ok. I got it . It can be a to-do item.
By the way, if you have to label a lot of the object with the same category in one Image, you can try to clone or copy the bounding box by using ctrl + d.

**Comment by Spark001** [comment]
I implemented some functions to solve the problem I encountered.

To add a label, instead of making mouse double left click, I use the mouse left click to choose one label, then **Space** to add it.

I hope it will make user more friendly : )

**Comment by tzutalin** [comment]
@Spark001 ,
  Ok. I will refer to your change, then merge it if necessary.
