### ISSUE TITLE
Error with Qt platform plugin "xcb" when start labelImg

### ISSUE THREAD

**Issue by vovaekb** [tzutalin/labelImg#630]
I am using Ubuntu 14.04. I have installed labelImg both ways: from source and using pip install. In both cases when start labelImg I get following error: 

```
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.
```
 
- **OS:** Ubuntu 14.04
- **PyQt version:** 5

**Comment by AnhPC03** [comment]
@vovaekb Have you try the following yet?
Run this first:
``` sudo apt-get update```
Then run command:
``` sudo apt-get install pyqt5-dev-tools ```

**Comment by vovaekb** [comment]
@AnhPC03 Yes, I tried it. I did all steps from [guide](https://mlnotesblog.wordpress.com/2017/12/16/how-to-install-labelimg-in-ubuntu-16-04/) and this didn't work.

**Comment by AnhPC03** [comment]
@vovaekb can you show all errors?

**Comment by clizarralde** [comment]
In my case the issue was that libxcb-xinerama0 was missing. I've found out after setting the export QT_DEBUG_PLUGINS=1

Something like: https://askubuntu.com/questions/308128/failed-to-load-platform-plugin-xcb-while-launching-qt5-app-on-linux-without

**Comment by vovaekb** [comment]
> In my case the issue was that libxcb-xinerama0 was missing. I've found out after setting the export QT_DEBUG_PLUGINS=1
> 
> Something like: https://askubuntu.com/questions/308128/failed-to-load-platform-plugin-xcb-while-launching-qt5-app-on-linux-without

Thank you. I will try this.

**Comment by lxb1989** [comment]
I have the same issue, and use 'sudo python3 labelImg.py', it works for me.
My os is ubuntu18.04.
@vovaekb

**Comment by vovaekb** [comment]
> I have the same issue, and use 'sudo python3 labelImg.py', it works for me.
> My os is ubuntu18.04.
> @vovaekb

Thank you very much! It works.

**Comment by mastermanband** [comment]
> I have the same issue, and use 'sudo python3 labelImg.py', it works for me.
> My os is ubuntu18.04.
> @vovaekb

thank you, I killed 2 days to find a solution
