### ISSUE TITLE
annotation aren't save

### ISSUE THREAD

**Issue by InbarKedem** [tzutalin/labelImg#634]
I'm started to labeling pictures, but I cannot save the annotation in my computer, when I press the save just nothing happen. I tried to use the save as button but the result was the same.
Windows 10
the latest version of lavelImg

**Comment by cschar** [comment]
@InbarKedem in the Readme they have a tutorial for setting up.

one of the lines is this
`pyrcc5 -o libs/resources.py resources.qrc`

run it in the base folder beside your labelImg.py
should fix your problem!

**Comment by InbarKedem** [comment]
Maybe I did something wrong. anyway, I followed this tutorial and it worked. 
https://medium.com/@sanghuynh_73086/how-to-install-labelimg-in-windows-with-anaconda-c659b27f0f
