### ISSUE TITLE
How to load yolo label file?

### ISSUE THREAD

**Issue by luvwinnie** [tzutalin/labelImg#639]
I got a directory that include jpg file and yolo's label txt files and classes.txt, however, I can't load the label file....
Does anyone know how to solve this?

- **OS:MacOS 10.15.6**
- **PyQt version:5.14.0**

**Comment by cschar** [comment]
@luvwinnie when you run on commandline, 1st arg is train directory, 2nd arg is your classes.txt ?
e.g.
`python labelImg.py /path/to/training/data/folder/ /path/to/file/mylabels.txt

**Comment by luvwinnie** [comment]
@cschar Thank you so much, it seems like my label not in the same directory, but thank you for your reply

**Comment by guysoft** [comment]
Hey, just tried with latest master and it does nt seem to load:
```
python labelImg.py /path/to/training/data/folder/ /path/to/file/mylabels.txt
```
But I seem to get no taggs loaded, and no error message.
My stdout shows:
```
python3 /labelImg/labelImg.py /datasets/split-fixed-last/train2017/  /datasets/split-fixed-last/
annotations/instances_train2017.txt
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
```

Moreover when in YOLO mode selected I pick the "open annotations" from the ``file`` dropdown menu nothing happens. It does using VOC mode.

**Comment by christian-cahig** [comment]
> Hey, just tried with latest master and it does nt seem to load:
> 
> ```
> python labelImg.py /path/to/training/data/folder/ /path/to/file/mylabels.txt
> ```
> 
> But I seem to get no taggs loaded, and no error message.
> My stdout shows:
> 
> ```
> python3 /labelImg/labelImg.py /datasets/split-fixed-last/train2017/  /datasets/split-fixed-last/
> annotations/instances_train2017.txt
> QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
> libGL error: No matching fbConfigs or visuals found
> libGL error: failed to load driver: swrast
> libpng warning: iCCP: known incorrect sRGB profile
> libpng warning: iCCP: known incorrect sRGB profile
> ```
> 
> Moreover when in YOLO mode selected I pick the "open annotations" from the `file` dropdown menu nothing happens. It does using VOC mode.

I'm experiencing the same problem with the YOLO format.
