### ISSUE TITLE
Terminal error: "ZeroDivisionError: float division by zero," program crashes when attempting to create YOLO training samples on large images

### ISSUE THREAD

**Issue by ib124** [tzutalin/labelImg#648]
I am trying to label images (with bounding boxes) with the YOLO format, but the program keeps crashing when I try to label large images (works fine with Pascal VOC samples). I have several UAV images (dimensions 4000 x 3000 pixels) taken at low altitude, and I need to label these images, as they are very high-resolution and useful for my project. However, when I splice the images into 1000 x 1000 pixel images and convert from .jpg to .png format, it will save the samples just fine. I am using a conda environment to run the code, and am relatively new to Python.

Note: Installation followed [this](https://medium.com/@sanghuynh_73086/how-to-install-labelimg-in-windows-with-anaconda-c659b27f0f) tutorial.

The following code was run to open the program in Anaconda Shell:
```
conda activate labelImg
cd D:\\myDirectory
python labelImg.py       D:\imageDirectory_with_multiple_images      D:\imageDirectory\text_file_with_class_specified.txt
```
Note that there is one class to classify in the text file, "weeds."

After specifying where to save the YOLO samples (D:\imageDirectory_with_multiple_images), I opened the big image (First image below) to create training samples, but when clicking the "save" or "Next Image" button, the program crashes with the following error:

```
Traceback (most recent call last):
  File "labelImg.py", line 1339, in saveFile
    self._saveFile(savedPath)
  File "labelImg.py", line 1371, in _saveFile
    if annotationFilePath and self.saveLabels(annotationFilePath):
  File "labelImg.py", line 837, in saveLabels
    self.lineColor.getRgb(), self.fillColor.getRgb())
  File "D:\labelImg\libs\labelFile.py", line 89, in saveYoloFormat
    writer.save(targetFile=filename, classList=classList)
  File "D:\labelImg\libs\yolo_io.py", line 70, in save
    classIndex, xcen, ycen, w, h = self.BndBox2YoloLine(box, classList)
  File "D:\labelImg\libs\yolo_io.py", line 37, in BndBox2YoloLine
    xcen = float((xmin + xmax)) / 2 / self.imgSize[1]
ZeroDivisionError: float division by zero
```

However, after slicing the big photos to smaller photos with dimensions of 1000 x 1000 using the following Python code in Jupyter Notebook...
```
import glob, os
import image_slicer

for file in glob.glob('D:\\directory_of_large_images'):
    image_slicer.slice(file, row=3, col=4)
```

...the YOLO training samples save just fine.  The second attached photo (below) is a smaller, sliced photo that allowed the training samples to be saved, and did not crash the program.

Let me know if any other information is needed to solve the issue. Thanks!

![weed32819](https://user-images.githubusercontent.com/71450942/93521927-529ebf00-f8f6-11ea-924d-c7f66054de69.png)

![weed9](https://user-images.githubusercontent.com/71450942/93522122-a27d8600-f8f6-11ea-81f3-20352870f40c.png)

**Comment by Orangeman69** [comment]
I had the same error: "ZeroDivisionError: float division by zero". My problem was that i had "jpg"s, but they really were pngs, but i renamed them to .jpg . Open the file with Notepad and see if the first line is: "‰PNG". If it is then the file's extension should be .png . I made a script to detect if the file is really a png and ,then renames it. repo: https://github.com/Orangeman69/RenameFakeJPGsToPNG
