### ISSUE TITLE
There are 2 actions of the shortcut 'Ctrl+D'

### ISSUE THREAD

**Issue by EddyKuo** [tzutalin/labelImg#652]
- OS: Windows 10 x64
- PyQt version:

Ctrl + D is copying a selected bounded box, but now there is a new function to delete current image.
And now the Ctrl + D is not working for copying.

**Comment by EddyKuo** [comment]
I have fix the issue, but the 'deleteImg' should be disabled.
Replace "CTRL+D" into "None" at line 245
deleteImg = action(getStr('deleteImg'), self.deleteImg, None, 'close', getStr('deleteImgDetail'))
The duplicate rect-box will work.

**Comment by tzutalin** [comment]
Good finding. There are duplicated ctrl+D hotkey. I will fix this by changing delete image hotkey to `'Ctrl+Shift+D`

**Comment by tzutalin** [comment]
949e46c
