### ISSUE TITLE
resources.py not found

### ISSUE THREAD

**Issue by mansi-aggarwal-2504** [tzutalin/labelImg#656]
I downloaded the latest code and I can't find `resources.py`.
![labelImg](https://user-images.githubusercontent.com/60866597/95962353-e4c9b280-0e23-11eb-9d61-c27364936e38.PNG)

I am using Anaconda Prompt in the labelImg directory.
Can someone help?

**Comment by SoonWhenHow** [comment]
there should be a resouces.py above the resouces.qrc ,and you must move it into the libs folder yourself, but it seems resouces.py get lost in the project

**Comment by mansi-aggarwal-2504** [comment]
@SoonWhenHow yeah I moved the `resources.qrc` to libs but can't find `resources.py`

**Comment by AguRodCan** [comment]
The resources.py its created when you run the "pyrcc5 -o libs/resources.py resources.qrc"

I had trouble making it work as its in the READ.ME

try doing it with the compleat path.

C:\Python35\Scripts\pyrcc5 -o C:\Desktop\labelImg\libs\resources.py

https://stackoverflow.com/questions/58140305/labelimg-pyrcc5-is-not-recognized-as-an-internal-or-external-command

**Comment by najmuddinsiddique** [comment]
When i run the following commad, i am getting 
python labelImg.py


Loading setting failed
Traceback (most recent call last):
  File "labelImg.py", line 1699, in <module>
    sys.exit(main())
  File "labelImg.py", line 1695, in main
    app, _win = get_main_app(sys.argv)
  File "labelImg.py", line 1688, in get_main_app
    args.save_dir)
  File "labelImg.py", line 119, in __init__
    self.label_dialog = LabelDialog(parent=self, list_item=self.label_hist)
  File "E:\Nicholas\FaceRecognitionApp\RealTimeObjectDetection\Tensorflow\labelImg\libs\labelDialog.py", line 37, in __init__
    layout.addWidget(bb, alignment=Qt.AlignmentFlag.AlignLeft)
AttributeError: type object 'AlignmentFlag' has no attribute 'AlignLeft'
