### ISSUE TITLE
meaning of xmin, ymin, xmax and ymax

### ISSUE THREAD

**Issue by tmdgml-96** [tzutalin/labelImg#658]
- **OS:**
- **PyQt version:**

`<bndbox>
			<xmin>647</xmin>
			<ymin>825</ymin>
			<xmax>1300</xmax>
			<ymax>1238</ymax>
</bndbox>`

In this case, What's the meaning of xmin, ymin, xmax and ymax?
Each means... xmin : left, ymin : top, xmax : right, ymax : botttom?

Is that right? Or Is it wrong?

**Comment by utsavraj** [comment]
**xmin, ymin:** coordinates of top left corner of the bounding box/rectangle. _Note: The top-left most corner of the image starts from 1 and hence, both of them start from 1 and not 0._

**xmax, ymax:** coordinates of the bottom right corner of the bounding box/rectangle _Note: Maximum value of xmax is width of the image while maximum value of ymax is the height of the image._

**Comment by tmdgml-96** [comment]
@utsavraj I solved it before. But thank you for the answer. I'll check again to see if the code I modified is correct.

**Comment by ibrandiay** [comment]
@tmdgml-96 @utsavraj Hello and sorry for opening the question. I just want to ask with this coordinate system, how were you able to recover the coordinates in real size of the image? thank you for helping me
