### ISSUE TITLE
Autosave

### ISSUE THREAD

**Issue by eschacht** [tzutalin/labelImg#668]
Autosave did not work for me.
I fix it by changing the code in line 1114.

line 1114: 
filedir = filePath.split(basename)[0].split("/")[-2:-1][0] to filedir = filePath.split(basename)[0].split("\ \ ")[-2:-1][0]

**Comment by tzutalin** [comment]
Hi @eschacht ,
Thanks. I think it is OS file path separator issue. I will fix it

**Comment by tzutalin** [comment]
Fixed https://github.com/tzutalin/labelImg/commit/e13d154ad8b2217883cbedd085ffba00d8753f40
