### ISSUE TITLE
Not working on new MacOS Big Sur

### ISSUE THREAD

**Issue by taozang62** [tzutalin/labelImg#672]
Hi, I just updated my Mac to Big Sur and I couldn't open labelImg after typing python labelimg.py. 
There will be an icon shown at the bottom of the screen, but no window will pop up as usual. Thank you for any help!

**Comment by tzutalin** [comment]
Hi @taozang62 ,
Do you see any error in the terminal? My theory is that something wrong with python QT? Could you try to update python QT?

**Comment by taozang62** [comment]
Hi, @tzutalin there is no error shown in terminal. But there is an icon shown in task bar. But I cannot open it or show any window.

**Comment by xeonye** [comment]
pip install  pyqt5==5.12.1

**Comment by tzutalin** [comment]
@xeonye ,
Do you mean installing pyqt 5.12.1 can resolve the problem?

**Comment by tzutalin** [comment]
Close this one since it is duplicated. https://github.com/tzutalin/labelImg/issues/661

**Comment by taozang62** [comment]
Hi @tzutalin the code above works!

**Comment by guanyichen** [comment]
Hi all,
>pip install pyqt5==5.12.1
The above command really works for the Mac OS Big Sur.
Highly Recommend the user who encountered the similar issue try this solving method.
`pip3 install pyqt5==5.12.1 lxml`
`make qt5py3`
`pip3 install labelImg`

**Comment by Maogeer** [comment]
it works!

**Comment by debugger89** [comment]
installing the pyqt5==5.12.1 solves the problem in Big Sur. Thanks, @tzutalin, @guanyichen 
```
pip3 install pyqt5==5.12.1 lxml
make qt5py3
pip3 install labelImg
```

**Comment by tzutalin** [comment]
What’s error
