### ISSUE TITLE
[Running] /usr/bin/env python "/tmp/tempCodeRunnerFile.python" Traceback (most recent call last):   File "/tmp/tempCodeRunnerFile.python", line 27, in <module>     from PyQt4.QtGui import * ImportError: No module named PyQt4.QtGui

### ISSUE THREAD

**Issue by potusiman** [tzutalin/labelImg#688]
Hello i am running a raspberry pi 400 (Linux)(chrome) and am having some trouble getting labelimg to run.. I'm not entirely sure if this is a possibility as i'm new to pi ad linux but it seems to be doable i am just missing a few items it seems. hopefully someone can help resolve this issue -- ive a attached a screenshot of different errors i'm incurring including various traceback errors concerning lib/pyqt/and other condundrums, i would also ask that someone takes time to do some basic explaining of these various concepts as i've looked them up and am having some trouble wrapping my brain around them, in a perfect world i will be able to run labelimg or some alternative compatible software to label some image datasets thanks!
-->
![2020-12-28-164907_3840x2160_scrot](https://user-images.githubusercontent.com/74438435/103230218-c8221e80-492c-11eb-92e9-05a687a2df3f.png)

- **OS:**
- **PyQt version:**](url)

**Comment by potusiman** [comment]
one other thing im not sure exactly what all extensions plugins this thing (pi) can run for things like python etc so breaking down to the leanest most rudimentary solution would be greatly advantageous in our question to stumbling upon a solution

**Comment by potusiman** [comment]
![2020-12-28-170456_3840x2160_scrot](https://user-images.githubusercontent.com/74438435/103231090-e38e2900-492e-11eb-84c8-d11dc171de64.png)
also it states that python is already newest version but it seems labelimg requires something additional to runn

**Comment by potusiman** [comment]
Traceback (most recent call last):
  File "/home/pi/.local/bin/labelImg", line 5, in <module>
    from labelImg.labelImg import main
  File "/home/pi/.local/lib/python2.7/site-packages/labelImg/labelImg.py", line 26, in <module>
    from PyQt4.QtGui import *
ImportError: No module named PyQt4.QtGui

**Comment by potusiman** [comment]
this seems to be core issue when trying to run labelImg

**Comment by tzutalin** [comment]
I will suggest using pytho qt5
