### ISSUE TITLE
Please update to pyqt5 for mac

### ISSUE THREAD

**Issue by vitamin** [tzutalin/labelImg#69]
pyqt4 could not be found in mac
```
localhost:labelImg didi$ brew install pyqt4
Error: No available formula with the name "pyqt4"
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
Error: No formulae found in taps.
```

after installing
```
brew install pyqt5
brew install libxml2 --force
make pyqt5
```

something wrong...

```
localhost:labelImg didi$ python labelImg.py
Traceback (most recent call last):
  File "labelImg.py", line 25, in <module>
    from PyQt4.QtGui import *
ImportError: No module named PyQt4.QtGui
localhost:labelImg didi$
```

**Comment by aaronshan** [comment]
@vitamin 

You can use `pyqt5`. latest pyqt5 has bug, please see #71

**Comment by dqhieu** [comment]
@aaronshan I tried to follow [#71](https://github.com/tzutalin/labelImg/issues/71). I got the same problem with you but when I ran command `install pyqt5.7`it gave me this
<img width="1194" alt="screen shot 2017-05-16 at 10 34 18 pm" src="https://cloud.githubusercontent.com/assets/8291457/26115343/f008231e-3a89-11e7-8c52-aa7325d8bdb4.png">

**Comment by XiomarG** [comment]
@dqhieu  that's quite interesting because I tried to follow #71 on another mac and confronted the same error you did. I ended up with copying my pyqt5.rb in my mac to that mac and it worked. I don't know what has changed on homebrew or something else.

**Comment by XiomarG** [comment]
This is really stupid.
I have installed labelImg in various mac machines.
The first two were ok. Just follow #71.
The third one had some issue. In /Formula there is no pyqt5.rb. I don't know why, and I cannot run `git reset XXXXXXXXX pyqt5.rb`. I copied my pyqt5.rb there, and installed it. It worked.
I am working on the fourth machine now. Even if I have installed pyqt5@5.7.1_1, I still received the error 
```
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: cgImage != NULL'
```
Totally lost.

**Comment by dqhieu** [comment]
It's a disaster :(

**Comment by XiomarG** [comment]
@dqhieu  did you confirm that do you have pyqt5.rb at all?

**Comment by dqhieu** [comment]
@XiomarG how can I do that?

**Comment by XiomarG** [comment]
in the Formula folder, run `ls | grep pyqt5` what do you see?

**Comment by dqhieu** [comment]
I see nothing
<img width="697" alt="screen shot 2017-05-18 at 1 17 41 pm" src="https://cloud.githubusercontent.com/assets/8291457/26188952/64a35584-3bcc-11e7-85f6-b98e7f5966c6.png">

**Comment by XiomarG** [comment]
so you don't have it. I don't know why git checkout pyqt5.rb didn't return error.

**Comment by XiomarG** [comment]
I finally solved my issue. Even though I installed pyqt5@5.7.1, the pyqt is still at version 5.8.2, and labelImg will refer to this pyqt somehow.
I did `brew uninstall pyqt` then it worked....

**Comment by lminer** [comment]
FYI, you cant get pyqt4 installed pretty easily if you use anaconda. No need for homebrew or pyqt5. Once anaconda is setup, it's as easy as `conda install pyqt=4.11.4`
