### ISSUE TITLE
Labeled dataset does not appear in labelImg

### ISSUE THREAD

**Issue by ondereser** [tzutalin/labelImg#697]
When I download the labeled dataset from the internet, the labels do not appear in the labelImg program.

**Comment by kurtjcu** [comment]
double check the image urls in the xml files, they will probably need to be amended to reflect new location of data

**Comment by kurtjcu** [comment]
I have a stripped back version of the dataset processing that should be pretty generic. https://colab.research.google.com/drive/1IKL4MHeKhYlPcKBO3ox1yQciYP1sFdZE
