### ISSUE TITLE
File explorer is missing for no reason

### ISSUE THREAD

**Issue by hdnh2006** [tzutalin/labelImg#706]
Hello, I was using labelimg and suddenly the file explorer is missing.
![image](https://user-images.githubusercontent.com/17271049/107657059-11cc8b80-6c85-11eb-8652-e11aca4b5485.png)

What I have to do to view again this explorer?

Thanks in advance

- **OS:** Ubuntu 20.04
- **PyQt version:** Python3.8

**Comment by tandes** [comment]
I have the same problem on macOS Catalina.

**Comment by hdnh2006** [comment]
It seems nobody gives support to this repo. I reinstall labelImg into virtualenv

**Comment by tzutalin** [comment]
Hi you might need to delete hidden pref file located in -/.labeling.pkl
