### ISSUE TITLE
LabelImg YOLO class problem on Ubuntu

### ISSUE THREAD

**Issue by shaiful019** [tzutalin/labelImg#707]
I've 20 images in a directory. I created a classes.txt file and mentioned all the classes in a particular order. Let's say I've three classes. So I created my classes.txt like this.

cat
dog
bird
that means cat as label 0, dog as label 1, and bird as label 2. And then I opened the labelImg to annotate those images with YOLO format. But the problem is when I annotated the first picture which contains a dog, all the classes of my classes.txt are getting vanished and classes.txt has only one class named dog with the label 0.

I just want my dog labeled as 1 instead of 0 as I already created the class order on classes.txt

- **OS:** Ubuntu
- **PyQt version:** 5.9.7

**Comment by SerSerg** [comment]
Try to change /labelimg/data/predefined_classes.txt so it contains your three classes. This could help

**Comment by anahithambardzumyan** [comment]
Always clone the repository, don't install or built it manually. after thet change the file data/predefined_classes, and then run labelimg using `python3 labelImg.py ` command. everything should be ok

**Comment by mjeedelamen** [comment]
just change  a directory again
