### ISSUE TITLE
Hotskeys for Next-Image and Prev-Image

### ISSUE THREAD

**Issue by PushkarChatterji** [tzutalin/labelImg#715]
- **OS: Ubuntu 18.04**
- **PyQt version:qt5py3**

Very useful tool.

Would be an awesome 'quality of life' improvement to add hot-keys for "next image" and "prev image"

**Comment by sampreets3** [comment]
Hi @PushkarChatterji, 
I believe there already exists hotkeys for navigating to the next image and the previous image *(the keys **A** and **D** respectively)*. Have you tried them out?

Maybe you want to check this section of the README : https://github.com/tzutalin/labelImg#hotkeys
