### ISSUE TITLE
May add function of landmarks?

### ISSUE THREAD

**Issue by nopattern** [tzutalin/labelImg#72]
Thanks for your great work. It's clean and simple.
     I want to add some labels such as facial landmarks. Have you any plan ? Or have any suggestion?

**Comment by tzutalin** [comment]
@nopattern 
 The use case is specified to some fields, and I don't have resources to help you. My suggestion is that you can try to modify the source code to fit your requirements

**Comment by nopattern** [comment]
ok ,thank you again.
