### ISSUE TITLE
CreateML annotation format does not work.

### ISSUE THREAD

**Issue by Cerno-b** [tzutalin/labelImg#724]
The CreateML annotation format is currently not supported in the tool. It can be selected, but saving and loading does not work. I assume that this is a temporary fix for some incompatibility, but I would suggest either making it work or getting rid of the format altogether to not have unexpected behavior in the tool

_Originally posted by @Cerno-b in https://github.com/tzutalin/labelImg/pull/723#r598457996_

**Comment by az-oolloow** [comment]
@tzutalin While saving works, loading doesn't work for me with CreateML :(
