### ISSUE TITLE
Labels move themselves.

### ISSUE THREAD

**Issue by TrungKhoaLe** [tzutalin/labelImg#729]
Hi,

I am labeling objects on tiny-dimension images (about width=150 x height=90). There is one thing that I've struggled finding a solution: That is the moving of done labels. 

How I detected: After finishing labeling several images, I came back and double-checked the accomplished ones. I realized that they didn't stay in the position they were supposed to stay. 

Has anyone encountered this issue before? Please give me some advice. Thanks

- **OS: Ubuntu 18.04**
- **PyQt version: 5.15.0**

**Comment by Ledorub** [comment]
Do you save in YOLO format?

**Comment by TrungKhoaLe** [comment]
Yes! I did use the YOLO format.

**Comment by Ledorub** [comment]
Well couple of days earlier I faced the same issue. Box shifts by 1px because of wrong rounding.
Already developed a fix, will open pull request today.

**Comment by TrungKhoaLe** [comment]
Did you update the yolo_io.py file?

**Comment by Ledorub** [comment]
Yes, you can read more here: #730.

**Comment by TrungKhoaLe** [comment]
In my case, I had to change them to %.32f's
