### ISSUE TITLE
"width" and "height" fields in "size" dict is set to zero instead of real img dims 

### ISSUE THREAD

**Issue by silcowitz** [tzutalin/labelImg#73]
I was trying to fix up some bad VOC2012 annotations and this came up

**Comment by silcowitz** [comment]
seems something breaks inside savePascalVocFormat(), it tries to load an xml file (to get the dims) which presumably should had been an image file

**Comment by rtgoring** [comment]
Please see: https://github.com/tzutalin/labelImg/issues/59

This sounds like the same issue.
