### ISSUE TITLE
Problem when installing it with docker

### ISSUE THREAD

**Issue by KansaiUser** [tzutalin/labelImg#732]
I have tried the docker version of your software

I did

1. git clone your repo
2. docker pull tzutalin/py2qt4
3. run thee docker run instruction you got in the readme
4. inside the container `make all`

I got 
```

pyrcc5 -o libs/resources.py resources.qrc
make: pyrcc5: Command not found
make: *** [qt5py3] Error 127

```

What can I do to solve this. I tried `apt-get install pyqt5-dev-tools` but after that make all makes an even larger set of errors

- **OS:**
- ubuntu 20
- 
- **PyQt version:**

**Comment by tzutalin** [comment]
when you use docker,    you should follow readme to use 
`make qt4py2;./labelImg.py` rather `make all`
