### ISSUE TITLE
No module named 'libs.resources'

### ISSUE THREAD

**Issue by waynemystir** [tzutalin/labelImg#748]
(ve) user1@comp1:~/path/to/labelImg$ python labelImg.py 
Traceback (most recent call last):
  File "labelImg.py", line 33, in <module>
    from libs.resources import *
ModuleNotFoundError: No module named 'libs.resources'

Ubuntu
- **PyQt version:** 5

**Comment by tzutalin** [comment]
try

make qt5py3
