### ISSUE TITLE
KeyError: <libs.shape.Shape object at 0x00000266308E3710>

### ISSUE THREAD

**Issue by LW-CVer** [tzutalin/labelImg#750]
Traceback (most recent call last):
  File "labelImg.py", line 726, in shapeSelectionChanged
    self.shapesToItems[shape].setSelected(True)
KeyError: <libs.shape.Shape object at 0x00000266308E3710>

OS:win10
PyQt version:5

**Comment by pletnes** [comment]
Could be a duplicate of #750

**Comment by tzutalin** [comment]
Thanks @pletnes who fixed it
