### ISSUE TITLE
can not read label.xml

### ISSUE THREAD

**Issue by Gavin-Huang** [tzutalin/labelImg#76]
when open label xml file console print error" AttributeError: "LabelFile " object has no attribute 'load'"
xml detail 
`<annotation>
  <folder>Imagedata</folder>
  <filename>Camera MV-U300#31F62505-9-Snapshot-20170327101952-3048953431</filename>
  <path>E:\Imagedata\Camera MV-U300#31F62505-9-Snapshot-20170327101952-3048953431.BMP</path>
  <source>
    <database>Unknown</database>
  </source>
  <size>
    <width>2048</width>
    <height>1536</height>
    <depth>3</depth>
  </size>
  <segmented>0</segmented>
  <object>
    <name>&#28938;&#28857;&#65288;&#24453;&#28938;&#25509;&#28857;&#65289;</name>
    <pose>Unspecified</pose>
    <truncated>0</truncated>
    <difficult>0</difficult>
    <bndbox>
      <xmin>380</xmin>
      <ymin>186</ymin>
      <xmax>486</xmax>
      <ymax>293</ymax>
    </bndbox>
  </object>
</annotation>
`
win7 64 bit 
labelImg v1.2.2
- **OS:**
- **PyQt version:**

**Comment by tzutalin** [comment]
It is fixed in the latest release
