### ISSUE TITLE
Hi，thank you for your tools!But could tell me how to compile the .py project to a .exe project?Thank you 

### ISSUE THREAD

**Issue by leoozy** [tzutalin/labelImg#77]
i have tired the tools included py2exe and pyinstaller ,but I haven't got it. Thank you for your time

**Comment by tzutalin** [comment]
Hi @leoozy ,
My os: Ubuntu
Steps:  
`cd labelImg/build-tools/ `
`sh envsetup.sh`
`sh build-windows-binary.sh`

**Comment by IvyGongoogle** [comment]
@leoozy it does not contains `install wine`
