### ISSUE TITLE
labellmg not showing old labels on images with annotation 

### ISSUE THREAD

**Issue by besbesmany** [tzutalin/labelImg#783]
I tried to open images with .txt files in yolo annotation but labellmg not show the labels on images

what can I do ?

**Comment by wangziren1** [comment]
Make sure that you open right image directory and right label directory. Press d button a few times, then you will see your labels.

**Comment by besbesmany** [comment]
thank you sir
I didn't know that we have 2 separate folders for images and labels

**Comment by Jelly123456** [comment]
@besbesmany Did you solve this problem? Or do you know how to open the old labels?
I am facing the same problem as you.

**Comment by anahithambardzumyan** [comment]
create classes.txt and write all your classnames there

**Comment by hissaanscorecarts** [comment]
in my case i had to change the annotation folder to the same folder as well. that's when annotations loaded.

**Comment by mansi-aggarwal-2504** [comment]
I have ~370 images in my folder, annotations for those with the same name in same folder, and a classes.txt file there. But the annotations are somehow only showing for the first two images.
