### ISSUE TITLE
can't make qt5py3

### ISSUE THREAD

**Issue by Dasun2020** [tzutalin/labelImg#784]
So I was following the mac instructions

`pip3 install pyqt5 lxml # Install qt and lxml by pip`
`make qt5py3`
`python3 labelImg.py`
`python3 labelImg.py [IMAGE_PATH] [PRE-DEFINED CLASS FILE]`

But after typing "make qt5py3" i get the problem
``make: *** No rule to make target `qt5py3'.  Stop.``
here's a picture:

<img width="431" alt="Screen Shot 2021-08-21 at 5 55 20 PM" src="https://user-images.githubusercontent.com/68830653/130335738-f6ea627f-61f9-4b57-99f7-044adac0b814.png">

another quick thing to note, I am using VsCode, so maybe thats affecting it?
Thanks in advance! 
**_EDIT:_**
turns out it's not vscode i tried it in normal terminal and it still didn't work

**Comment by Dasun2020** [comment]
So after using a Python 3 Virtualenv this now works, sooooo yeah.

**Comment by ergoego** [comment]
Can you say exactly what you did? I still can't get this to work for me, even with Python 3 and using Virtualenv. 

Running macOS 11.5.2
