### ISSUE TITLE
OSError

### ISSUE THREAD

**Issue by biotech70** [tzutalin/labelImg#836]
What causes the following error in Python 2.7 and how can it be fixed?
![design_analysis_error](https://user-images.githubusercontent.com/73783725/147747459-455a1361-a1c4-47ec-b3c7-9a41e6989a28.png)

**Comment by leventerevesz** [comment]
This error does not seem related to labelImg. 

It's a bug in your design_analysis.py file.

According to the backtrace you posted, the command line stored in the `weblogo_command` variable in design_analysis.py line 98 is trying to use nonexistent file. Look into this `weblogo_command` to find out more.

**Comment by tzutalin** [comment]
+1 leventerevesz@
