### ISSUE TITLE
labelIMG crashing while selecting Create Rect box

### ISSUE THREAD

**Issue by Asets2022** [tzutalin/labelImg#838]
- **OS:**
- **PyQt version:**

**Comment by Asets2022** [comment]
![image](https://user-images.githubusercontent.com/97979457/149992839-018c5ee7-e871-4803-a37f-6d3e79c636ac.png)
labelIMG crashes

**Comment by sammiee5311** [comment]
- [code](https://github.com/tzutalin/labelImg/blob/5c38b6bcddce895d646e944e3cddcb5b43bf8b8b/libs/canvas.py#L532)

``` python
p.drawLine(int(self.prev_point.x()), 0, int(self.prev_point.x()), int(self.pixmap.height()))
p.drawLine(0, int(self.prev_point.y()), int(self.pixmap.width()), int(self.prev_point.y()))
```

As you can see here, the arguments have changed to `int`.

However, yours not.

I guess you need to upgrade labeling ? or clone this repo and use it.

**Comment by Pf4rR3R** [comment]
Have the same problem. Downloaded through pip as well.

**Comment by evan-qin-xu** [comment]
Have the same issue, run by Python3.10, download it using pip3

**Comment by aztecbinaynay** [comment]
I have the same issue. Has it been resolved when downloading through pip?

**Comment by t89** [comment]
I can't recall the details anymore, but I think I resolved it by downloading this repository and installing by running `pip install -e .` inside of the directory. If I recall correctly the version uploaded to pip was outdated.

**Comment by Asets2022** [comment]
Can you please share the updated version with us?
Thanks ,

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by HridoyHazard** [comment]
facing the same issue now. anybody got a solutions ?

**Comment by IffahSaiful** [comment]
> facing the same issue now. anybody got a solutions ?

https://github.com/tzutalin/labelImg/issues/899#issue-1274532359 try check this one, the owner has fixed it

**Comment by HridoyHazard** [comment]
after using the latest version it fixed now

**Comment by shinymbowman** [comment]
@tzutalin I do not see the canvas.py changes to fix the cast to int( ) when 'pip install labelimg'. It installs version 1.8.6, but, this version still has the broken canvas.py code that tries to use float. Any suggestions on how I can pip install the latest with the fix?

**Comment by Mustafa-AlSaeed** [comment]
facing the same issue when installing through pip, any solution?

**Comment by fisilmiazizah** [comment]
#error
drawLine(self, l: QLineF): argument 1 has unexpected type 'float'

#how to fix it
on the python3.11/site-packages/libs/canvas.py

change the code to int;

p.drawRect(int(left_top.x()), int(left_top.y()), int(rect_width), int(rect_height))

p.drawLine(int(self.prev_point.x()), 0, int(self.prev_point.x()), int(self.pixmap.height()))
p.drawLine(0, int(self.prev_point.y()), int(self.pixmap.width()), int(self.prev_point.y()))

**Comment by MuhammadBilal848** [comment]
BRUHHHHHHH!! it's working. arigato.

The changes are working but with different variable names.
            p.drawRect(int(leftTop.x()), int(leftTop.y()), int(rectWidth), int(rectHeight))
            p.drawLine(int(self.prevPoint.x()), 0, int(self.prevPoint.x()), int(self.pixmap.height()))
            p.drawLine(0, int(self.prevPoint.y()), int(self.pixmap.width()), int(self.prevPoint.y()))

**Comment by PawanKuma** [comment]
I fixed it by creating new environment with python 3.6

**Comment by ashok01620** [comment]
This video solved everything:- [Float to Int](https://www.youtube.com/watch?v=5jHPuwo8z1o)

**Comment by ASV1995** [comment]
> This video solved everything:- [Float to Int](https://www.youtube.com/watch?v=5jHPuwo8z1o)

Its absolutely did as of 21NOV2023, this still works! thank you ashok01620!

**Comment by ferdiandhika** [comment]
For those who face this error. This is step by step:
1. For me its work on python version 3.8.0
2. Update pip version, put this command on gitbash:python -m pip install --upgrade pip
3. put this command on gitbash to download labelImg:pip3 install labelImg
4. run it on gitbash with this command:labelImg

hope this will fix your problem.
