### ISSUE TITLE
Mouse zoom yields float values, cause TypeError - int expected

### ISSUE THREAD

**Issue by pletnes** [tzutalin/labelImg#841]
LabelImg crashes under python 3 when zooming with the mouse. Apparently, some arithmetic results in `float` values, whereas the PyQt API expects `int`, causing an instant crash. I prepared a fix of this issue as well as a couple of other fixes in PR #840. I hope this is helpful.

Thanks for sharing LabelImg, I've found it to be quite useful, easy to use and very efficient enough for my purposes.

Version information:
- **OS: Windows 10**
- **Python version: Python 3.10.2**

```
lxml==4.7.1
PyQt5==5.15.6
PyQt5-Qt5==5.15.2
PyQt5-sip==12.9.0
PyQt5-stubs==5.15.2.0
```

**Comment by tzutalin** [comment]
Thanks
