### ISSUE TITLE
请受中国专利管辖的用户注意，你正常使用该软件可能造成专利侵权遭到起诉

### ISSUE THREAD

**Issue by zhi2xin1** [tzutalin/labelImg#843]
- **OS:** Windows  7 以上
- **PyQt version:** Python和与其相匹配的pip、PyQt等工具均为Python3及以上版本

该专利为中国的 东北农业大学 申请。该学校为双一流、211的中国重点建设高校之一。🥵🥵🥵🥵🥵🥵🥵🥵🥵🥵

专利号：CN201910992334.4

权利要求书：
1.针对深度学习的数据集标记方法，其特征在于，该方法包括以下步骤：(1)安装Python和pip；(2)下载并解压labelImg软件；(3)在步骤(1)安装Python和pip的基础上，pip下载PyQt5、pyqt5_tools、lxml；(4)在步骤(3)的基础上，在步骤(2)的解压后的文件夹下通过cmd 将Qt文件格式改 为Py thon格式 ；(5) 在步骤 (2) 的 解压 后的 文件夹下找到resources .py文件将其添加到libs文件夹；(6)在labelImg软件解压后的文件夹下用Python调用labelImg .py，打开labelImg；(7)在步骤(6)打开后的labelImg界面中，OpenDir按键选取待标记图片所在文件夹；ChangeSaveDir按键选取标记后的 .xml文件存储位置；(8)将图像按一定方法划分，所得即为深度学习所需的训练集与验证集。2.如权利要求1所述的一种针对深度学习的数据集标记方法，其特征在于：软件所基于的操作系统必须是Windows7及以上版本。3.如权利要求1所述的一种针对深度学习的数据集标记方法，其特征在于：Python和与其相匹配的pip、PyQt等工具均为Python3及以上版本，并且在安装Python时要将其添加到系统环境变量中。

**Comment by tzutalin** [comment]
不太明白這是什麼專利。
