### ISSUE TITLE
关于无法设置中文的问题请替换该文件

### ISSUE THREAD

**Issue by PTA00** [tzutalin/labelImg#847]
- 首先下载下面提供的文件，放入`\resources\strings`内，替换原文件。

    [strings-zh-CN.zip](https://github.com/tzutalin/labelImg/files/8032830/strings-zh-CN.zip)

    **注意：如果你已经编译过资源文件了，那么需要重新编译一次。**
    _（因为替换了文件所以需要重新链接）_

    例如：`pyrcc5 -o libs/resources.py resources.qrc`

- 然后需要编辑文件`\libs\stringBundle.py`的第52行，

    将字符串`":/strings"`替换为`":/strings-zh-CN"`即可。

- 最后再次运行`labelImg.py`，你会发现已经是中文了，请享受。

- **_如有错误请指正，包括翻译文件的内容_**

**Comment by PTA00** [comment]
4444

**Comment by PTA00** [comment]
**- 文件`strings-zh-CN.properties`的内容（相比仓库内源文件补充了缺少的翻译）**
```
openFile=打开文件
openFileDetail=打开图像文件
quit=退出
quitApp=退出程序
openDir=打开目录
copyPrevBounding=复制当前图像中的上一个边界框
changeSavedAnnotationDir=更改保存标签文件的预设目录
openAnnotation=开启标签
openAnnotationDetail=打开标签文件
changeSaveDir=改变存放目录
nextImg=下一个图像
nextImgDetail=下一个图像
prevImg=上一个图像
prevImgDetail=上一个图像
verifyImg=验证图像
verifyImgDetail=验证图像
save=保存
saveDetail=保存标签文件
changeSaveFormat=更改存储格式
saveAs=另存为
saveAsDetail=將标签保存到其他文件
closeCur=关闭文件
closeCurDetail=关闭当前文件
deleteImg=删除图像
deleteImgDetail=删除当前图像
resetAll=全部重置
resetAllDetail=重置所有设定
boxLineColor=区块线条颜色
boxLineColorDetail=选择线框颜色
crtBox=创建区块
crtBoxDetail=创建一个新的区块
delBox=删除选择的区块
delBoxDetail=删除区块
dupBox=复制区块
dupBoxDetail=复制区块
editBox=编辑区块
editBoxDetail=编辑区块
hideAllBox=隐藏所有区块
showAllBox=显示所有区块
tutorialDefault=YouTube教学
tutorialChrome=YouTube教学(Chrome)
tutorialDetail=显示示范内容
info=版本信息
shortcut=快捷键
zoomin=放大画面
zoominDetail=放大画面
zoomout=缩小画面
zoomoutDetail=缩小画面
originalsize=原始大小
originalsizeDetail=放大到原始大小
fitWin=调整到窗口大小
fitWinDetail=缩放到当前窗口大小
fitWidth=缩放到跟当前画面一样宽
fitWidthDetail=调整宽度适应到窗口宽度
editLabel=编辑标签
editLabelDetail=修改当前所选的区块颜色
shapeLineColor=形状线条颜色
shapeLineColorDetail=更改线条颜色
shapeFillColor=填充颜色
shapeFillColorDetail=更改填充颜色
showHide=显示/隐藏标签
useDefaultLabel=使用预设标签
useDifficult=有难度的
boxLabelText=区块的标签
labels=标签
autoSaveMode=自动保存模式
singleClsMode=单一类别模式
displayLabel=显示类别
fileList=文件列表
files=文件
advancedMode=专家模式
advancedModeDetail=切换到专家模式
showAllBoxDetail=显示所有区块
hideAllBoxDetail=隐藏所有区块
menu_file=文件(&F)
menu_edit=编辑(&E)
menu_view=查看(&V)
menu_help=帮助(&H)
menu_openRecent=最近打开(&R)
chooseLineColor=选择线条颜色
chooseFillColor=选择填充颜色
drawSquares=绘制正方形
```

**Comment by dashjim** [comment]
Thank you. It is needed to know that upgrade to newer version you should also execute `pyrcc5 -o libs/resources.py resources.qrc`

**Comment by PTA00** [comment]
已将修复中文作为了一个新的分支：https://github.com/PTA00/labelImg

**Comment by tzutalin** [comment]
Hi @PTA00 ,

could you submit a pull request? it will be great.

Otherwise, i can fix it based on your previous commnet

**Comment by tzutalin** [comment]
Fixed this https://github.com/tzutalin/labelImg/commit/dd6781656c06538dc87760c2376245716e39691d
based on @PTA00  repo

**Comment by PTA00** [comment]
Hi @tzutalin ,
In the `libs/stringBundle.py` :
Change `locale.getlocale()` to `locale.getdefaultlocale()` .Tests correctly on Windows .

![image](https://user-images.githubusercontent.com/59364024/157147359-ffed46cd-199f-479a-bec8-c1744c48bf55.png)

**Comment by tzutalin** [comment]
Thanks . Fixed https://github.com/tzutalin/labelImg/commit/0f111e643a2d44ffc984bac80f6602a4a5f17eda

**Comment by WangRongsheng** [comment]
> 已将修复中文作为了一个新的分支：https://github.com/PTA00/labelImg
> 
> * **无需再手动进行上述的修复操作！**

关于我一次使用遇到的问题以及解决方法：
1. 初次运行会出现：ModuleNotFoundError: No module named 'libs.resources'
解决方式是：修改`labelImg.py`文件第29行`from libs.resources import *`为'from resources import *'
2. 再次运行报错：AssertionError: Missing string id : useDefaultLabel
解决方式是：重新编译一次：`pyrcc5 -o resources.py resources.qrc`之后就可以完美运行
