### ISSUE TITLE
LabelImg does not read predefined_classes.txt

### ISSUE THREAD

**Issue by AndreaPisoni** [tzutalin/labelImg#85]
Hi, 
After i upgraded to version 1.3 I do not see the predefined choices for the labels. When I draw a box, the only thing I see is the text field to write the class name, I am not able to see the clickable list of classes. Any tip on how to get that back? 

data/predefined_classes.txt has the right labels as expected.

**Comment by tzutalin** [comment]
Hi,
  What is your OS? How do you get labelImg,e.g. using pip, download prebuilt, or download source code?

**Comment by AndreaPisoni** [comment]
Hi! Ubuntu 16.04 using pre-built. I have installed the ore-built on windows as well and there it works fine...

**Comment by blotimer** [comment]
I've met the same issue on Ubuntu 16.04. I installed it using pip.

**Comment by tzutalin** [comment]
Hi

**Comment by blateyang** [comment]
I meet the same problem even when I get labelImg from source code. My OS is also Ubuntu 16.04. Has this problem been solved?@ @tzutalin

**Comment by vdalv** [comment]
@tzutalin I think this issue can be closed.
