### ISSUE TITLE
FileList disappear & the box boundary line disappear

### ISSUE THREAD

**Issue by CT-Yang** [tzutalin/labelImg#87]
Dear Author:

I have used this tool for almost one month. It works well until 2 days ago.

I meet 2 questions as I mention below:

1. The filelist disappear(it happened sometimes)

This function is important for me. Because when there are many images in this file, I can directly click the image I want to label instead of clicking "next image" so many times. And the most important reason is, when I move to another directory, the annotation box will remain the same with the last image I labeled. Only if I click the desired image in the filelist , I can reload the corresponding annotation box for the new desired image.That's why I need this function.

![image](https://cloud.githubusercontent.com/assets/28501254/25779146/c69a4ca2-3343-11e7-8311-aa4a963795ff.png)

when the problem happen, it shows following messages:

```
Traceback (most recent call last):
  File "labelImg.py", line 1024, in openDir
    self.openNextImg()
  File "labelImg.py", line 1081, in openNextImg
    self.loadFile(filename)
  File "labelImg.py", line 875, in loadFile
    self.loadPascalXMLByFilename(xmlPath)
  File "labelImg.py", line 1224, in loadPascalXMLByFilename
    tVocParseReader = PascalVocReader(xmlPath)
  File "/labelImg/libs/pascal_voc_io.py", line 132, in __init__
    self.parseXML()
  File "/labelImg/libs/pascal_voc_io.py", line 161, in parseXML
    difficult = bool(int(object_iter.find('Difficult').text))
AttributeError: 'NoneType' object has no attribute 'text'
```

2. The bounding box's boundary line disappear

It's also important because when there are so many object in the image, sometimes it's hard for me to recognize which object I still not label yet. 

![image](https://cloud.githubusercontent.com/assets/28501254/25779211/813cef28-3345-11e7-8e39-42755a737a3a.png)

- **OS:  Ubuntu 16.04.2 LTS**
- **PyQt version: 4**

Hope you can fix these problems, thanks a lot!

**Comment by CT-Yang** [comment]
The problem 1 can be solved by downloading the Linux_v1.2.3.

And the problem 2 maybe have some problems in my computer.Because when I change to another computer and download the  Linux_v1.2.3, it not only can open the old version xml files successfully, but also can see the bbox lines. 

So I think problem 2 may not be a general problem for most of the users.

**Comment by tzutalin** [comment]
Can you share your image and xml?

**Comment by CT-Yang** [comment]
Although downloading the Linux_v1.2.3 can solve problem1, but it will cause the problem like #84 
I summary the way how I deal the current problem:
1. According the problem in #84 ,we have no choice but to download the newest version (1.3.0).

2. If the default annotation file set to the file which contains the old version xml file in the previous time, file list will disappear when we open labelImg in the next time. So if we meet this problem, we set the default annotation file to the file that doesn't contain the old version xml file, then close the program. And turn on again, the problem will be solved.

Hope this clue will help u(author) to fix such problem & update the newer version to deal these problem.

And I think the problem that the bbox line disappear have nothing to do with the image and xml file. In my previous computer,I had tried the images in the "tests" file, and still have this problem. If I misunderstand the reason for ur request, just ignore it.=)

**Comment by CT-Yang** [comment]
The reason that v1.3.0 can't read the old version xml file is just because the "diffucult" term in the xml file.
In the new xml file is "Difficult" but in old xml file is "difficult". That's the reason.
This is the updated version code:

[labelImg_修改版.zip](https://github.com/tzutalin/labelImg/files/987199/labelImg_.zip)

**Comment by tzutalin** [comment]
Thanks. I will check and merge it after I am done with my current work

**Comment by tzutalin** [comment]
Merge and fix it on https://github.com/tzutalin/labelImg/commit/a7e3a32385f7a458c667af17d20b650cfb9fa73f
Thanks again

**Comment by IvyGongoogle** [comment]
@tzutalin my 'File List' window disappears not only the 'File List' disappear. Crazy about this problem.
