### ISSUE TITLE
 I have a question about the program.

### ISSUE THREAD

**Issue by limhasic** [tzutalin/labelImg#874]
1. Is it possible to run an exe file without an anaconda environment?

2. I want to 'exe' this file, is there any other way other than making it with pyinstaller?

**Comment by tzutalin** [comment]
Is it possible to run an exe file without an anaconda environment?
```
yes, as long as you have pyqt dependencies
```

I want to 'exe' this file, is there any other way other than making it with pyinstaller?
```
yes, there is an alternative to package this to exe. I didn't compare which one is better in the recent years
```
