### ISSUE TITLE
some pictures become invalid after i labeled them

### ISSUE THREAD

**Issue by Lasper2016** [tzutalin/labelImg#88]
i meet some problems that some pictures become invalid after i label this picture such as the following picture. thanks very much!

- **OS:** windows10
- **labelimg_version:** windows_v
![206_190](https://cloud.githubusercontent.com/assets/20119271/26030324/f3a08876-3882-11e7-8b0d-b832a4f48041.jpg)
![206_202](https://cloud.githubusercontent.com/assets/20119271/26030325/f3a2ecd8-3882-11e7-9cb9-c36501c3c999.jpg)

1.3.0
- **PyQt version:**

**Comment by tzutalin** [comment]
Hi @Lasper2016 ,
  I cannot see the images. Does all of your images have the same problem or only that image?

**Comment by Lasper2016** [comment]
@tzutalin The image become invalid like following .
![204_11](https://cloud.githubusercontent.com/assets/20119271/26030286/b280133a-3881-11e7-8008-f8bfad27bb99.jpg)
only some images in my labeled image.For example, i have labeled about 300 ,and then i found there are about 30 images become invalid.

**Comment by vdalv** [comment]
I believe that this has since been resolved.
