### ISSUE TITLE
Why the saved file formats of annotations are lif but not xml?

### ISSUE THREAD

**Issue by qffun** [tzutalin/labelImg#89]
Hi
I used LabelImg to create annotations but the saved files are end of .lif but not .xml. I wish someone can tell me the reason or solution. Thanks a lot!  

- **OS:ubuntu16.04**
- **PyQt version:4**

**Comment by qffun** [comment]
I found that v1.3.0 does not have this problem.

**Comment by aaronshan** [comment]
@qffun you can revise `labelImg/libs/labelFile.py` file, change 

```
suffix = '.lif'
```

to

```
suffix = '.xml'
```

**Comment by qffun** [comment]
@aaronshan Thanks a lot!

**Comment by tzutalin** [comment]
Hi @qffun ,
I fixed it already.
https://github.com/tzutalin/labelImg/commit/7cf546b50030ea3efa9c24b1c18624e412c4f03b

**Comment by tzutalin** [comment]
suffix = '.lif' is the file which will serialize image raw data and annotation result to .lif file.

It is a legacy code.
