### ISSUE TITLE
argument 1 has unexpected type 'float' labelImg crashes

### ISSUE THREAD

**Issue by IffahSaiful** [tzutalin/labelImg#899]
hai can anyone help me? kept getting error when i tried to label the images, the labelImg crashes.

im working with python 3.9.12 and i"ve tried several solutions as well such as:

1. line 213 "self.dock.setFeatures(self.dock.features() ^ int(self.dock_features)) adding int to this line, 
2. reinstalling pip install -e . in the command where i did my project.

Traceback (most recent call last):
  File "D:\Documents\Master Stuffs Iffah\Sem 2\PS1\Apps\BIM Hand Gesture\TensorFlow\labelImg\labelImg.py", line 972, in new_shape
    text = self.label_dialog.pop_up(text=self.prev_label_text)
  File "D:\Documents\Master Stuffs Iffah\Sem 2\PS1\Apps\BIM Hand Gesture\TensorFlow\labelImg\libs\labelDialog.py", line 74, in pop_up
    offset += QPoint(btn.size().width()/4, btn.size().height()/2)
TypeError: arguments did not match any overloaded call:
  QPoint(): too many arguments
  QPoint(int, int): argument 1 has unexpected type 'float'
  QPoint(QPoint): argument 1 has unexpected type 'float'

**Comment by IffahSaiful** [comment]
> hai can anyone help me? kept getting error when i tried to label the images, the labelImg crashes.
> 
> im working with python 3.9.12 and i"ve tried several solutions as well such as:
> 
> 1. line 213 "self.dock.setFeatures(self.dock.features() ^ int(self.dock_features)) adding int to this line,
> 2. reinstalling pip install -e . in the command where i did my project.
> 
> Traceback (most recent call last): File "D:\Documents\Master Stuffs Iffah\Sem 2\PS1\Apps\BIM Hand Gesture\TensorFlow\labelImg\labelImg.py", line 972, in new_shape text = self.label_dialog.pop_up(text=self.prev_label_text) File "D:\Documents\Master Stuffs Iffah\Sem 2\PS1\Apps\BIM Hand Gesture\TensorFlow\labelImg\libs\labelDialog.py", line 74, in pop_up offset += QPoint(btn.size().width()/4, btn.size().height()/2) TypeError: arguments did not match any overloaded call: QPoint(): too many arguments QPoint(int, int): argument 1 has unexpected type 'float' QPoint(QPoint): argument 1 has unexpected type 'float'

i've finally solved this problem by changing this line. i just add "/" so instead of \labelImg\libs\labelDialog.py", line 74, in pop_up
offset += QPoint(btn.size().width()/4, btn.size().height()/2) 
i wrote offset += QPoint(btn.size().width()/4, btn.size().height()//2)

**Comment by tzutalin** [comment]
It sounds like it is a pyqt issue that some versions of that method are unable o support float. I just fixed it.  https://github.com/tzutalin/labelImg/commit/eb603c29e1d88085d4552da54074c044d5ec4841

**Comment by sprynt001** [comment]
I downloaded labelImg from pypi on 21/10/2022 and I have a similar issue. However, the lines above are not in `labelDialog.py`. The issues I am having are in `canvas.py` and other files and seem to stem from the use of `QPointF`, `QRectF` etc. Example errors:

```
TypeError: arguments did not match any overloaded call:
  drawLine(self, QLineF): argument 1 has unexpected type 'float'
  drawLine(self, QLine): argument 1 has unexpected type 'float'
  drawLine(self, int, int, int, int): argument 1 has unexpected type 'float'
  drawLine(self, QPoint, QPoint): argument 1 has unexpected type 'float'
  drawLine(self, Union[QPointF, QPoint], Union[QPointF, QPoint]): argument 1 has unexpected type 'float'
```

```
   p.drawRect(int(left_top.x()), int(left_top.y()), rect_width, rect_height)
TypeError: arguments did not match any overloaded call:
  drawRect(self, QRectF): argument 1 has unexpected type 'int'
  drawRect(self, int, int, int, int): argument 3 has unexpected type 'float'
  drawRect(self, QRect): argument 1 has unexpected type 'int'
```

```
venv/lib/python3.10/site-packages/labelImg/labelImg.py", line 965, in scroll_request
    bar.setValue(bar.value() + bar.singleStep() * units)
TypeError: setValue(self, int): argument 1 has unexpected type 'float'
```

**Comment by gonend** [comment]
Hi @sprynt001! 
I have the same issue, did you mange to fix it? 
if you have can u please explain how? 
thank you

**Comment by sprynt001** [comment]
Hi @gonend I tried making changes to various files, but in the end I gave up and used labelme ( from conda forge: https://anaconda.org/conda-forge/labelme )...

**Comment by sam-a-d** [comment]
**Having the same issue with the error codes below:**
**OS**: Ubuntu 22.10
**Python Version**: 3.10
**VEnv**: Python3 Venv

Traceback (most recent call last):
  File "/home/samad/.local/lib/python3.10/site-packages/libs/canvas.py", line 530, in paintEvent
    p.drawLine(self.prev_point.x(), 0, self.prev_point.x(), self.pixmap.height())
TypeError: arguments did not match any overloaded call:
  drawLine(self, l: QLineF): argument 1 has unexpected type 'float'
  drawLine(self, line: QLine): argument 1 has unexpected type 'float'
  drawLine(self, x1: int, y1: int, x2: int, y2: int): argument 1 has unexpected type 'float'
  drawLine(self, p1: QPoint, p2: QPoint): argument 1 has unexpected type 'float'
  drawLine(self, p1: Union[QPointF, QPoint], p2: Union[QPointF, QPoint]): argument 1 has unexpected type 'float'
QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
QPainter::begin: Painter already active
[1]    14029 segmentation fault (core dumped)  labelImg

**Comment by lyxxxh** [comment]
> I downloaded labelImg from pypi on 21/10/2022 and I have a similar issue. However, the lines above are not in `labelDialog.py`. The issues I am having are in `canvas.py` and other files and seem to stem from the use of `QPointF`, `QRectF` etc. Example errors:
> 
> ```
> TypeError: arguments did not match any overloaded call:
>   drawLine(self, QLineF): argument 1 has unexpected type 'float'
>   drawLine(self, QLine): argument 1 has unexpected type 'float'
>   drawLine(self, int, int, int, int): argument 1 has unexpected type 'float'
>   drawLine(self, QPoint, QPoint): argument 1 has unexpected type 'float'
>   drawLine(self, Union[QPointF, QPoint], Union[QPointF, QPoint]): argument 1 has unexpected type 'float'
> ```
> 
> ```
>    p.drawRect(int(left_top.x()), int(left_top.y()), rect_width, rect_height)
> TypeError: arguments did not match any overloaded call:
>   drawRect(self, QRectF): argument 1 has unexpected type 'int'
>   drawRect(self, int, int, int, int): argument 3 has unexpected type 'float'
>   drawRect(self, QRect): argument 1 has unexpected type 'int'
> ```
> 
> ```
> venv/lib/python3.10/site-packages/labelImg/labelImg.py", line 965, in scroll_request
>     bar.setValue(bar.value() + bar.singleStep() * units)
> TypeError: setValue(self, int): argument 1 has unexpected type 'float'
> ```

![b776877dfe67a05cac2bc2b201bfb7b](https://github.com/HumanSignal/labelImg/assets/35553218/8b4b538b-a0b5-457d-a401-7b319a947dc9)


## ps
too many float, I gave up too
