### ISSUE TITLE
How to build  a binary file from source?

### ISSUE THREAD

**Issue by mursalal** [tzutalin/labelImg#92]
Hello! I changed libs/pascal_voc_io.py in line 49
from

`filename.text = self.filename`

to

`filename.text = self.filename + '.jpg'`

Because PASCAL VOC format  have

`<filename>file.jpg</filename>`

not just

`<filename>file</filename>`

How can I build binary file? I think there may be problems during training because of this differences.

**Comment by tzutalin** [comment]
Hi @mursalal ,
      In pascal_voc_io.py, I used imgFileNameWithoutExt instead of imgFileName to save. As far as I know, pascal format won't append the file extension to the annotation file. Please correct me if I am wrong.

The below is an example which I got from ImageNet.
```
<annotation>
	<folder>n07805966</folder>
	<filename>n07805966_18</filename>
	<source>
		<database>ImageNet database</database>
	</source>
	<size>
		<width>500</width>
		<height>375</height>
		<depth>3</depth>
	</size>
	<segmented>0</segmented>
	<object>
		<name>n07805966</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>0</difficult>
		<bndbox>
			<xmin>150</xmin>
			<ymin>52</ymin>
			<xmax>430</xmax>
			<ymax>326</ymax>
		</bndbox>
	</object>
</annotation>

```

**Comment by mursalal** [comment]
I uploaded Pascal VOC dataset and there are filename+extension.

**Comment by tzutalin** [comment]
Hi @mursalal ,
 Can you share the link with us?

**Comment by mursalal** [comment]
Hi @tzutalin [host.robots.ox.ac.uk](http://host.robots.ox.ac.uk/pascal/VOC/voc2007/VOCtrainval_06-Nov-2007.tar)

**Comment by vdalv** [comment]
Closing this because labelImg now includes the filename+extension in the PascalVOC xml output files.

Not sure if the binary file question was resolved...Feel free to reopen if that's still an issue.
