### ISSUE TITLE
The output xml is not same as the VOC2007 XML

### ISSUE THREAD

**Issue by 315386775** [tzutalin/labelImg#96]
There are two different points:
1.The VOC2007 xml's filename is 000001.jpg.
2.Indented formats are different.

**Comment by 315386775** [comment]
the output is xx.lif.  Is it the same as the version of xml?

**Comment by 315386775** [comment]
i solve it in the closed issue. If i want to add more labels. where to modify the code. thank you

**Comment by 315386775** [comment]
i get it

**Comment by mursalal** [comment]
@tzutalin and tag "difficult" begins with lower case, not "Difficult"

**Comment by tzutalin** [comment]
@mursalal,
  It had been fixed in the latest code

**Comment by tzutalin** [comment]
Hi @315386775 ,
  Thanks. I will check it later

**Comment by 315386775** [comment]
@tzutalin https://github.com/sergeyk/skvisutils/blob/master/test/support/VOC2007/Annotations/000023.xml.
You can refer this one. thanks

**Comment by 315386775** [comment]
@tzutalin Have you modified the bug in my question? thanks.

**Comment by tzutalin** [comment]
Hi, 
 Not yet. I  does not have free time yet

**Comment by 315386775** [comment]
@tzutalin Hi. i download the version of v1.3.3, i can see you add some function. but the output xml maybe not correct. There are two difference:
The first: jpg
> Yours : <filename>000001</filename>
> VOC2007 : <filename>000023.jpg</filename>
The second: Indented formats
> Yours:
<annotation verified="no">
  <folder>Test</folder>
  <filename>000001</filename>
  <path>C:/Users/000001.jpg</path>
  <source>
    <database>Unknown</database>
  </source>
  <size>
    <width>6000</width>
    <height>4000</height>
    <depth>3</depth>
> VOC:
<annotation>
	<folder>VOC2007</folder>
	<filename>000023.jpg</filename>
	<source>
		<database>The VOC2007 Database</database>
		<annotation>PASCAL VOC2007</annotation>
		<image>flickr</image>
		<flickrid>220208496</flickrid>
	</source>
	<owner>
		<flickrid>thevelodrome.com</flickrid>
		<name>?</name>
	</owner>
	<size>
		<width>334</width>
		<height>500</height>
		<depth>3</depth>
	</size>

**Comment by mursalal** [comment]
Hi @315386775. Use this

`import os`
`from os import listdir`
`from os.path import isfile, join`

`path_to_anns = 'path/to/annotations'`
`file_names = [f for f in listdir(path_to_anns) if isfile(join(path_to_anns, f))]`

```
for i in file_names:
	f = open(i, 'r')
	content = f.read()
	#print content
	f.close()
	hm = content.replace('  ', '\t')
	f2 = open(i, 'w')
	f2.write(hm)
	f2.close()

**Comment by 315386775** [comment]
@mursalal Thanks. it works!

**Comment by freaad** [comment]
Did you compile the solved one? If you don't mind could you send to me or upload the code?

**Comment by tzutalin** [comment]
Hi,
 I will use '\t' as indent next release

**Comment by tzutalin** [comment]
Thanks for all of you. I fixed it https://github.com/tzutalin/labelImg/commit/27cf04aeccfe58fc7f58ea315b68b9f103c1114e
